<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>nl.numworx.notebook</groupId>
    <artifactId>notebook-parent</artifactId>
    <version>0.0.3-SNAPSHOT</version>
  </parent>
  <artifactId>notebook</artifactId>
  <dependencies>
 		<dependency>
			<groupId>fi.wiskopdr</groupId>
			<artifactId>wiskopdr</artifactId>
			<version>0.3.0</version>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
        	<groupId>nl.uu.fi.dwo</groupId>
    		<artifactId>DWO-commons-lib</artifactId>
        	<version>2.5.10</version>
        	<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.c-book</groupId>
			<artifactId>cbookif</artifactId>
			<version>1.0.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.c-book</groupId>
			<artifactId>cbookeditor</artifactId>
			<version>0.0.1</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>nl.numworx.swingbrowser</groupId>
			<artifactId>swingbrowser-api</artifactId>
			<version>0.0.10</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.numworx.swingbrowser</groupId>
			<artifactId>swingbrowser-jxb</artifactId>
			<version>0.0.10</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>numworxlf</artifactId>
			<version>2.5.4</version>
		</dependency>
  </dependencies>
  <build>
  	<finalName>notebook</finalName>
  </build>
 	<repositories>	
	<repository>
	  <id>com.teamdev</id>
	  <url>https://europe-maven.pkg.dev/jxbrowser/releases</url>
	</repository>
	</repositories>
</project>