<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>nl.uu.fi.dwo</groupId>
		<artifactId>dwo</artifactId>
		<version>2.5.49-SNAPSHOT</version>
		<relativePath>../DWO/pom.xml</relativePath>
	</parent>
  <groupId>nl.numworx.notebook</groupId>
  <artifactId>notebook-parent</artifactId>
  <version>2.5.49-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Notebook widget </name>
  <properties>
    <gwtVersion>2.8.2</gwtVersion>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <modules>
<!--  	<module>notebook</module>-->
  	<module>notebook-common</module>
  	<module>NotebookGWT</module>
    <module>notebook-service</module>
  </modules>
</project>
