mail.subject= Registration completion
mail.mime: text/plain
mail.body=Beste {1} {2} {3},\n\nHartelijk dank voor uw aanmelding voor het gebruik van Numworx Free.\n\n\
Gebruik onderstaande link om uw aanmelding te bevestigen en een wachtwoord te kiezen\n\
{0}\n\
Daarna kunt u via https://www.numworx.nl/inloggen-op-numworx/ gebruik maken van de Numworx Digitale Wiskunde Omgeving voor leerling of student.\n\
\n\
Veel plezier met Numworx!\n\
\n\
Hartelijke groet,\n\
\nHet Numworx team\nNumworx Solutions BV\n
next=https://www.numworx.nl/inloggen-op-numworx/
cancel=https://www.numworx.nl/
mail.demo=Beste {1} {2} {3},\n\nHartelijk dank voor uw aanmelding voor het gebruik van Numworx demo-omgeving.\n\n\
Gebruik onderstaande link om uw aanmelding te bevestigen en een wachtwoord te kiezen\n\
{0}\n\
Daarna kunt u via https://www.numworx.nl/inloggen-op-numworx/ gebruik maken van de Numworx Digitale Wiskunde Omgeving voor leerling of student.\n\
\n\
Veel plezier met Numworx!\n\
\n\
Hartelijke groet,\n\
\nHet Numworx team\nNumworx Solutions BV\n
