mail.subject= Registration completion
mail.mime: text/plain
mail.body.FREE=Beste {1} {2} {3},\n\nHartelijk dank voor uw aanmelding voor het gebruik van {4}.\n\n\
Gebruik onderstaande link om uw aanmelding te bevestigen en een wachtwoord te kiezen\n\
{0}\n\
Daarna kunt u via https://www.numworx.nl/inloggen-op-numworx/ gebruik maken van de Numworx Digitale Wiskunde Omgeving voor leerling of student.\n\
\n\
Veel plezier met Numworx!\n\
\n\
Hartelijke groet,\n\
\nHet Numworx team\nNumworx Solutions BV\n
next=https://www.numworx.nl/inloggen-op-numworx/
cancel=https://www.numworx.nl/

#demo teksten
mail.body.DEMO=\
Beste {1} {2} {3},\n\n\
Hartelijk dank voor uw aanvraag van een Numworx demo-account. Er is een schoolomgeving voor u beschikbaar, "{5}", en een docent-account dat zes weken geldig is:\n\
Met dit account kunt u eventueel ook accounts maken voor studenten/leerlingen. Handleidingen kunt u vinden op www.numworx.nl (zie http://www.numworx.nl/help/handleidingen/).\n\
Gebruik onderstaande link om uw aanmelding te bevestigen en een wachtwoord te kiezen\n\
{0}\n\
Voor inloggen in Numworx, zie https://www.numworx.nl/inloggen-op-numworx/.\n\
Voor de docent-auteursomgeving moet u Numworx Author installeren, zie https://www.numworx.nl/help/downloads/.\n\n\
Met vriendelijke groet,\n\
Numworx Solutions B.V.\n
language=nl
hetbosin=/hetbosin.html