component.alpha = Dit is een geschikt significantieniveau.
component.conclusion.p-value = Dit is de juiste conclusie over deze p-waarde.
component.critical-conclusion = Dit is de juiste conclusie over deze toetsingsgrootheid en kritiek gebied.
component.critical.r-value = Dit is de juiste kritieke r-waarde.
component.critical.t-value = Dit is de juiste kritieke t-waarde.
component.critical.z-value = Dit is de juiste kritieke z-waarde.
component.critical.f-value = Dit is de juiste kritieke F-waarde.
component.critical.chi-value = Dit is de juiste kritieke waarde.
component.df = Dit aantal vrijheidsgraden is correct.
component.df-anova = Dit aantal vrijheidsgraden is correct.
component.expected-frequencies = De tabel met verwachte frequenties is correct.
component.h0 = Dit is een geschikte nulhypothese.
component.h0-from-ha = Dit is een geschikte nulhypothese.
component.h0-from-ha-eq = Dit is een geschikte nulhypothese.
component.ha = Dit is een geschikte alternatieve hypothese.
component.hypotheses = Dit zijn geschikte hypotheses.
component.hypotheses-chi-squared = Dit zijn geschikte hypotheses.
component.hypotheses-conclusion-critical = Dit is de correcte conclusie over deze hypotheses; je hebt de toets correct uitgevoerd.
component.hypotheses-conclusion-pvalue = Dit is de correcte conclusie over deze hypotheses; je hebt de toets correct uitgevoerd.
component.mean = Dit is het juiste gemiddelde.
component.n = Dit is de juiste steekproefgrootte.
component.observed-totals = De tabel met geobserveerde frequenties is correct.
component.p-value.t-test = Dit is de juiste p-waarde bij deze toetsingsgrootheid.
component.p-value.z-test = Dit is de juiste p-waarde bij deze toetsingsgrootheid.
component.rejection.critical = Dit is het juiste kritieke gebied voor deze toets.
component.sided = Dit is de juiste toetsrichting.
component.standard-deviation = Dit is de correcte standaardafwijking.
component.standard-error-sigma = Dit is de correcte standaardfout.
component.standard-error-sd = Dit is de correcte standaardfout.
component.test.anova = Een ANOVA is hier inderdaad de meest geschikte toets.
component.test.chi-squared = Een Chi-kwadraattoets is hier inderdaad de meest geschikte toets.
component.test.r-pearson = Een Pearson correlatietoets is hier inderdaad de meest geschikte toets.
component.test.t-test = Een t-toets voor één groep is hier inderdaad de meest geschikte toets.
component.test.t-test-paired = Een t-toets voor afhankelijke groepen is hier inderdaad de meest geschikte toets.
component.test.t-test-two = Een t-toets voor onafhankelijke groepen is hier inderdaad de meest geschikte toets.
component.test.z-test = Een z-toets is hier inderdaad de meest geschikte toets.
component.test-formula = Deze formule voor de toetsingsgrootheid is correct.
component.test-value = Deze waarde van de toetsingsgrootheid is correct.
component.variance = Dit is de correcte variantie.
expr.substitute = 
noFeedback = Dit is een correcte stap
        
#        checks: state is not equivalent with previous state; checking of mentioned constraint resulted in error
check.samplemean = Je hebt niet het juiste steekproefgemiddelde ingevuld.
check.populationsdev = Je hebt niet de juiste standaardafwijking van de variabele in de populatie ingevuld. Let ook op de notatie.
check.samplesdev = Je hebt niet de juiste steekproefstandaardafwijking ingevuld. Let ook op de notatie.
check.samplesize = Je hebt niet de juiste steekproefgrootte ingevuld.
check.correlation = Je hebt niet de juiste waarde van de correlatiecoefficient ingevuld. 
check.alpha = Het significantieniveau is niet correct.
check.h0 = Deze nulhypothese past niet bij de opgestelde alternatieve hypothese of de claim uit de opdracht.
check.h0\:\ parameter\ mismatch = De nulhypothese moet gaan over parameters in de populatie, niet over eigenschappen van één specifieke steekproef. Welke parameter bekijk je?
check.h0\:\ value\ mismatch = Kijk nog eens naar de rechterkant van je nulhypothese. Welke waarde moet daar staan?
check.h0\:\ sign\ mismatch = De richting van je nulhypothese past niet bij de alternatieve hypothese.
check.h0\:\ component\ is\ not\ of\ type\ relation = Vul eerst de gehele nulhypothese in, voor je nakijkt.
check.ha = Deze alternatieve hypothese past niet bij de claim uit de opdracht.
check.ha\:\ parameter\ mismatch = De alternatieve hypothese moet gaan over parameters in de populatie, niet over eigenschappen van één specifieke steekproef. Welke parameter bekijk je?
check.ha\:\ value\ mismatch = Kijk nog eens naar de rechterkant van je alternatieve hypothese. Welke waarde moet daar staan?
check.ha\:\ sign\ mismatch = De richting van je alternatieve hypothese past niet bij de claim uit de opdracht.
check.ha\:\ component\ is\ not\ of\ type\ relation = Vul eerst de gehele alternatieve hypothese in, voor je nakijkt.
check.sided = Deze toetsrichting past niet bij de hypotheses of claim uit de opdracht.
check.sided\:\ anova = Deze toetsrichting past niet bij een ANOVA.
check.sided\:\ chi-squared = Deze toetsrichting past niet bij een Chi-kwadraattoets.
check.test = Je hebt niet de meest geschikte toets gekozen.
check.test-formula = De formule van de toetsingsgrootheid is niet correct.
check.test-formula\:\ component\ is\ not\ of\ type\ relation = Bepaal eerst beide kanten van de formule, voor je nakijkt.
check.test-formula\:\ cannot\ solve = Heb je alle variabelen in de formule gedefinieerd en gebruik je gangbare namen voor de variabelen?
check.test-formula\:\ no\ match = De formule van de toetsingsgrootheid is niet correct.
check.test-formula\:\ test\ mismatch = Welke variabelenaam hoort bij de toets die je uitvoert? Z, t of nog iets anders?
check.test-value = Dit is niet de juiste waarde van de toetsingsgrootheid.
check.test-value\:\ no\ match = Dit is niet de juiste waarde van de toetsingsgrootheid.
check.test-value\:\ test\ mismatch = Welke variabelenaam hoort bij de toets die je uitvoert? Z, t of nog iets anders?
check.test-value\:\ component\ is\ not\ of\ type\ relation = Bepaal zowel de variabelenaam als de waarde van de toetsingsgrootheid voor je nakijkt.
check.test-value\:\ almost\ equal = De waarde van de toetsingsgrootheid is niet correct, maar zit in de buurt. Heb je correct afgerond en op voldoende decimalen?
check.df = Het aantal vrijheidsgraden is niet correct.
check.df\:\ no\ match = Het aantal vrijheidsgraden is niet correct.
check.df-anova = Het aantal vrijheidsgraden is niet correct.
check.df-anova\:\ df-between = Het aantal vrijheidsgraden tussen de groepen is niet correct.
check.df-anova\:\ df-within = Het aantal vrijheidsgraden binnen de groepen is niet correct.
check.df-anova\:\ no\ match = Het aantal vrijheidsgraden is niet correct.
check.critical = Dit is niet de juiste kritieke waarde.
check.critical\:\ alternative\ hypothesis\ missing = Bij welke hypotheses hoort deze kritieke waarde? Stel eerst hypotheses op.
check.critical\:\ test\ mismatch = Welke variabelenaam hoort bij de toets die je uitvoert? Z, t of nog iets anders?
check.critical\:\ component\ is\ not\ of\ type\ relation = Geef zowel de naam als de waarde van de kritieke waarde, voor je nakijkt.
check.critical\:\ almost\ equal = De kritieke waarde is niet correct, maar zit in de buurt. Heb je correct afgerond en op voldoende decimalen?
check.rejectioncritical = Dit is niet het juiste kritieke gebied.
check.rejectioncritical\:\ test\ mismatch = Welke variabelenaam hoort bij de toets die je uitvoert? Z, t of nog iets anders?
check.rejectioncritical\:\ sidedness\ mismatch = Past het teken dat je in het kritiek gebied gebruikt bij de richting van de alternatieve hypothese?
check.rejectioncritical\:\ anova\ mismatch = Past het teken dat je in het kritiek gebied gebruikt bij de toets die je aan het doen bent?
check.rejectioncritical\:\ chi-squared\ mismatch = Past het teken dat je in het kritiek gebied gebruikt bij de toets die je aan het doen bent?
check.rejectioncritical\:\ alternative\ hypothesis\ missing = Bij welke hypotheses hoort dit kritieke gebied? Stel eerst hypotheses op.
check.rejectioncritical\:\ component\ is\ not\ of\ type\ relation = Bepaal eerst het gehele kritieke gebied, voor je nakijkt.
check.p-value = Dit is niet de juiste p-waarde bij de toetsingsgrootheid.
check.p-value\:\ TestValue\ missing = Om een p-waarde te bepalen, moet je eerst de toetsingsgrootheid berekenen.
check.p-value\:\ alternative\ hypothesis\ missing = Bij welke hypotheses hoort deze p-waarde? Stel eerst hypotheses op.
check.p-value\:\ component\ is\ not\ of\ type\ relation = Er is iets fout gegaan met de p-waarde. Vul deze nogmaals in.
check.p-value\:\ value\ not\ a\ probability = De p-waarde is de overschrijdingskans. Heb je inderdaad een kans (een getal tussen 0 en 1) bepaald?
check.p-value\:\ almost\ equal = De p-waarde is niet correct, maar zit in de buurt. Heb je correct afgerond en op voldoende decimalen?
check.conclusion.p-value = Je bewering over de p-waarde en het significantieniveau klopt niet.
check.conclusion.p-value\:\ PValue\ missing = Geef eerst een schatting van de p-waarde zelf, voordat je deze vergelijkt met het significantieniveau.
check.conclusion-critical = Je bewering over de toetsingsgrootheid en het kritieke gebied klopt niet.
check.conclusion-critical\:\ RejectionCritical\ missing = Wat is het kritieke gebied? Voordat je dit hebt bepaald is het te vroeg om deze conclusie te trekken.
check.conclusion-critical\:\ no\ match = Wat zijn de kritieke waarde en de waarde van de toetsingsgrootheid? Bepaal ze eerst, voordat je ze probeert te vergelijken.
check.conclusion-hypotheses = Waar baseer je deze conclusie op? Kun je eerst iets zeggen over het kritieke gebied, of over de p-waarde die bij de toetsingsgrootheid hoort?
check.conclusion-hypotheses\:\ conclusion\ mismatch\ critical = Deze conclusie past niet bij de toetsingsgrootheid en het kritieke gebied. Ligt de toetsingsgrootheid in het kritieke gebied of niet?
check.conclusion-hypotheses\:\ conclusion\ mismatch\ pvalue = Deze conclusie past niet bij de p-waarde die je hebt gevonden en bij het significantieniveau. Is de p-waarde groter of kleiner dan het significantieniveau?
check.conclusion-hypotheses\:\ convention\ DontRejectH0 = Met een hypothesetoets kun je uiteindelijk een uitspraak doen over het al dan niet verwerpen van de nulhypothese. We accepteren hypotheses nooit, maar doen wel altijd een uitspraak over $fH$s0@.@ 
check.conclusion-hypotheses\:\ convention\ RejectH0 = Met een hypothesetoets kun je uiteindelijk een uitspraak doen over de nulhypothese, niet over de alternatieve hypothese.
check.standard-error = Dit is niet de juiste waarde van de standaardfout.
check.standard-error\:\ component\ is\ not\ of\ type\ relation = Geef zowel de variabelenaam als de waarde van de standaardfout, voor je nakijkt.
check.standard-error\:\ standard\ error\ mismatch = Kun je de standaardafwijking uit de populatie gebruiken, of moet je die schatten met behulp van de steekproef? En welke notatie hoort hierbij?
check.standard-error\:\ almost\ equal = De standaardfout is niet correct, maar zit in de buurt. Heb je correct afgerond en op voldoende decimalen?
check.groups = Dit is niet het juiste aantal groepen.
check.observed-totals\:\ rows = De totalen van de geobserveerde frequenties kloppen niet allemaal.
check.observed-totals\:\ columns = De totalen van de geobserveerde frequenties kloppen niet allemaal.
check.observed-totals:\:\ total = De totalen van de geobserveerde frequenties kloppen niet allemaal.
check.expected-frequencies = De verwachte frequenties kloppen niet allemaal.
        
#Buggy: state is not equivalent to previous state; mentioned buggy rule detected
buggy.component.alpha = Je hebt niet het gevraagde significantieniveau gebruikt.
buggy.component.df = Het aantal vrijheidsgraden dat je gebruikt is niet correct.
buggy.component.h0-samplemean = De nulhypothese moet gaan over parameters in de populatie, niet over eigenschappen van één specifieke steekproef.
buggy.component.ha-samplemean = De alternative hypothese moet gaan over parameters in de populatie, niet over eigenschappen van één specifieke steekproef.
buggy.component.hypotheses-samplemean = De hypotheses moeten gaan over parameters in de populatie, niet over eigenschappen van één specifieke steekproef.
buggy.component.t-test-one-sample.should-be-t-test-paired = Een t-toets voor één groep is geschikt als je maar één steekproef hebt.
buggy.component.t-test-one-sample.should-be-t-test-two-sample = Een t-toets voor één groep is geschikt als je maar één steekproef hebt.
buggy.component.t-test-one-sample.should-be-z-test = Een t-toets voor één groep is geschikt bij kleine steekproefgroottes, wanneer de standaardafwijking van de populatie niet bekend is.
buggy.component.t-test-paired.should-be-t-test-one-sample = Een t-toets voor afhankelijke groepen is geschikt als je twee afhankelijke steekproeven hebt.
buggy.component.t-test-paired.should-be-t-test-two-sample = Een t-toets voor afhankelijke groepen is geschikt als de objecten in de twee steekproeven te koppelen zijn.
buggy.component.t-test-paired.should-be-z-test = Een t-toets voor afhankelijke groepen is geschikt als je twee afhankelijke steekproeven hebt.
buggy.component.t-test-two-sample.should-be-t-test-one-sample = Een t-toets voor onafhankelijke groepen is geschikt als je twee steekproeven hebt.
buggy.component.t-test-two-sample.should-be-t-test-paired = Een t-toets voor onafhankelijke groepen is geschikt als de objecten in de twee steekproeven niet te koppelen zijn.
buggy.component.t-test-two-sample.should-be-z-test = Een t-toets voor onafhankelijke groepen is geschikt als je twee steekproeven hebt.
buggy.component.z-test.should-be-t-test-one-sample = Een z-toets is geschikt bij grote steekproeven, of wanneer de standaardafwijking van de populatie bekend is.
buggy.component.z-test.should-be-t-test-paired = Een z-toets is geschikt als je maar één steekproef hebt.
buggy.component.z-test.should-be-t-test-two-sample = Een z-toets is geschikt als je maar één steekproef hebt.
buggy.component.test-z-value = Waar heb je door gedeeld om deze toetsingsgrootheid te berekenen? De standaardafwijking of de standaardfout?
buggy.component.test-t-value = Waar heb je door gedeeld om deze toetsingsgrootheid te berekenen? De standaardafwijking of de standaardfout?
buggy.component.critical.chi-value.alpha = Bij welk significantieniveau heb je de kritieke waarde opgezocht?
buggy.component.critical.chi-value.df = Bij welk aantal vrijheidsgraden heb je de kritieke waarde opgezocht?
buggy.component.critical.chi-value.sided = In welke staart(en) van de verdeling ligt het kritieke gebied bij een Chi-kwadraattoets? Links, rechts, of allebei?
buggy.component.critical.chi-value.test-value = Wat is precies de kritieke waarde en wat is de toetsingsgrootheid?
buggy.component.critical.f-value.alpha = Bij welk significantieniveau heb je de kritieke waarde opgezocht?
buggy.component.critical.f-value.df = Bij welk aantal vrijheidsgraden heb je de kritieke waarde opgezocht?
buggy.component.critical.f-value.test-value = Wat is precies de kritieke waarde en wat is de toetsingsgrootheid?
buggy.component.critical.r-value.alpha = Bij welk significantieniveau heb je de kritieke waarde opgezocht?
buggy.component.critical.r-value.df = Bij welk aantal vrijheidsgraden heb je de kritieke waarde opgezocht?
buggy.component.critical.r-value.sided = In welke staart(en) van de verdeling ligt het kritieke gebied in dit geval? Links, rechts, of allebei?
buggy.component.critical.r-value.test-value = Wat is precies de kritieke waarde en wat is de toetsingsgrootheid?
buggy.component.critical.t-value.alpha = Bij welk significantieniveau heb je de kritieke waarde opgezocht?
buggy.component.critical.t-value.df = Bij welk aantal vrijheidsgraden heb je de kritieke waarde opgezocht?
buggy.component.critical.t-value.sided = In welke staart(en) van de verdeling ligt het kritieke gebied in dit geval? Links, rechts, of allebei?
buggy.component.critical.t-value.test-value = Wat is precies de kritieke waarde en wat is de toetsingsgrootheid?
buggy.component.critical.z-value.alpha = Bij welk significantieniveau heb je de kritieke waarde opgezocht?
buggy.component.critical.z-value.sided = In welke staart(en) van de verdeling ligt het kritieke gebied in dit geval? Links, rechts, of allebei?
buggy.component.critical.z-value.test-value = Wat is precies de kritieke waarde en wat is de toetsingsgrootheid?
buggy.component.test-value.critical = Wat is precies de toetsingsgrootheid en wat is de kritieke waarde?