component.alpha = Dit is een geschikt significantieniveau.
component.conclusion.p-value = Dit is de juiste conclusie over deze p-waarde.
component.critical-conclusion = Dit is de juiste conclusie over deze toetsingsgrootheid en kritiek gebied.
component.critical.t-value = Dit is de juiste kritieke t-waarde.
component.critical.z-value = Dit is de juiste kritieke z-waarde.
component.df = Dit aantal vrijheidsgraden is correct.
component.h0 = Dit is een geschikte nulhypothese.
component.h0-from-ha = Dit is een geschikte nulhypothese.
component.h0-from-ha-eq = Dit is een geschikte nulhypothese.
component.ha = Dit is een geschikte alternatieve hypothese.
component.hypotheses = Dit zijn geschikte hypotheses.
component.hypotheses-conclusion-critical = Dit is de correcte conclusie over deze hypotheses; je hebt de toets correct uitgevoerd.
component.hypotheses-conclusion-pvalue = Dit is de correcte conclusie over deze hypotheses; je hebt de toets correct uitgevoerd.
component.mean = Dit is het juiste gemiddelde.
component.n = Dit is de juiste steekproefgrootte.
component.p-value.t-test = Dit is de juiste p-waarde bij deze toetsingsgrootheid.
component.p-value.z-test = Dit is de juiste p-waarde bij deze toetsingsgrootheid.
component.rejection.critical = Dit is het juiste kritieke gebied voor deze toets.
component.sided = Dit is de juiste toetsrichting.
component.standard-deviation = Dit is de correcte standaardafwijking.
component.standard-error-sigma = Dit is de correcte standaardfout.
component.standard-error-sd = Dit is de correcte standaardfout.
component.test-formula = Deze formule voor de toetsingsgrootheid is correct.
component.test-value = Deze waarde van de toetsingsgrootheid is correct.
component.test.t-test = Een t-toets voor één groep is hier inderdaad de meest geschikte toets.
component.test.t-test-paired = Een t-toets voor afhankelijke groepen is hier inderdaad de meest geschikte toets.
component.test.t-test-two = Een t-toets voor onafhankelijke groepen is hier inderdaad de meest geschikte toets.
component.test.z-test = Een z-toets is hier inderdaad de meest geschikte toets.
component.variance = Dit is de correcte variantie.
expr.substitute = 
noFeedback = Dit is een correcte stap
        
#        checks: state is not equivalent with previous state; checking of mentioned constraint resulted in error
check.samplemean = Je hebt niet het juiste steekproefgemiddelde ingevuld.
check.populationsdev = Je hebt niet de juiste standaardafwijking van de variabele in de populatie ingevuld. Let ook op de notatie.
check.samplesdev = Je hebt niet de juiste steekproefstandaardafwijking ingevuld. Let ook op de notatie.
check.samplesize = Je hebt niet de juist steekproefgrootte ingevuld.
check.alpha = Het significantieniveau is niet correct.
check.h0 = Deze nulhypothese past niet bij de opgestelde alternatieve hypothese of de claim uit de opdracht.
check.h0\:\ parameter\ mismatch = De nulhypothese moet gaan over parameters in de populatie, niet over eigenschappen van één specifieke steekproef.
check.h0\:\ value\ mismatch = Kijk nog eens naar de rechterkant van je nulhypothese. Welke waarde moet daar staan?
check.h0\:\ sign\ mismatch = De richting van je nulhypothese past niet bij de alternatieve hypothese.
check.h0\:\ component\ is\ not\ of\ type\ relation = Vul eerst de gehele nulhypothese in, voor je nakijkt.
check.ha = Deze alternatieve hypothese past niet bij de claim uit de opdracht.
check.ha\:\ parameter\ mismatch = De alternatieve hypothese moet gaan over parameters in de populatie, niet over eigenschappen van één specifieke steekproef.
check.ha\:\ value\ mismatch = Kijk nog eens naar de rechterkant van je alternatieve hypothese. Welke waarde moet daar staan?
check.ha\:\ sign\ mismatch = De richting van je alternatieve hypothese past niet bij de claim uit de opdracht.
check.ha\:\ component\ is\ not\ of\ type\ relation = Vul eerst de gehele alternatieve hypothese in, voor je nakijkt.
check.sided = Deze toetsrichting past niet bij de hypotheses of claim uit de opdracht.
check.test = Je hebt niet de meest geschikte toets gekozen.
check.test-formula = De formule van de toetsingsgrootheid is niet correct.
check.test-formula\:\ component\ is\ not\ of\ type\ relation = Bepaal eerst beide kanten van de formule, voor je nakijkt.
#        feedbackMap.put("check.test-formula: TestChoice missing = Wat voor toets ga je uitvoeren? Specificeer dit eerst, voordat je de toetsingsgrootheid gaat bepalen.
check.test-formula\:\ cannot\ solve = Heb je alle variabelen in de formule gedefinieerd en gebruik je gangbare namen voor de variabelen?
check.test-formula\:\ no\ match = De formule van de toetsingsgrootheid is niet correct.
check.test-formula\:\ test\ mismatch = Bepaal je een t-waarde of een z-waarde?
check.test-value = Dit is niet de juiste waarde van de toetsingsgrootheid.
check.test-value\:\ no\ match = Dit is niet de juiste waarde van de toetsingsgrootheid.
check.test-value\:\ test\ mismatch = Bereken je een t-waarde of een z-waarde?
check.test-value\:\ component\ is\ not\ of\ type\ relation = Bepaal zowel de variabelenaam als de waarde van de toetsingsgrootheid voor je nakijkt.
check.df = Het aantal vrijheidsgraden is niet correct.
#        feedbackMap.put("check.df: TestChoice missing = Wat voor toets ga je uitvoeren? Specificeer dit eerst, voordat je het aantal vrijheidsgraden bepaalt.
check.critical = Dit is niet de juiste kritieke waarde.
check.critical\:\ alternative\ hypothesis\ missing = Bij welke hypotheses hoort deze kritieke waarde? Stel eerst hypotheses op.
#        feedbackMap.put("check.critical: TestChoice missing = Wat voor toets ga je uitvoeren? Specificeer dit eerst, voordat je de kritieke waarde gaat bepalen.
#        feedbackMap.put("check.critical: SignificanceLevel missing = Voor welk significantieniveau bepaal je de kritieke waarde? Geef eerst het significantieniveau.
#        feedbackMap.put("check.critical: df missing = Voor welk aantal vrijheidsgraden bepaal je de kritieke waarde? Geef eerst het aantal vrijheidsgraden.
check.critical\:\ test\ mismatch = Bepaal je een kritieke t-waarde of een kritieke z-waarde?
check.critical\:\ component\ is\ not\ of\ type\ relation = Geef zowel de naam als de waarde van de kritieke waarde, voor je nakijkt.
check.rejectioncritical = Dit is niet het juiste kritieke gebied.
check.rejectioncritical\:\ test\ mismatch = Bepaal je een kritiek gebied voor een t-waarde of voor een z-waarde?
check.rejectioncritical\:\ sidedness\ mismatch = Past het teken dat je in het kritiek gebied gebruikt bij de richting van de alternatieve hypothese?
check.rejectioncritical\:\ alternative\ hypothesis\ missing = Bij welke hypotheses hoort dit kritieke gebied? Stel eerst hypotheses op.
check.rejectioncritical\:\ component\ is\ not\ of\ type\ relation = Bepaal eerst het gehele kritieke gebied, voor je nakijkt.
check.p-value = Dit is niet de juiste p-waarde bij de toetsingsgrootheid.
check.p-value\:\ TestValue\ missing = Om een p-waarde te bepalen, moet je eerst de toetsingsgrootheid berekenen.
#        feedbackMap.put("check.p-value: Df missing = Voor het bepalen van de p-waarde bij een t-toets, heb je het aantal vrijheidsgraden nodig. Geef eerst het aantal vrijheidsgraden.
check.p-value\:\ alternative\ hypothesis\ missing = Bij welke hypotheses hoort deze p-waarde? Stel eerst hypotheses op.
check.p-value\:\ component\ is\ not\ of\ type\ relation = Er is iets fout gegaan met de p-waarde. Vul deze nogmaals in.# TODO: kijken wat hier goede feedbacktekst is. 
check.p-value\:\ value\ not\ a\ probability = De p-waarde is de overschrijdingskans. Heb je inderdaad een kans (een getal tussen 0 en 1) bepaald?
check.conclusion.p-value = Je bewering over de p-waarde en het significantieniveau klopt niet.
check.conclusion.p-value\:\ PValue\ missing = Geef eerst een schatting van de p-waarde zelf, voordat je deze vergelijkt met het significantieniveau.
#feedbackMap.put("check.conclusion.p-value: SignificanceLevel missing = Met welk significantieniveau vergelijk je de p-waarde? Geef eerst het significantieniveau.
check.conclusion-critical = Je bewering over de toetsingsgrootheid en het kritieke gebied klopt niet.
check.conclusion-critical\:\ RejectionCritical\ missing = Wat is het kritieke gebied? Voordat je dit hebt bepaald is het te vroeg om deze conclusie te trekken.
check.conclusion-critical\:\ no\ match = Wat zijn de kritieke waarde en de waarde van de toetsingsgrootheid? Bepaal ze eerst, voordat je ze probeert te vergelijken.
check.conclusion-hypotheses = Waar baseer je deze conclusie op? Kun je eerst iets zeggen over het kritieke gebied, of over de p-waarde die bij de toetsingsgrootheid hoort?
check.conclusion-hypotheses\:\ conclusion\ mismatch\ critical = Deze conclusie past niet bij je conclusie over of de toetsingsgrootheid wel of niet in het kritieke gebied ligt.
check.conclusion-hypotheses\:\ conclusion\ mismatch\ pvalue = Deze conclusie past niet bij je conclusie over of de p-waarde groter of kleiner is dan het significantieniveau.
check.standard-error = Dit is niet de juiste waarde van de standaardfout.
check.standard-error\:\ component\ is\ not\ of\ type\ relation = Geef zowel de variabelenaam als de waarde van de standaardfout, voor je nakijkt.
check.standard-error\:\ standard\ error\ mismatch = Kun je de standaardafwijking uit de populatie gebruiken, of moet je die schatten met behulp van de steekproef? En welke notatie hoort hierbij?
        
#Buggy: state is not equivalent to previous state; mentioned buggy rule detected
buggy.component.alpha = Je hebt niet het gevraagde significantieniveau gebruikt.
buggy.component.df = Het aantal vrijheidsgraden dat je gebruikt is niet correct.
buggy.component.h0 = De nulhypothese moet gaan over parameters in de populatie, niet over eigenschappen van één specifieke steekproef.
buggy.component.ha = Deze alternatieve hypothese past niet bij de claim uit de opdracht.
buggy.component.t-test-one-sample.should-be-t-test-paired = Een t-toets voor één groep is geschikt als je maar één steekproef hebt.
buggy.component.t-test-one-sample.should-be-t-test-two-sample = Een t-toets voor één groep is geschikt als je maar één steekproef hebt.
buggy.component.t-test-one-sample.should-be-z-test = Een t-toets voor één groep is geschikt bij kleine steekproefgroottes, wanneer de standaardafwijking van de populatie niet bekend is.
buggy.component.t-test-paired.should-be-t-test-one-sample = Een t-toets voor afhankelijke groepen is geschikt als je twee afhankelijke steekproeven hebt.
buggy.component.t-test-paired.should-be-t-test-two-sample = Een t-toets voor afhankelijke groepen is geschikt als de objecten in de twee steekproeven te koppelen zijn.
buggy.component.t-test-paired.should-be-z-test = Een t-toets voor afhankelijke groepen is geschikt als je twee afhankelijke steekproeven hebt.
buggy.component.t-test-two-sample.should-be-t-test-one-sample = Een t-toets voor onafhankelijke groepen is geschikt als je twee steekproeven hebt.
buggy.component.t-test-two-sample.should-be-t-test-paired = Een t-toets voor onafhankelijke groepen is geschikt als de objecten in de twee steekproeven niet te koppelen zijn.
buggy.component.t-test-two-sample.should-be-z-test = Een t-toets voor onafhankelijke groepen is geschikt als je twee steekproeven hebt.
buggy.component.z-test.should-be-t-test-one-sample = Een z-toets is geschikt bij grote steekproeven, of wanneer de standaardafwijking van de populatie bekend is.
buggy.component.z-test.should-be-t-test-paired = Een z-toets is geschikt als je maar één steekproef hebt.
buggy.component.z-test.should-be-t-test-two-sample = Een z-toets is geschikt als je maar één steekproef hebt.
buggy.component.test-z-value = Waar heb je door gedeeld om deze toetsingsgrootheid te berekenen? De standaardafwijking of de standaardfout?
buggy.component.test-t-value = Waar heb je door gedeeld om deze toetsingsgrootheid te berekenen? De standaardafwijking of de standaardfout?
buggy.component.critical.t-value-positive = In welke staart(en) van de verdeling ligt het kritieke gebied in dit geval? Links, rechts, of allebei?
buggy.component.critical.z-value-positive = In welke staart(en) van de verdeling ligt het kritieke gebied in dit geval? Links, rechts, of allebei?
buggy.component.accepth0.should-be-dontrejecth0 = In een hypothesetoets accepteren we hypotheses nooit. Als de data niet genoeg aanleiding geven om $fH$s0@@ te verwerpen, dan zeggen we dat we $fH$s0@@ niet verwerpen.
buggy.component.accepth0.should-be-rejecth0 = In een hypothesetoets accepteren we hypotheses nooit. Maar geven de data inderdaad aanleiding om te denken dat $fH$s0@@ waar is?
buggy.component.rejecth1.should-be-dontrejecth0 = Met een hypothesetoets kun je uiteindelijk een uitspraak doen over de nulhypothese, niet over de alternatieve hypothese.
buggy.component.rejecth1.should-be-rejecth0 = Met een hypothesetoets kun je uiteindelijk een uitspraak doen over de nulhypothese, niet over de alternatieve hypothese.
buggy.component.accepth1.should-be-dontrejecth0 = Met een hypothesetoets kun je uiteindelijk een uitspraak doen over de nulhypothese, niet over de alternatieve hypothese.
buggy.component.accepth1.should-be-rejecth0 = Met een hypothesetoets kun je uiteindelijk een uitspraak doen over de nulhypothese, niet over de alternatieve hypothese.
buggy.component.dontrejecth1.should-be-dontrejecth0 = Met een hypothesetoets kun je uiteindelijk een uitspraak doen over de nulhypothese, niet over de alternatieve hypothese.
buggy.component.dontrejecth1.should-be-rejecth0 = Met een hypothesetoets kun je uiteindelijk een uitspraak doen over de nulhypothese, niet over de alternatieve hypothese.
buggy.component.rejecth0.should-be-dontrejecth0 = Geven de data inderdaad voldoende bewijs om aan te denken dat $fH$s0@@ niet waar is?
buggy.component.dontrejecth0.should-be-rejecth0 = Geven de data inderdaad voldoende bewijs om te denken dat $fH$s0@@ waar is?
