exception = Er is iets fout gegaan.
component.test.t-test = Bepaal welke toets geschikt is voor deze situatie.
component.alpha = Definiëer het significantieniveau waarmee je de toets gaat uitvoeren.
component.conclusion.p-value = Trek een conclusie op basis van de gevonden p-waarde.
component.critical-conclusion = Trek een conclusie op basis van de gevonden toetsingsgrootheid en het kritieke gebied.
component.critical.t-value = Bepaal de kritieke waarde(n) voor deze toets.
component.critical.z-value = Bepaal de kritieke waarde(n) voor deze toets.
component.df = Bepaal het aantal vrijheidsgraden in deze toets.
component.h0 = Geef aan welke nulhypothese je wil toetsen.
component.h0-from-ha = Geef aan welke nulhypothese je wil toetsen.
component.h0-from-ha-eq = Geef aan welke nulhypothese je wil toetsen.
component.ha = Geef aan welke alternatieve hypothese je wil toetsen.
component.hypotheses = Bepaal hypotheses om te toetsen.
component.hypotheses-conclusion = Trek een conclusie over je hypotheses.
component.hypotheses-conclusion-critical = Trek een conclusie over je hypotheses.
component.hypotheses-conclusion-pvalue = Trek een conclusie over je hypotheses.
component.mean =  //-- sample or population?
component.n = Bepaal de steekproefgrootte.
component.p-value.t-test = Bepaal de p-waarde die hoort bij de gevonden toetsingsgrootheid.
component.p-value.z-test = Bepaal de p-waarde die hoort bij de gevonden toetsingsgrootheid.
component.rejection.critical = Bepaal het verwerpingsgebied dat past bij je hypotheses.
component.sided = Bepaal de toetsrichting die past bij de opdracht of je hypotheses.
component.standard-deviation =  //-- sample or population?
component.standard-error =  //-- sample or population?
component.standard-error-sigma = Bepaal de standaardfout. //-- sample or population?
component.standard-error-sd = Bepaal de standaardfout. //-- sample or population?
component.test-formula = Bepaal de formule voor de toetsingsgrootheid.
component.test-value = Bereken de toetsingsgrootheid bij de gekozen toets.
component.test.t-test = Bepaal welke toets geschikt is voor deze situatie.
component.test.t-test-paired = Bepaal welke toets geschikt is voor deze situatie.
component.test.t-test-two = Bepaal welke toets geschikt is voor deze situatie.
component.test.z-test = Bepaal welke toets geschikt is voor deze situatie.
component.variance =  //-- sample or population?
