OptionPane.yesButtonText: Ja
OptionPane.noButtonText: Nee
OptionPane.cancelButtonText: Annuleer
OptionPane.okButtonText: OK
OptionPane.titleText: Bevestiging
OptionPane.inputDialogTitle: Voer in
OptionPane.messageDialogTitle: Bericht
