<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>nl.numworx.uploadwidget</groupId>
    <artifactId>uploadwidget-parent</artifactId>
    <version>2.5.49-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>uploadwidgetgwt</artifactId>
  <packaging>war</packaging>
  <name>UploadWidget GWT</name>
  <description>Upload Widget GWT project</description>
  <properties>
    <!-- Convenience property to set the GWT version. NIET UPGRADEN NAAR 2.10.0, Geeft CORS errors
    DAN EERST CROSS-ORIGIN HEADERS TOEVOEGEN.
     -->
    <gwt.version>2.10.0</gwt.version>

    <!-- GWT 2.8 requires 1.8 -->
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <gwt.style>PRETTY</gwt.style>
    <dbrest.url>http://localhost:80/dwo/</dbrest.url>
    <maven.test.skip>true</maven.test.skip>
    <restyVersion>2.2.0</restyVersion>

  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.gwt</groupId>
        <artifactId>gwt</artifactId>
        <version>${gwt.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
     <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-user</artifactId>
      <scope>provided</scope>
    </dependency>
        <dependency>
            <groupId>org.fusesource.restygwt</groupId>
            <artifactId>restygwt</artifactId>
            <version>${restyVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.fusesource.restygwt</groupId>
            <artifactId>restygwt</artifactId>
            <version>${restyVersion}</version>
            <classifier>sources</classifier>
        </dependency>
  	<dependency>
  		<groupId>nl.numworx.uploadwidget</groupId>
  		<artifactId>uploadwidget-s3</artifactId>
  	</dependency>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-dev</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
    	<groupId>${project.groupId}</groupId>
    	<artifactId>uploadwidget-common</artifactId>
    </dependency>
    <dependency>
    	<groupId>${project.groupId}</groupId>
    	<artifactId>uploadwidget-common</artifactId>
    	<classifier>sources</classifier>
	    <scope>provided</scope>
    </dependency>
    <dependency>
	    	<groupId>nl.uu.fi.dwo.mobile</groupId>
	    	<artifactId>interaction</artifactId>
	    	<scope>provided</scope>
    </dependency>
    <dependency>
	    	<groupId>nl.uu.fi.dwo.mobile</groupId>
	    	<artifactId>interaction</artifactId>
	    	<scope>provided</scope>
	    	<classifier>sources</classifier>
    </dependency>
		<dependency>
		    <groupId>com.googlecode.gwtupload</groupId>
		    <artifactId>gwtupload</artifactId>
		    <version>1.0.3</version>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.rest</groupId>
			<artifactId>dwo-jclient-lib</artifactId>
		</dependency>

<dependency> 
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-jdk14</artifactId>
  <version>1.7.28</version>
  <scope>test</scope>
</dependency>
<dependency> 
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-api</artifactId>
  <version>1.7.28</version>
  <scope>test</scope>
</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo</groupId>
  		<artifactId>dwo-commons-lib</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo.rest</groupId>
  		<artifactId>dwo-rest-lib</artifactId>
  		<scope>provided</scope>
  		<classifier>sources</classifier>
  	</dependency>
 
  </dependencies>

  <build>
    <finalName>${project.artifactId}</finalName>
    <!-- Output classes directly into the webapp, so that IDEs and "mvn process-classes" update them in DevMode -->
    <outputDirectory>${project.build.directory}/${project.build.finalName}/WEB-INF/classes</outputDirectory>

    <plugins>

      <!-- Mojo's Maven Plugin for GWT -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <version>${gwt.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>test</goal>
              <goal>generateAsync</goal>
            </goals>
          </execution>
        </executions>
        <!-- Plugin configuration. There are many available options, see 
          gwt-maven-plugin documentation at codehaus.org -->
        <configuration>
          <runTarget>UploadWidgetGWT.html</runTarget>
          <modules>
            <module>nl.numworx.uploadwidgetgwt.UploadWidgetGWT</module>
          </modules>
          <localWorkers>1</localWorkers>
        </configuration>
      </plugin>
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<attachClasses>true</attachClasses>
                    <filteringDeploymentDescriptors>true</filteringDeploymentDescriptors>
        			<packagingIncludes>*.css,*GWT/**,WEB-INF/**</packagingIncludes>
        			<packagingExcludes>*.html</packagingExcludes>
				</configuration>
			</plugin>
    </plugins>
  </build>
	<profiles>	 	
	 	<profile>
	 		<id>local</id>
	 		<properties>
    			<dbrest.url>http://localhost:8080/dwo/</dbrest.url> 		
	 		</properties>
	 	</profile>
	</profiles>

</project>
