#all default!
# zie ook build.xml

####(2) class name waarmee het programma wordt gestart
# default is is deze fi.${packagename}.${ant.project.name}
main-class: nl.uu.fi.dwo.interaction.Interaction


####(3) USED_JARS: namen van jars in de CODEBASE die nodig zijn bij compilatie of '' (niks)
#USED_JARS: dbi.jar


####(4) Dos drive letter, is N: op het Fi, wordt toegevoegd aan alle
#       absolute padnamen /home/.....
#	        Bij thuisgebruik veranderen in bijv. C:
#	        + zorgen voor de benodigde C:\home\... structuur
#dosdrive: N:


####(5) voeg uit de CODEBASE gebruikte class (+evt resource) files toe aan de jar.
# Uncomment bijvoorbeeld:
#include.jar= fi/beans/scorm/*.class


####(6) voeg desgewenst benodigde jars toe aan packagename.jar
# Uncomment:
#extra.jar=


####(7) bij de task .exe maken kun je kiezen voor een .exe met of zonder Java Console
# Uncommment de volgende regel voor een .exe zonder java console
#java.console=/w


####(8) applicatie argumenten voor targets test, testjar, testexe
args:


####(9) gebruik de interface fi.packagename.VERSION voor versiegegevens.
# Uncomment de volgende regel daarvoor.
#use.version=yes
#compile=yes
source-level=1.5
target-level=1.5
classes=war/WEB-INF/classes
####(10) installeer de scorm package "packagename.zip"  in .../javaclasses/scorm
#use.scorm=yes

####(11) scorm codebase
#uncomment voor Peter Boon's variant van scorm.zip's
#packagename.jar bevindt zich dan in de remote 'jars' subdir.
#scorm.codebase= http://www.fisme.uu.nl/javaclasses/

####(12) installeer en gebruik de obfuscated jar.
#use.obfuscate=yes

####(13) welke packages moeten NIET geobfuscate worden.
#yguard en jshrink hebben verschillende syntax. TODO
#dont.obfuscate=fi.*
#dont.obfuscate=fi?