<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.parentgwt</groupId>
    <artifactId>ParentGWT</artifactId>
    <version>0.0.1</version>
    <relativePath>../ParentGWT</relativePath>
  </parent>
  <groupId>fi.writemathgwt</groupId>
  <artifactId>WriteMathGWT-matcherUpdate</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>WriteMath</name>
  <dependencies>
  	<dependency>
  		<groupId>com.google.gwt</groupId>
  		<artifactId>gwt-user</artifactId>
  	</dependency>
  	  	<dependency>
  		<groupId>com.googlecode.mgwt</groupId>
  		<artifactId>MGWT</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo.mobile</groupId>
  		<artifactId>interaction</artifactId>
  	</dependency>
	<dependency>
		<groupId>fi.beans</groupId>
		<artifactId>lineairealgebra</artifactId>
		<version>0.0.1-SNAPSHOT</version>			
	</dependency>
  	<dependency>
		<groupId>nl.uu.fi.dwo.writemath</groupId>
		<artifactId>engine</artifactId>
		<version>1.10-SNAPSHOT</version>
  	</dependency>
  	
  </dependencies>
  <build>
  	<finalName>writemath</finalName>
  	<resources>
  		<resource>
  			<directory>src</directory>
  		</resource>
  	</resources>
  	<sourceDirectory>src</sourceDirectory>
  </build>
  <description>Recognize handwritten mathematics.</description>
</project>