<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>fi.servlet</groupId>
    <artifactId>DWOmAccess</artifactId>
    <version>0.0.7-SNAPSHOT</version>
    <packaging>war</packaging>
    <name>DWOmAccess</name>
    <description>HTML5 access to dwo-server</description>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.6</maven.compiler.source>
        <maven.compiler.target>1.6</maven.compiler.target>
        <dsaccess>/dwo/xmlrpc</dsaccess>
        <dsaccess.url>http://127.0.0.1/dwo/xmlrpc</dsaccess.url>
        <dsrest.url>http://127.0.0.1/dwo/rest/</dsrest.url>
        <ideas>/ideas/IdeasServlet</ideas>
        <comment>amazon, *.dwo.nl</comment>
        <maven.javadoc.failOnError>false</maven.javadoc.failOnError>
    </properties>
    <dependencies>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>servlet-api</artifactId>
            <version>2.4</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>jsp-api</artifactId>
            <version>2.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>fi.dwo.client</groupId>
            <artifactId>dwo-client</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/WebContent/WEB-INF/lib/dwo.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>fi.beans</groupId>
            <artifactId>javaclasses</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/WebContent/WEB-INF/lib/javaclasses.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>net.oauth.core</groupId>
            <artifactId>oauth</artifactId>
            <version>20100601</version>
        </dependency>
        <dependency>
            <groupId>net.oauth.core</groupId>
            <artifactId>oauth-provider</artifactId>
            <version>20100601</version>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.jamonapi</groupId>
            <artifactId>jamon</artifactId>
            <version>2.80</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>aelfred</groupId>
            <artifactId>aelfred</artifactId>
            <version>1.2</version>
            <scope>runtime</scope>
        </dependency>	
    </dependencies>
    <build>
        <sourceDirectory>src</sourceDirectory>
        <testSourceDirectory>test</testSourceDirectory>
        <plugins>
<!--            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.10</version>
                <executions>
                    <execution>
                        <id>copy</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                                <artifactItem>
                                  <groupId>org.c-book</groupId>
                                                  <artifactId>CBookInstance</artifactId>
                                                  <version>0.0.1-SNAPSHOT</version>
                                                  <classifier>jar-with-dependencies</classifier>
                                  <outputDirectory>${project.build.directory}/${project.build.finalName}/lti</outputDirectory>
                                  <destFileName>cbookinstance.jar</destFileName>
                                </artifactItem>
                            </artifactItems>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>true</overWriteSnapshots>
                        </configuration>
                    </execution>
                </executions>
            </plugin>-->
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <version>2.1.1</version>
                <configuration>
                    <warSourceDirectory>WebContent</warSourceDirectory>
                    <filteringDeploymentDescriptors>true</filteringDeploymentDescriptors>
                    <archive> <!-- add the manifest to the war -->
                        <manifestFile>WebContent/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                    <attachClasses>true</attachClasses>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
            </plugin>
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>9.3.7.v20160115</version>
                <configuration>
                    <webAppSourceDirectory>WebContent</webAppSourceDirectory>
                    <webApp>
                        <contextPath>/DWOmAccess</contextPath>
                        <descriptor>target/${project.build.finalName}/WEB-INF/web.xml</descriptor>
                    </webApp>
                    <httpConntector>
                        <port>8081</port>
                        <host>127.0.0.1</host>
                    </httpConntector>          
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>com.jamonapi</groupId>
                        <artifactId>jamon</artifactId>
                        <version>2.75</version>
                    </dependency>            
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/*IT.java</include>
                    </includes>
                    <skipTests>true</skipTests> 
                    <!--                   <systemProperties>
                        <property>
                            <name>jersey.config.test.container.factory</name>
                            <value>org.glassfish.jersey.test.framework.spi.container.external.ExternalTestContainerFactory</value>
                        </property>
                        <property>
                            <name>jersey.test.host</name>
                            <value>localhost</value>
                        </property>
                        <property>
                            <name>jersey.config.test.container.port</name>
                            <value>8080</value>
                        </property>
                    </systemProperties>  -->
                </configuration>
            </plugin>                       
			<plugin>
        		<groupId>org.apache.maven.plugins</groupId>
        		<artifactId>maven-release-plugin</artifactId>
        		<version>2.5.3</version>
        	</plugin>
        </plugins>
    </build>
    <distributionManagement>
        <repository>
            <id>release</id>
            <name>libs-release-local</name>
            <url>https://repos.dwo.nl/artifactory/libs-release-local</url>
        </repository>
        <snapshotRepository>
            <id>snapshots</id>
            <name>libs-snapshot-local</name>
            <url>https://repos.dwo.nl/artifactory/libs-snapshot-local</url>
        </snapshotRepository>
    </distributionManagement>
    <profiles>
        <profile>
            <id>ws</id>
            <build>
                <finalName>${project.artifactId}</finalName>
            </build>
            <properties>
                <comment>speciaal for ws.fisme.science.uu.nl</comment>
                <dsaccess>//app.dwo.nl/dwo/dsaccess</dsaccess>
                <dsaccess.url>https://app.dwo.nl/dwo/dsaccess</dsaccess.url>
                <dsrest.url>https://app.dwo.nl/dwo/rest/</dsrest.url>
                <ideas>/servlet/IdeasServlet</ideas>
            </properties>
        </profile>
        <profile>
            <id>dummytwo</id>
            <build>
                <finalName>${project.artifactId}_local</finalName>
            </build>
            <properties>
                <comment>speciaal for localhost met dummytwo.dwo.nl als database</comment>
                <dsaccess>https://dummytwo.dwo.nl/dwo/xmlrpc</dsaccess>
                <dsaccess.url>http://dummytwo.dwo.nl/dwo/xmlrpc</dsaccess.url>
                <dsrest.url>http://dummytwo.dwo.nl/dwo/rest/</dsrest.url>
            </properties>
        </profile>
        <profile>
            <id>local</id>
            <build>
<!--                <finalName>${project.artifactId}_local</finalName>-->
            </build>
            <properties>
                <comment>speciaal for localhost met dummytwo.dwo.nl als database</comment>
                <dsaccess>http://127.0.0.1:8080/dwo/xmlrpc</dsaccess>
                <dsaccess.url>http://127.0.0.1:8080/dwo/xmlrpc</dsaccess.url>
                <dsrest.url>http://127.0.0.1:8080/dwo/rest/</dsrest.url>
            </properties>
        </profile>
    </profiles>
    <scm>
        <developerConnection>scm:svn:https://svn.science.uu.nl/repos/project.fisme.java/DWOmAccess/branches/dwo2</developerConnection>
    </scm>
    <parent>
    	<groupId>nl.uu.fi.dwo</groupId>
    	<artifactId>DWO</artifactId>
    	<version>2.0-SNAPSHOT</version>
    	<relativePath>../DWO</relativePath>
    </parent>
</project>
