#release configuration
#Tue Mar 28 16:20:40 CEST 2017
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
scm.url=scm\:svn\:https\://svn.science.uu.nl/repos/project.fisme.java/DWOProject/DWO-LMS/DWOServer/trunk
preparationGoals=clean verify install
remoteTagging=true
projectVersionPolicyId=default
scm.commentPrefix=[maven-release-plugin] 
scm.tagBase=https\://svn.science.uu.nl/repos/project.fisme.java/DWOProject/DWO-LMS/DWOServer/tags/
exec.snapshotReleasePluginAllowed=false
exec.additionalArguments=-P dwo-signing-vars,artifactory
completedPhase=check-poms
