<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- Adjust artifact, name and description for new projects -->
    <parent>
        <groupId>nl.uu.fi.dwo</groupId>
        <artifactId>dwo</artifactId>
        <version>2.5.50</version>
        <relativePath>../DWO/pom.xml</relativePath>
    </parent>
    <artifactId>dwoserver</artifactId>
    <packaging>war</packaging>
    <name>${project.build.finalName}</name>
    <url>http://www.dwo.nl</url>
    <!-- Update year to current when starting a new project -->
    <inceptionYear>2015</inceptionYear> 
    <organization>
        <name>Freudenthal Institute</name>
        <url>http://www.uu.nl/onderzoek/freudenthal-instituut</url>
    </organization> 

    <developers>
        <developer>
            <id>Gert van der Plas</id>
            <name>plas0006</name>
            <email>g.a.j.vanderplas@uu.nl</email>
            <organization>Freudenthal Institute</organization>
            <organizationUrl>http://www.uu.nl/onderzoek/freudenthal-instituut</organizationUrl>
            <roles>
                <role>Java Developer</role>
            </roles>
        </developer>
        <developer>
            <id>Wim van Velthoven</id>
            <name>velth101</name>
            <email>w.p.g.vanvelthoven@uu.nl</email>
            <organization>Freudenthal Institute</organization>
            <organizationUrl>http://www.uu.nl/onderzoek/freudenthal-instituut</organizationUrl>
            <roles>
                <role>Java Developer</role>
            </roles>
        </developer>
    </developers>
    <properties>
        <maven.javadoc.failOnError>false</maven.javadoc.failOnError>
        <context.xml>context.xml</context.xml>
        <jdbc.driver>software.amazon.jdbc.Driver</jdbc.driver>
        <jdbc.url>jdbc:mysql://127.0.0.1:3306/dwojunittest?allowPublicKeyRetrieval=true&amp;useSSL=false</jdbc.url>
        <jdbc.url.xml>jdbc:mysql://127.0.0.1:3306/dwojunittest?allowPublicKeyRetrieval=true&amp;amp;useSSL=false</jdbc.url.xml>
        <jdbc.copy>jdbc:mysql://127.0.0.1:3306/dwocopy?useSSL=false</jdbc.copy>
    </properties>
  
    <!-- dependencies -->
    <dependencies>
		<dependency>
			<groupId>jakarta.validation</groupId>
    		<artifactId>jakarta.validation-api</artifactId>
    		<version>2.0.2</version>
    		<scope>test</scope>
		</dependency>
         <dependency>
            <groupId>nl.uu.fi.dwo</groupId>
            <artifactId>dwo-commons-lib</artifactId>
        </dependency>
		<dependency>
		    <groupId>com.sun.mail</groupId>
		    <artifactId>javax.mail</artifactId>
		    <version>1.6.2</version>
		</dependency> 
      <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.0.1</version>
            <scope>provided</scope>
        </dependency>        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>bouncycastle</groupId>
            <artifactId>bcprov-jdk16</artifactId>
            <version>140</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.json</artifactId>
            <version>1.1</version>
        </dependency>
        <dependency>
            <groupId>org.skyscreamer</groupId>
            <artifactId>jsonassert</artifactId>
            <version>1.5.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>eclipselink</artifactId>
            <version>2.6.0</version>
            <exclusions>

            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.jpa.modelgen.processor</artifactId>
            <version>2.6.0</version>
        </dependency> 
        <dependency>
            <groupId>org.glassfish.jersey.containers</groupId>
            <!-- if your container implements Servlet API older than 3.0, use "jersey-container-servlet-core"  -->
            <artifactId>jersey-container-servlet</artifactId>
            <version>2.18</version>
            <exclusions>
 
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>2.18</version>
        </dependency>
        <!--  best found media type json support, faster than jackson -->
        <dependency>
            <groupId>com.owlike</groupId>
            <artifactId>genson</artifactId>
            <version>1.6</version>
        </dependency> 
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>8.4.0</version>
            <!--comment scope for elastic beanstalk-->
            <scope>runtime</scope>
            <exclusions>
            	<exclusion>
            		<groupId>com.google.protobuf</groupId>
            		<artifactId>protobuf-java</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
        <dependency>
		  <groupId>software.amazon.jdbc</groupId>
  		  <artifactId>aws-advanced-jdbc-wrapper</artifactId>
  		  <version>2.6.5</version>
  		  <scope>runtime</scope>
  		  <optional>true</optional>
        </dependency>
		<dependency>
		    <groupId>org.postgresql</groupId>
		    <artifactId>postgresql</artifactId>
		    <version>42.7.7</version>
		    <scope>test</scope>
		</dependency>
		 <dependency> 
		  <groupId>org.slf4j</groupId>
		  <artifactId>slf4j-jdk14</artifactId>
		  <version>1.7.30</version>
		  <scope>runtime</scope>
		  <optional>true</optional>
		</dependency>
		       <dependency>
            <groupId>org.tuckey</groupId>
            <artifactId>urlrewritefilter</artifactId>
            <version>4.0.3</version>
        </dependency>
    	<dependency>
    		<groupId>nl.uu.fi.dwo.rest</groupId>
    		<artifactId>dwo-rest-lib</artifactId>
    	</dependency>
		<dependency>
		    <groupId>com.fasterxml.jackson.core</groupId>
		    <artifactId>jackson-annotations</artifactId>
		    <version>2.12.6</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
			<version>0.11.5</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<version>0.11.5</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId>
			<version>0.11.5</version>
		</dependency>
        <dependency>
            <groupId>nl.uu.fi.dwo.rest</groupId>
            <artifactId>dwo-jclient-lib</artifactId>
        </dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>6.2.0.Final</version>
			<scope>test</scope>
		</dependency>
			<dependency>
			   <groupId>org.glassfish</groupId>
			   <artifactId>javax.el</artifactId>
			   <version>3.0.1-b08</version>
			   <scope>test</scope>
		   </dependency>
			<dependency>
		        <groupId>com.kstruct</groupId>
		        <artifactId>gethostname4j</artifactId>
		        <version>1.0.0</version>
		    </dependency>
	   		<dependency>
			    <groupId>javax.cache</groupId>
			    <artifactId>cache-api</artifactId>
			    <version>1.1.1</version>
			    <scope>provided</scope>
	   		</dependency>
	   		<dependency>
	   			<groupId>nl.numworx.schoolyear</groupId>
	   			<artifactId>schoolyear-jclient-lib</artifactId>
	   			<version>2.5.48</version>
	   		</dependency>
			<dependency>
			  <groupId>dev.samstevens.totp</groupId>
			  <artifactId>totp</artifactId>
			  <version>1.7.1</version>
			</dependency>
<!-- string template library -->
			 <dependency>
			    <groupId>org.antlr</groupId>
			    <artifactId>ST4</artifactId>
			    <version>4.3.4</version>
			    <scope>compile</scope>
			</dependency>

   	</dependencies>
        
    <build>
	  <testResources>
		<testResource>
			<directory>src/test/resources</directory>
			<filtering>true</filtering>
		</testResource>
	  </testResources>
        <plugins>
             <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>templating-maven-plugin</artifactId>
                <version>1.0.0</version>
                <executions>
                    <execution>
                        <id>filter-src</id>
                        <goals>
                            <goal>filter-sources</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
           <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                   <source>${jdk.version}</source>
                    <target>${jdk.version}</target>
                    <executable>${jdk}/bin/javac</executable>
                    <fork>false</fork>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.7</version>
                <configuration>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>      
                                  
             <!-- ensure the build number is available as ${buildNumber} -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>1.3</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!--
                     doCheck and doUpdate actually talk to repository if it's true,
                     Check would check that there are no local changes.
                     Update would update it
                    -->
                    <doCheck>false</doCheck>
                    <doUpdate>false</doUpdate>
                </configuration>
            </plugin>    
            
            <!-- put the build number in the manifest -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.5</version>
                        <configuration>
                            <archive>
                                <manifest>
                                    <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                                </manifest>
                                <manifestEntries>
                                    <Implementation-Build>${buildNumber}</Implementation-Build>
                                    <JavaClient-Version>${project.version}</JavaClient-Version>
                                    <HtmlClient-Version />
                                    <Implementation-Timestamp>${timestamp}</Implementation-Timestamp>
                                    <Implementation-ScmBranch>${scmBranch}</Implementation-ScmBranch>
                                </manifestEntries>
                            </archive>
                        </configuration>
            </plugin>
           <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <warSourceDirectory>src/main/webapp</warSourceDirectory>
                    <webXml>src/main/webapp/WEB-INF/web.xml</webXml>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
  					<attachClasses>true</attachClasses>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                        </manifest>
                        <manifestEntries>
                            <!-- put the project version and build number in the manifest -->
                                    <Implementation-Build>${buildNumber}</Implementation-Build>
                                    <Implementation-Timestamp>${timestamp}</Implementation-Timestamp>
                                    <Implementation-ScmBranch>${scmBranch}</Implementation-ScmBranch>
                        </manifestEntries>
                    </archive>
                    <!-- put the build number in the web.xml of the war file -->
                    <webResources>
                        <resource>
                            <filtering>true</filtering>
                            <directory>src/main/webapp</directory>
                            <includes>
                                <include>**/web.xml</include>
                            </includes>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>  
        <plugin>
                <groupId>org.apache.tomcat.maven</groupId>
                <artifactId>tomcat7-maven-plugin</artifactId>
                <version>2.2</version>
                    <configuration>
                        <server>TomcatServer</server>
                        <path>/dwo</path>
                        <systemProperties>
                            <java.util.secureRandomSeed>true</java.util.secureRandomSeed>
                    		<DWO_ENV>testentree</DWO_ENV>
                    		<DWO_REDIRECT>false</DWO_REDIRECT>
                    		<ALLOW_ORIGIN>http://localhost:8080</ALLOW_ORIGIN>
                    		<ENV_NOSEB>true</ENV_NOSEB>                   
<!--                    		<XAPI_ENDPOINT>http://localhost:8089/xapi/</XAPI_ENDPOINT>-->
<!--                    		<XAPI_AUTH>bXlfa2V5Om15X3NlY3JldA==</XAPI_AUTH>-->
                    		<AZ_ENDPOINT>http://127.0.0.1:10000/devstoreaccount1/</AZ_ENDPOINT>
                    		<AZ_SHAREDKEY>Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==</AZ_SHAREDKEY>
                    		<S3_BUCKET>devstoreaccount1</S3_BUCKET>      
                        </systemProperties>
                        <warFile>target/${project.artifactId}-${project.version}.war</warFile>
                            <contextFile>src/test/tomcat/${context.xml}</contextFile>
                            <warSourceDirectory>target/${project.artifactId}-${project.version}</warSourceDirectory>
                       	<webapps>
                         <webapp>
						    <groupId>nl.numworx.uploadwidget</groupId>
						    <artifactId>uploadwidget-local</artifactId>
						    <version>2.5.48</version>
                            <type>war</type>
                            <contextPath>/dwo/dav/upload</contextPath>
                            <asWebapp>true</asWebapp>
                         </webapp>
                        </webapps>
                   </configuration>
                    <dependencies>
   			<dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>
          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-util</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>
          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-coyote</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>
          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-api</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-jdbc</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-dbcp</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-servlet-api</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-jsp-api</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-jasper</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-jasper-el</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-el-api</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-catalina</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-tribes</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-catalina-ha</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-annotations-api</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-juli</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>

          <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-logging-juli</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>
          <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-logging-log4j</artifactId>
            <version>${tomcat7.version}</version>
          </dependency>                         
				<dependency>
				    <groupId>org.redisson</groupId>
				    <artifactId>redisson-all</artifactId>
				    <version>3.22.1</version>
				</dependency>
				<dependency>
    				<groupId>nl.uu.fi.dwo.rest</groupId>
					<artifactId>redis-config</artifactId>
					<version>2.5.48</version>
				</dependency>
          </dependencies>
            </plugin> 
            
                <!--
                    By default, the Surefire Plugin will automatically include all test classes with the following wildcard patterns:
                    "**/Test*.java" - includes all of its subdirectory and all java filenames that start with "Test". "**/*Test.java" -
                    includes all of its subdirectory and all java filenames that end with "Test". "**/*TestCase.java" - includes all of
                    its subdirectory and all java filenames that end with "TestCase".

            dedicated test server: -Djersey.test.host=myhost.org -Djersey.config.test.container.port=8080
            -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.2</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/*IT.java</include>
                    </includes>
                    <skipTests>${junit.test}</skipTests> 
				    <jdkToolchain>
				        <version>11</version>
				    </jdkToolchain>
                </configuration>
            </plugin>                    
        </plugins>
        <finalName>${project.artifactId}-${project.version}</finalName>
        <pluginManagement>
            <plugins>
                <!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
                <plugin>
                    <groupId>org.eclipse.m2e</groupId>
                    <artifactId>lifecycle-mapping</artifactId>
                    <version>1.0.0</version>
                    <configuration>
                        <lifecycleMappingMetadata>
                            <pluginExecutions>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>
                                            org.codehaus.mojo
                                        </groupId>
                                        <artifactId>
                                            buildnumber-maven-plugin
                                        </artifactId>
                                        <versionRange>
                                            [1.3,)
                                        </versionRange>
                                        <goals>
                                            <goal>
                                                create-timestamp
                                            </goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore />
                                    </action>
                                </pluginExecution>
                            </pluginExecutions>
                        </lifecycleMappingMetadata>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
    
    <!--    <repositories>
            <repository>
                <id>xmlrpc</id>
                <url>http://ws.apache.org/xmlrpc/</url>
            </repository>
        </repositories>
    -->
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.0-beta-2</version>
                <configuration>
                    <reportPlugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-project-info-reports-plugin</artifactId>
                            <version>2.2</version>
                            <reports>
                                <report>cim</report>
                                <report>issue-tracking</report>
                            </reports>
                        </plugin>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-javadoc-plugin</artifactId>
                            <version>2.2</version>
                        </plugin>
                    </reportPlugins>
                </configuration>
            </plugin>
        </plugins>
    </reporting>
    <!-- profile for running junittests -->
    <profiles>
		<profile>
			<id>postgres</id>
			<properties>
				<jdbc.driver>org.postgresql.Driver</jdbc.driver>
				<jdbc.url>jdbc:postgresql://localhost:5432/dwojunittest</jdbc.url>				
			</properties>
		</profile>
        <profile>
            <id>nojunittests</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <junit.test>true</junit.test>
            </properties>
        </profile>
        <profile>
            <id>dwodevel-db</id>
            <properties>
                <junit.test>false</junit.test>
                <context.xml>context-dwo_devel.xml</context.xml>
            </properties>
        </profile>
        <profile>
            <id>junit-db</id>
            <properties>
                <junit.test>false</junit.test>
                <context.xml>context-junittest.xml</context.xml>
            </properties>
        </profile>
        <profile>
            <id>dummytwo-db</id>
            <properties>
                <junit.test>false</junit.test>
                <context.xml>context-dummytwo.xml</context.xml>
            </properties>
        </profile>
        <profile>
            <id>test</id>
            <activation>
				<property><name>env.CI</name></property>
			</activation>
            <properties>
                <junit.test>false</junit.test>
            </properties>
			<dependencies>
				<dependency>
				    <groupId>org.jsr107.ri</groupId>
				    <artifactId>cache-ri-impl</artifactId>
				    <version>1.1.1</version>
				    <scope>test</scope>
				</dependency>
			</dependencies>
        </profile>
        
		<profile>
			<id>java17</id>
			<dependencies>
			 <dependency>
	    		<groupId>javax.xml.bind</groupId>
	    		<artifactId>jaxb-api-osgi</artifactId>
	    		<version>2.2.7</version>
			 </dependency>
			</dependencies>
		</profile>
		<profile>
			<id>memcached-jcache</id>
			<dependencies>
				<dependency>
				    <groupId>org.memcached</groupId>
    				<artifactId>memcached-jcache</artifactId>
    				<version>1.0</version>
		    		<scope>test</scope>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>ri-jcache</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<dependencies>
				<dependency>
				    <groupId>org.jsr107.ri</groupId>
				    <artifactId>cache-ri-impl</artifactId>
				    <version>1.1.1</version>
				    <scope>runtime</scope>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>redis-jcache</id>
			<dependencies>
			</dependencies>		
		</profile>
    </profiles> 
</project>
