/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.dwo.dwojapplet.gui.trial;

/**
 *
 * @author G.A.J. van der Plas
 */
public class JPanelProfile extends javax.swing.JPanel {

    /**
     * Creates new form JPanelprofile
     */
    public JPanelProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneProfile = new javax.swing.JTabbedPane();
        jPanelPersonalDetails = new javax.swing.JPanel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelCurPassword = new javax.swing.JLabel();
        jLabelNewPassword = new javax.swing.JLabel();
        jLabelConfirmPassword = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelGivenName = new javax.swing.JLabel();
        jLabelInsertion = new javax.swing.JLabel();
        jLabelFamilyName = new javax.swing.JLabel();
        jTextFieldConfirmPassword = new javax.swing.JTextField();
        jTextFieldNewPassword = new javax.swing.JTextField();
        jTextFieldUserName = new javax.swing.JTextField();
        jTextFieldCurPassword = new javax.swing.JTextField();
        jTextFieldGivenName = new javax.swing.JTextField();
        jTextFieldInsertion = new javax.swing.JTextField();
        jTextFieldFamilyName = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jPanelSchoolAndClass = new javax.swing.JPanel();
        jLabelSchoolClassAndRole = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSchoolAndClass = new javax.swing.JTable();
        jTextFieldSchoolClassAndRole = new javax.swing.JTextField();

        jLabelUserName.setText("gebruikersnaam");

        jLabelCurPassword.setText("Huidig wachtwoord");

        jLabelNewPassword.setText("Nieuw wachtwoord");

        jLabelConfirmPassword.setText("Bevestig wachtwoord");

        jLabelGivenName.setText("Voornaam");

        jLabelInsertion.setText("Tussenvoegsel");

        jLabelFamilyName.setText("Achternaam");

        jTextFieldUserName.setEditable(false);
        jTextFieldUserName.setToolTipText("");

        jTextFieldCurPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCurPasswordActionPerformed(evt);
            }
        });

        jTextFieldInsertion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInsertionActionPerformed(evt);
            }
        });

        jLabelEmail.setText("E-mail");

        jButtonUpdate.setText("Update gegevens");

        javax.swing.GroupLayout jPanelPersonalDetailsLayout = new javax.swing.GroupLayout(jPanelPersonalDetails);
        jPanelPersonalDetails.setLayout(jPanelPersonalDetailsLayout);
        jPanelPersonalDetailsLayout.setHorizontalGroup(
            jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                        .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldUserName))
                    .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                        .addComponent(jLabelCurPassword)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCurPassword))
                    .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                        .addComponent(jLabelNewPassword)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNewPassword))
                    .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                        .addComponent(jLabelConfirmPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldConfirmPassword))
                    .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                        .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGivenName)
                            .addComponent(jLabelInsertion)
                            .addComponent(jLabelFamilyName)
                            .addComponent(jLabelEmail))
                        .addGap(36, 36, 36)
                        .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldGivenName)
                            .addComponent(jTextFieldFamilyName)
                            .addComponent(jTextFieldInsertion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldEmail)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalDetailsLayout.createSequentialGroup()
                        .addGap(0, 446, Short.MAX_VALUE)
                        .addComponent(jButtonUpdate)))
                .addContainerGap())
        );
        jPanelPersonalDetailsLayout.setVerticalGroup(
            jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCurPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCurPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewPassword)
                    .addComponent(jTextFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfirmPassword)
                    .addComponent(jTextFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGivenName)
                    .addComponent(jTextFieldGivenName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInsertion)
                    .addComponent(jTextFieldInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFamilyName)
                    .addComponent(jTextFieldFamilyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdate)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPaneProfile.addTab("Persoonsgegevens", jPanelPersonalDetails);

        jLabelSchoolClassAndRole.setText("Geselecteerde school,  klas en rol: ");

        jSplitPane1.setResizeWeight(0.5);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        jTableSchoolAndClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "School", "Class"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSchoolAndClass.setMinimumSize(new java.awt.Dimension(200, 300));
        jTableSchoolAndClass.setPreferredSize(new java.awt.Dimension(200, 300));
        jScrollPane1.setViewportView(jTableSchoolAndClass);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jTextFieldSchoolClassAndRole.setEditable(false);

        javax.swing.GroupLayout jPanelSchoolAndClassLayout = new javax.swing.GroupLayout(jPanelSchoolAndClass);
        jPanelSchoolAndClass.setLayout(jPanelSchoolAndClassLayout);
        jPanelSchoolAndClassLayout.setHorizontalGroup(
            jPanelSchoolAndClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSchoolAndClassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSchoolAndClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelSchoolAndClassLayout.createSequentialGroup()
                        .addGroup(jPanelSchoolAndClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelSchoolAndClassLayout.createSequentialGroup()
                                .addComponent(jLabelSchoolClassAndRole)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSchoolClassAndRole, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSchoolAndClassLayout.setVerticalGroup(
            jPanelSchoolAndClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSchoolAndClassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSchoolAndClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSchoolClassAndRole)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSchoolClassAndRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneProfile.addTab("School en klas", jPanelSchoolAndClass);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCurPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCurPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCurPasswordActionPerformed

    private void jTextFieldInsertionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInsertionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInsertionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelConfirmPassword;
    private javax.swing.JLabel jLabelCurPassword;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFamilyName;
    private javax.swing.JLabel jLabelGivenName;
    private javax.swing.JLabel jLabelInsertion;
    private javax.swing.JLabel jLabelNewPassword;
    private javax.swing.JLabel jLabelSchoolClassAndRole;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPersonalDetails;
    private javax.swing.JPanel jPanelSchoolAndClass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPaneProfile;
    private javax.swing.JTable jTableSchoolAndClass;
    private javax.swing.JTextField jTextFieldConfirmPassword;
    private javax.swing.JTextField jTextFieldCurPassword;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFamilyName;
    private javax.swing.JTextField jTextFieldGivenName;
    private javax.swing.JTextField jTextFieldInsertion;
    private javax.swing.JTextField jTextFieldNewPassword;
    private javax.swing.JTextField jTextFieldSchoolClassAndRole;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
