<?xml version='1.0' ?>
<project name='_beans_wiskopdrbeans' basedir='../../../..' default='cpjc' >
	<description>
	Auteur: Wim

	Deze ant build kan je gebruiken voor het automatiseren van common tasks in de referentie omgeving.
	!Let op de eis dat de main application name gelijk is aan de project name!


	</description>
	<!-- Dit is een bean! Dus geen jar -->
	<property name="no.jar" value="true"/>

	<dirname property="ant.dir" file="${ant.file}"  />
	<property file="${ant.dir}/build.properties"/>

	<property name='dosdrive' value='N:' />
	<property name='java.resources' value='/home/java/resources' />
	<property name='common.build' value='${java.resources}/ant/common-build.xml' />
	<condition property='dos' value='dos' >
	   	<os family='dos' />
	</condition>
	<condition property='drive' value='${dosdrive}'>
		<os family='dos' />
	</condition>
	<condition property='drive' value=''  >
		<os family='unix' />
	</condition>

	<import file="${drive}${common.build}" />

	<target name="mock" description="Handel @mock:generate interfaces af " depends='init' >

		<taskdef name="mockobjects"
	             classname="xdoclet.modules.mockobjects.MockObjectDocletTask"
	    >
			<classpath>
				<fileset dir='${dir.xdoclet}' includes='*.jar' />
			</classpath>
		</taskdef>
	    	

	    <!-- MockDoclet task -->
	    <mockobjects destdir="${src}">

	      <!-- Process all src files -->
	      <fileset dir="${src}" includes="**/*.java" />

	      <!-- Generate Mock Object classes -->
	      <mockobjects>
	      	<packagesubstitution packages="beans.ideas" substituteWith="servlet.ideas.demo"
	      	/>
	      </mockobjects>

	    </mockobjects>
	    	
	 </target>

</project>
