<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>nl.uu.fi.dwo.mobile</groupId>
	<artifactId>dwoplayer</artifactId>
	<packaging>war</packaging>
	<name>DWO player</name>
    <scm>
        <developerConnection>scm:git:git@github.com:UtrechtUniversity/numworx-dwo-project.git</developerConnection>
    </scm>
	<build>
		<extensions>
			<extension>
				<groupId>org.kuali.maven.wagons</groupId>
				<artifactId>maven-s3-wagon</artifactId>
				<version>1.2.1</version>
			</extension>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ssh</artifactId>
				<version>2.8</version>
			</extension>
		</extensions>
		<finalName>${finalName}</finalName>
		<sourceDirectory>src</sourceDirectory>
		<testSourceDirectory>test</testSourceDirectory>
		<resources>
			<resource>
				<directory>src</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
				<configuration>
		<annotationProcessorPaths>
			<path>
			<groupId>com.google.dagger</groupId>
			<artifactId>dagger-compiler</artifactId>
			<version>${daggerVersion}</version>
			</path>
		</annotationProcessorPaths>
				</configuration>
			<dependencies>
				<dependency>
				    <groupId>javax.annotation</groupId>
				    <artifactId>javax.annotation-api</artifactId>
				    <version>1.3.2</version>
				</dependency>
			</dependencies>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<version>1.3</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<!-- doCheck and doUpdate actually talk to repository if it's true, 
						Check would check that there are no local changes. Update would update it -->
					<doCheck>false</doCheck>
					<doUpdate>false</doUpdate>
					<!-- This ensures that even if we are not connected to scm than also 
						take the version from local .svn file -->
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>templating-maven-plugin</artifactId>
				<version>1.0.0</version>
				<executions>
					<execution>
						<id>filter-src</id>
						<goals>
							<goal>filter-sources</goal>
						</goals>
						<configuration>
							<sourceDirectory>${basedir}/java-templates</sourceDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
            <plugin> <!-- attach-sources voor GWT -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>         
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<warSourceDirectory>war</warSourceDirectory>
					<warSourceIncludes>DWOplayer.jsp,KeyboardGWT.css,DWOplayer.css,${runTarget},GeoGebra.html,MCSquared.jsp,images/**,scripts/**,WEB-INF/lib/*,WEB-INF/web.xml,PrintPlayer.css</warSourceIncludes>
					<classifier>${warClassifier}</classifier>
					<failOnMissingWebXml>false</failOnMissingWebXml>
					<packagingIncludes>**</packagingIncludes>
					<packagingExcludes>WEB-INF/classes/**,WEB-INF/deploy/**</packagingExcludes>
					<attachClasses>true</attachClasses>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>${gwtVersion}</version>
				<configuration>
					<localWorkers>1</localWorkers>
					<module>${gwtModule}</module>
					<runTarget>${runTarget}</runTarget>
					<warSourceDirectory>war</warSourceDirectory>
					<extraJvmArgs>-Xms768m -Xmx2048m</extraJvmArgs>
					<webXml>war/WEB-INF/web.xml</webXml>
					<i18nConstantsWithLookupBundles>
						<i18nConstantsWithLookupBundle>nl.uu.fi.dwo.mobile.client.ui.views.interactionviews.mapperconstants.Hint</i18nConstantsWithLookupBundle>
						<i18nConstantsWithLookupBundle>nl.uu.fi.dwo.mobile.client.ui.views.interactionviews.mapperconstants.Feedback</i18nConstantsWithLookupBundle>
					</i18nConstantsWithLookupBundles>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>i18n</goal>
							<goal>compile</goal>
							<goal>test</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
					    <groupId>org.jsr107.ri</groupId>
					    <artifactId>cache-ri-impl</artifactId>
					    <version>1.1.1</version>
					</dependency>					
				</dependencies>
			</plugin>
			<plugin>
				<!-- usage: jetty:run-war of jetty:run-exploded -->
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-maven-plugin</artifactId>
				<version>9.0.0.v20130308</version>
			</plugin>
			<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-install-plugin</artifactId>
					<version>3.1.1</version>
					<configuration>
						<allowIncompleteProjects>true</allowIncompleteProjects>
					</configuration>			
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency><!-- before GWT -->
			<groupId>org.vectomatic</groupId>
			<artifactId>lib-gwt-svg</artifactId>
			<version>0.5.15</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<scope>provided</scope>
			<version>${gwtVersion}</version>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.keyboard</groupId>
			<artifactId>keyboardgwt</artifactId>
			<version>2.5.48</version>
			<exclusions>
				<exclusion>
					<groupId>fi.wiskopdrgwt</groupId>
					<artifactId>wiskopdrgwt</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-dev</artifactId>
			<version>${gwtVersion}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mitre.dsmiley.httpproxy</groupId>
			<artifactId>smiley-http-proxy-servlet</artifactId>
			<version>1.7</version>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>nl.uu.fi.dwo.account</groupId>
			<artifactId>account</artifactId>
			<version>2.5.48</version>
			<classifier>classes</classifier>
			<exclusions>
				<exclusion>
					<groupId>javax.xml.bind</groupId>
					<artifactId>jaxb-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.account</groupId>
			<artifactId>account</artifactId>
			<version>2.5.48</version>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.ideas</groupId>
			<artifactId>ideasgwt</artifactId>
			<version>0.1.9</version>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>formule</artifactId>
		</dependency>
		<dependency>
			<groupId>nl.numworx.gwtpatch</groupId>
			<artifactId>gwtpatch</artifactId>
			<version>2.5.48</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx.gwtpatch</groupId>
			<artifactId>gwtpatch</artifactId>
			<version>2.5.48</version>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.0</version>
			<classifier>sources</classifier>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.google.dagger</groupId>
			<artifactId>dagger-gwt</artifactId>
			<version>${daggerVersion}</version>
		</dependency>
		<dependency>
		    <groupId>com.vaadin.addon</groupId>
		    <artifactId>pointer-events</artifactId>
		    <version>1.0</version>
		</dependency>
        <dependency>
            <groupId>com.owlike</groupId>
            <artifactId>genson</artifactId>
            <version>1.4</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.owlike</groupId>
            <artifactId>genson</artifactId>
            <version>1.4</version>
			<classifier>sources</classifier>
            <scope>provided</scope>
        </dependency> 
        <dependency>
       		<groupId>com.google.code.findbugs</groupId>
			<artifactId>jsr305</artifactId>
			<version>1.3.9</version>
        	<scope>provided</scope>
        </dependency>
        <dependency>
			<groupId>nl.uu.fi.dwo.rest</groupId>
			<artifactId>dwo-jclient-lib</artifactId>
			<exclusions>
				<exclusion>
					<groupId>javax.xml.bind</groupId>
					<artifactId>jaxb-api</artifactId>
				</exclusion>
			</exclusions>
        </dependency>
        <dependency>
		    <groupId>org.jsr107.ri</groupId>
		    <artifactId>cache-ri-impl</artifactId>
			<version>1.1.1</version>
		    <scope>provided</scope>
		</dependency>			

	</dependencies>
	<parent>
        <groupId>nl.uu.fi.dwo</groupId>
        <artifactId>dwo</artifactId>
        <version>3.0.0</version>
        <relativePath>../DWO/pom.xml</relativePath>
	</parent>
	<properties>
		<daggerVersion>2.42</daggerVersion>
		<maven.test.skip>true</maven.test.skip>
		<gwtModule>${project.groupId}.DWO2playerDebug</gwtModule>
		<finalName>${project.artifactId}</finalName>
		<runTarget>${project.artifactId}.html</runTarget>
		<warClassifier>dwo</warClassifier>
		<gwt.copyWebapp>true</gwt.copyWebapp>
		<gwtVersion>2.10.0</gwtVersion>
        <maven.javadoc.failOnError>false</maven.javadoc.failOnError>
        <maven.javadoc.skip>true</maven.javadoc.skip>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
	<profiles>
		<profile>
			<id>WiskOpdrPlayerDebug</id>
			<properties>
				<finalName>WiskOpdrPlayerDebug</finalName>
				<gwtModule>${project.groupId}.WiskOpdrPlayerDebug</gwtModule>
				<gwt.style>PRETTY</gwt.style>
			</properties>
		</profile>
		<profile>
			<id>PrintPlayer</id>
			<properties>
				<finalName>PrintPlayer</finalName>
				<gwtModule>${project.groupId}.PrintPlayer</gwtModule>
				<gwt.style>PRETTY</gwt.style>
			</properties>
		</profile>
		<profile>
			<id>WiskOpdrPlayer</id>
			<properties>
				<finalName>WiskOpdrPlayer</finalName>
				<gwtModule>${project.groupId}.WiskOpdrPlayer</gwtModule>
				<wagonPhase>none</wagonPhase>
				<s3>s3://ebs-dev-dwo-nl</s3>
				<gwt.style>OBFUSCATED</gwt.style>
			</properties>
		<build>
			<plugins>
			  <plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>wagon-maven-plugin</artifactId>
				<version>1.0</version>
				<executions>
					<execution>
						<id>upload</id>
						<goals>
							<goal>upload</goal>
						</goals>
						<phase>${wagonPhase}</phase>
					</execution>
				</executions>
				<configuration>
					<fromDir>${project.build.directory}/${finalName}/</fromDir>
					<includes>DWOplayer.css,images/**,DWOplayer/**</includes>
					<!-- <serverId>staff</serverId> -->
					<!-- <url>scp://gemini.science.uu.nl/home/staff/velth101/tmp</url> -->
					<serverId>ubuntu</serverId>
					<url>${s3}</url>
					<toDir>apps</toDir>
				</configuration>

			</plugin>
			
			</plugins>
		</build>
		</profile>
		<profile>
			<id>WidgetPlayer</id>
			<properties>
				<warClassifier>widget</warClassifier>
				<maven.war.webxml>war/WEB-INF/web-dwo2.xml</maven.war.webxml>
				<finalName>WidgetPlayer</finalName>
				<gwtModule>${project.groupId}.WidgetPlayer</gwtModule>
				<wagonPhase>none</wagonPhase>
				<gwt.copyWebapp>false</gwt.copyWebapp>
				<s3>s3://ebs-dev-dwo-nl</s3>
			</properties>
		</profile>
		<profile>
			<id>NoordhoffPlayer</id>
			<properties>
				<gwtModule>${project.groupId}.NoordhoffPlayer</gwtModule>
				<finalName>NoordhoffPlayer</finalName>
			</properties>
		</profile>
		<profile>
			<id>TinCanPlayer</id>
			<properties>
				<gwtModule>${project.groupId}.TinCanPlayer</gwtModule>
				<finalName>TinCanPlayer</finalName>
				<warClassifier>xapi</warClassifier>
				<maven.war.webxml>war/WEB-INF/web-dwo2.xml</maven.war.webxml>
				<gwt.copyWebapp>false</gwt.copyWebapp>
				<gwt.style>PRETTY</gwt.style>
			</properties>
		</profile>
		<profile>
			<id>DWO2player</id>
			<activation>
				<activeByDefault>true</activeByDefault>
				<property><name>performRelease</name><value>true</value></property>
			</activation>
			<properties>
				<finalName>DWO2player</finalName>
				<gwtModule>${project.groupId}.DWO2player</gwtModule>
				<warClassifier />
				<maven.war.webxml>war/WEB-INF/web-dwo2.xml</maven.war.webxml>
				<gwt.copyWebapp>false</gwt.copyWebapp>
				<!-- <gwt.style>PRETTY</gwt.style> -->
				<gwt.compiler.force>true</gwt.compiler.force>
				<gwt.compiler.localWorkers>3</gwt.compiler.localWorkers>
        		<maven.javadoc.failOnError>false</maven.javadoc.failOnError>
			</properties>
			<build>
				<plugins>
					<plugin>
                		<groupId>org.apache.maven.plugins</groupId>
                		<artifactId>maven-release-plugin</artifactId>
                		<version>2.5.3</version>         
            		</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>DWO2playerDebug</id>
			<properties>
				<finalName>DWO2player</finalName>
				<gwtModule>${project.groupId}.DWO2playerDebug</gwtModule>
				<gwt.copyWebapp>true</gwt.copyWebapp>
				<gwt.style>PRETTY</gwt.style>
				<gwt.compiler.force>false</gwt.compiler.force>
 				<warClassifier>debug</warClassifier>
				<maven.war.webxml>war/WEB-INF/web.xml</maven.war.webxml>
				<runTarget>DWO2player.html</runTarget>
			</properties>
			<build>
				<plugins>
				            <plugin>
                <groupId>org.apache.tomcat.maven</groupId>
                <artifactId>tomcat7-maven-plugin</artifactId>
                <version>2.2</version>
                <configuration>
                    <server>TomcatServer</server>
                    <path>/</path>
                    <systemProperties>
                    	<DWO_ENV>test</DWO_ENV>                   
                    </systemProperties>
                    <warSourceDirectory>target/${finalName}</warSourceDirectory>
                    <port>8888</port>
                </configuration> 
                <dependencies>
                    <dependency>
                        <groupId>org.apache.tomcat.embed</groupId>
                        <artifactId>tomcat-embed-core</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-util</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-coyote</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-api</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-jdbc</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-dbcp</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-servlet-api</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-jsp-api</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-jasper</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-jasper-el</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-el-api</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-catalina</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-tribes</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-catalina-ha</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-annotations-api</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-juli</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat.embed</groupId>
                        <artifactId>tomcat-embed-logging-juli</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.tomcat.embed</groupId>
                        <artifactId>tomcat-embed-logging-log4j</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>                                
                </dependencies>
            </plugin>            
				
				
				
				</plugins>
			
			</build>


		</profile>
		<profile> <!-- gebruik deze voor gwt:run -->
			<id>DWO2player-run</id>
			<properties>
				<finalName>DWO2player</finalName>
				<gwtModule>${project.groupId}.DWO2player</gwtModule>
				<gwt.copyWebapp>true</gwt.copyWebapp>
			</properties>
		</profile>
		<profile>
			<id>uploadwidget</id>
			<dependencies>
				<dependency>
				    <groupId>nl.numworx.uploadwidget</groupId>
		    		<artifactId>UploadWidgetGWT</artifactId>
		    		<version>2.5.29</version>
		    		<classifier>classes</classifier>		
				</dependency>
			</dependencies>		
		</profile>
		<profile>
			<id>notebook</id>
			<properties>
				<notebookVersion>0.0.1</notebookVersion>
			</properties>
			<dependencies>
				<dependency>
				    <groupId>nl.numworx.notebook</groupId>
		    		<artifactId>notebookgwt</artifactId>
		    		<version>0.0.1</version>
		    		<classifier>classes</classifier>		
				</dependency>
				<dependency>
				    <groupId>nl.numworx.notebook</groupId>
		    		<artifactId>notebookgwt</artifactId>
		    		<version>0.0.1</version>
		    		<classifier>sources</classifier>		
				</dependency>
			</dependencies>		
		</profile>
		<profile>
			<id>leerdoelwidget</id>
			<properties>
				<leerdoelwidgetVersion>2.5.27-SNAPSHOT</leerdoelwidgetVersion>
			</properties>
			<dependencies>
					<dependency>
						<groupId>nl.numworx.leerdoelwidget</groupId>
						<artifactId>LeerdoelWidgetGWT</artifactId>
						<version>${leerdoelwidgetVersion}</version>
						<classifier>sources</classifier>
					</dependency>
					<dependency>
						<groupId>nl.numworx.leerdoelwidget</groupId>
						<artifactId>LeerdoelWidgetGWT</artifactId>
						<version>${leerdoelwidgetVersion}</version>
						<classifier>classes</classifier>
					</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>running11</id>
			<activation>
				<jdk>[9,)</jdk>
			</activation>
			<dependencies>
				<dependency>
				    <groupId>javax.annotation</groupId>
				    <artifactId>javax.annotation-api</artifactId>
				    <version>1.3.2</version>
				    <scope>provided</scope>
				</dependency>
				<dependency>
				    <groupId>javax.xml.bind</groupId>
				    <artifactId>jaxb-api</artifactId>
				    <version>2.3.0</version>
		 		    <scope>provided</scope>
				</dependency>
			</dependencies>
		</profile>
	</profiles>
</project>
