package fi.wiskopdr.text;

import java.util.Vector;

/**
 * 
 * @author Danny Hendrix
 * 
 */

public class Text_nl implements TextIF
{
	private Vector<String> keys = new Vector<String>();
	private Vector<String> values = new Vector<String>();

	public Text_nl()
	{
		Object[][] items = this.getContents();
		for (int i = 0; i < items.length; i++)
		{
			keys.add(items[i][0].toString());
			values.add(items[i][1].toString());
		}
	}

	public Object[][] getContents()
	{
		return contents;
	}

	public String getString(String key)
	{
		int keyint = keys.indexOf(key);
		return values.get(keyint);
	}

	static final Object[][] contents =
	{
	{ "terugKnopLabel", "Terug" },

	{ "terugKnopToolTip", "Stap terug" },
	{ "gelijkwaardigKnopToolTip", "Geef een gelijkwaardige formule" },
	{ "opdrachtToolTip", "Kies opdracht" },
	{ "zelfKnopToolTip", "Maak zelf een opdracht. \n Vul een eigen formule in." },

	{ "haakjesLabel0", "  haakjes" },
	{ "haakjesLabel1", "    weg" },
	{ "herleidLabel0", "   herleid" },
	{ "herleidLabel1", "" },
	{ "ontbindLabel0", "  ontbind" },
	{ "splitsLabel0", "  splits" },
	{ "wortelLabel0", "  wortels" },
	{ "gelijkwaardigLabel0", "  gelijkwaardig" },
	{ "gelijkwaardigLabel1", "    met:" },
	{ "ofLabel", "of" },
	{ "enLabel", "en" },
	{ "subLabel", "Substitueer:" },
	{ "meerLabel", "meer" },

	{ "klaarKnopLabel", "klaar" },
	{ "nakijkKnopLabel", "kijk na" },
	{ "nakijkLabel1", "Nagekeken: " },
	{ "nakijkLabel2", " keer " },
	{ "opnieuwKnopLabel", "opnieuw" },
	{ "allesOpnieuwKnopLabel", "alles opnieuw" },
	{ "opdrachtLabel", "Opdracht:" },
	{ "paginaLabel", "Pagina:" },
	{ "onderdeelLabel", "Onderdeel:" },
	{ "scoreLabel", "Score:" },
	{ "score", "Score: " },
	{ "optiesButtonLabel", "Opties" },
	{ "standaardActiviteitNaam", "Niveau" },
	{ "standaardOpdrachtNaam", "Opdracht" },
	{ "opnieuwPanelTekstMW", "Je verliest je huidige score als je opnieuw begint.\n\nWeet je zeker dat je opnieuw wilt beginnen?" },
	{ "opnieuwPanelTekst", "Je verliest je huidige scores als je opnieuw begint.\n\nWeet je zeker dat je opnieuw wilt beginnen?" },
	{ "opnieuwPanelTitel", "Opnieuw?" },
	{ "lockToetsCBLabel", "Verzegel toets" },
	{ "lockToetsLabel", "Toets verzegeld" },

	{ "choiceOefenen", "Oefenen" },
	{ "choiceOefenenEindloos", "Oefenen eindeloos" },
	{ "choiceOefenenStraf", "Oefenen strafpunten" },
	{ "choiceZelfToets", "Zelftoets" },
	{ "choiceEindToets", "Eindtoets" },

	{ "opdrachtTitelLabel", "Titel:" },
	{ "opdrachtTekstLabel", "Tekst:" },
	{ "randVarLabel", "Variabelen voor random parameters:" },
	{ "startExpLabel", "Startexpressie:" },
	{ "startVergLabel", "Startvergelijking:" },
	{ "antwoordLabel", "Antwoordmodel:" },
	{ "scoringLabel", "Scoring van het antwoord:" },
	{ "puntenLabel", "Punten:" },
	{ "checkTotaalLabel", "Let op! Totaal 10" },
	{ "gelijkwaardigCBLabel", "Gelijkwaardig" },
	{ "herleidingCBLabel", "Herleiding" },
	{ "exactCBLabel", "Exact" },
	{ "stappenCBLabel", "Stappen mogelijk" },
	{ "bewerkingKnoppenCBLabel", "Bewerkingknoppen" },
	{ "bewerkingKnoppenExtraCBLabel", "Bewerkingknoppen extra" },
	{ "abcCBLabel", "abc" },
	{ "subKnopCBLabel", "substituties" },
	{ "subKnopExtraCBLabel", "subst. extra" },
	{ "grafiekToolCBLabel", "Grafiekentool" },
	{ "grafiekToolKnopLabel", "Grafiekentool" },
	{ "vergelijkingCBLabel", "Vergelijking" },
	{ "eindOplossingCBLabel", "Eindoplossing" },
	{ "checkCBLabel", "Kijk na (of niet)" },
	{ "teltMeeCBLabel", "Telt mee in score (of niet)" },
	{ "logCBLabel", "logID" },
	{ "rmCBLabel", "rekenmachine" },
	{ "pijlCBLabel", "Pijl" },
	{ "substitutiesButtonLabel", "substituties" },
	{ "strategieVersieLabel", "Strategieversie" },
	{ "oefenVersieLabel", "Strategie-oefenversie" },
	{ "bordjesVersieLabel", "bordjesmethodeversie" },

	{ "herleidingKeuze_0", "Geen" },
	{ "herleidingKeuze_1", "Veelterm herleid zonder haakjes" },
	{ "herleidingKeuze_2", "Als één macht" },
	{ "herleidingKeuze_3", "Zonder gebroken of negatieve exponenten" },
	{ "herleidingKeuze_4", "Als één breuk" },
	{ "herleidingKeuze_5", "Als één log" },
	{ "herleidingKeuze_6", "Met alleen enkelvoudige log's (bv log(x)+log(3))" },

	{ "feedbackTekst01", "Deze stap bevat correcte en niet correcte onderdelen. Verwijder of vervang de delen die niet correct zijn." },
	{ "feedbackTekst02", "Niet alle oplossingen voldoen aan de oorspronkelijke vergelijking. Verwijder de oplossingen die niet voldoen." },
	{ "feedbackTekst03", "De ongelijkheid is correct opgelost." },
	{ "feedbackTekst04", "De vergelijking is correct opgelost." },
	{ "feedbackTekst05", "Geef de gevraagde afronding." },
	{ "feedbackTekst06", "Geef nu de oplossing(en) van de ongelijkheid." },
	{ "feedbackTekst07", "Er ontbreken oplossingen. Vul aan." },
	{ "feedbackTekst08", "Gebruik geen absoluut strepen ( bv: |x-3| )." },
	{ "feedbackTekst09", "De notatie van de vergelijking of oplossingen is niet juist." },
	{ "feedbackTekst10", "Oplossing is goed, maar nog niet in de juiste vorm." },
	{ "feedbackTekst11", "Deze benadering is een goede oplossing." },
	{ "feedbackTekst12", "Dit antwoord is juist." },
	{ "feedbackTekst13", "Is gelijkwaardig maar heeft nog niet de juiste vorm." },
	{ "feedbackTekst14", "De notatie van het antwoord klopt niet." },
	{ "feedbackTekst15", "Correct antwoord." },
	{ "feedbackTekst16", "Dit is een correcte vergelijking" },
	{ "feedbackTekst17", "Deze vergelijking heeft niet de gevraagde vorm" },

	{ "xVarMessage1", "De onafhankelijk variabele is altijd\n" + "een letter.\n " + "In het geval er met woordformules\n" + " wordt gewerkt, is het eerste teken\n" + "van de woordvariabele altijd een letter." },
	{ "xVarMessage2", "De onafhankelijk variabele kan uit\n" + "slechts één letter bestaan.\n" + "Alleen als de optie \"woordformule\" \n" + "is geselecteerd, dan kan de onafhankelijke\n" + "variabele uit meer letters bestaan." },
	{ "xVarMessage3", "De letter e is gereserveerd als teken \n" + "voor het grondtal van de natuurlijke.\n" + "logaritme.\n" + "Deze letter kan dus niet gebruikt worden\n" + "als naam voor de onafhankelijke variabele." },
	{ "xVarMessage4a", "De tekst:  \"" },
	{ "xVarMessage4b", "\" is gereserveerd voor\n" + "de betreffende wiskundige functie en mag dus\n" + "niet gebruikt worden in de naam van de variabele" },

	{ "gelijkwaardigKnopLabelGR", "Volgende regel" },
	{ "terugKnopLabelGR", "Vorige regel" },

	{ "editorVersieKnopLabel1", "Nieuwe editor versie" },
	{ "editorVersieKnopLabel2", "Oude editor versie" },

	{ "antwoordVakLabel", "antwoordvak" },
	{ "interactieVakLabel", "interactievak" },
	{ "tekstVakLabel", "tekstvak" },
	{ "grafiekComponentLabel", "grafiekcomponent" },

	{ "interactieKeuzeLabel", "Kies soort " },
	{ "okKnopLabel", "OK" },
	{ "annuleerKnopLabel", "Annuleer" },
	{ "breedteLabel", "Breedte:" },
	{ "hoogteLabel", "Hoogte:" },
	{ "volleBreedteLabel", "Volle breedte" },
	{ "popupLabel", "Popup" },

	{ "feedbackCBLabel", "Feedback" },
	{ "uitwCBLabel", "Popup voor uitwerking" },
	{ "casAntwCBLabel", "CAS" },
	{ "eigenOpdrCBLabel", "Eigen opdr." },
	{ "feedbackLabel", "feedback" },
	{ "ideasButtonLabel", "options" },
	{ "substitutiesButtonLabel", "substituties" },
	{ "antwoordmodelButtonLabel", "mogelijk antwoordmodel" },
	{ "formuleInvoerModeCBLabel", "Formule invoer modus" },
	{ "aantalKeuzesLabel", "aantal keuzes" },
	{ "aantalSelectieObjLabel", "Aantal selectie-objecten" },
	{ "randomPosLabel", "Randomiseer posities" },
	{ "meervSelectiesLabel", "Meervoudige selecties mogelijk" },
	{ "checkViaFormuleLabel", "Check m.b.v. een formule" },
	{ "aantalSleepObjLabel", "Aantal sleepobjecten" },
	{ "aantalDoelObjLabel", "Aantal doelobjecten" },
	{ "snapToTargetLabel", "Springt naar doelobject" },
	{ "snapMargeLabel", "Springt met marge" },
	{ "checkVasteDoelenLabel", "Check op vaste doelen voor sleepobjecten" },
	{ "checkWaardeOpDoelLabel", "Check met waarden sleepobjecten" },
	{ "relocateCBLabel", "Springt terug" },
	{ "viewCBLabel", "View" },
	{ "aantalValueObjectenLabel", "Aantal objecten" },
	{ "checkAfzonderlijkLabel", "Check afzonderlijk" },
	{ "checkOpSamenhangLabel", "Check op samenhang" },
	{ "boxMetRand", "Box" },
	{ "keuzeVakKiesLabel", "Kies" },

	{ "vormCBLabel", "Vorm" },
	{ "formuleToolCBLabel", "Formule-invoer editor" },
	{ "goedLabel", "Goed" },
	{ "doorLabel", "Doorgaan" },
	{ "foutLabel", "Fout" },
	{ "halfLabel", "Half" },

	{ "geenOplossingen", "geen oplossingen" },
	{ "allesOplossing", "alles is een oplossing" },
	{ "antwoordModelGeen", "geen" },
	{ "abc", "abc" },

			// TekstVakInteractiePanel
	{ "formuleAntwVakLabel", "formulevak met stappen" },
	{ "vergelijkingAntwVakLabel", "Vergelijkingvak met stappen" },
	{ "simpelFormuleAntwVakLabel", "Simpel formulevak" },
	{ "simpelVergelijkingAntwVakLabel", "Simpel vergelijkingvak" },
	{ "tekstAntwVakLabel", "Tekst-antwoordvak" },
	{ "algebraPijlenLabel", "AlgebraPijlen" },
	{ "blokkenbouwenLabel", "Blokkenbouwen" },
	{ "stroomdiagrammenLabel", "Stroomdiagrammen" },
	{ "grafiekenToolLabel", "Grafiekentool" },
	{ "tekstVakLabelH", "Tekstvak" },
	{ "geogebraIpLabel", "Geogebra 4" },
	{ "geogebra3IpLabel", "Geogebra 3" },
	{ "fruitBalansIpLabel", "Fruitbalans" },
	{ "checkSelectieUnitLabel", "Check selectie unit" },
	{ "checkTekstAntwoordVakLabel", "Check-tekstantwoordvak" },
	{ "keuzeAntwoordVakLabel", "Keuzeantwoordvak" },
	{ "doorzienIpLabel", "Doorzien-component" },
	{ "checkSleepUnitLabel", "CheckSleepUnit" },
	{ "vergrotenIpLabel", "PO Vergroten" },
	{ "vangenIpLabel", "PO Vangen" },
	{ "verknippenIpLabel", "PO Verknippen" },
	{ "geomAlgebra2dIpLabel", "Geom.algebra 2d" },
	{ "geomAlgebra1dIpLabel", "Geom.algebra 1d" },
	{ "normaleVerdelingIpLabel", "Normale verdeling" },
	{ "mp3PlayerIpLabel", "Mp3-player" },
	{ "binominaleVerdelingIpLabel", "Binominale verdeling" },
	{ "getallenlijnIpLabel", "Getallenlijn (sprong)" },
	{ "tekenVeelvlakIpLabel", "Tekenveelvlak" },
	{ "mozaikIpLabel", "Mozaik" },
	{ "veelvlakkenIpLabel", "Veelvlakken" },
	{ "eerlijkVerdelenIpLabel", "PO Eerlijk verdelen" },
	{ "statistiekIpLabel", "[test] Statistische representaties" },
	{ "stroomdiagrammenIpLabel", "[test] Stroomdiagrammen Nieuw" },
	{ "tegelsIpLabel", "Tegels" },
	{ "checkWaardeUnitLabel", "[test] CheckWaardeUnit" },
	{ "omtrekAppletIpLabel", "PO Omtrek applet" },
	{ "algebraExpressiesIpLabel", "[test] Algebra expressies" },
	{ "oppervlakteAlgebraIpLabel", "[test] Oppervlakte-algebra" },
	{ "blokkenProgrammaIpLabel", "[test] Blokkenprogramma" },
	{ "grafieken3DIpLabel", "[test] Grafieken 3D" },

			//InstellingenPanel
	{ "OPT_vermenigvTeken", "Vermenigvuldigingsteken X" },
	{ "OPT_woordformules", "Woordformules " },
	{ "OPT_tweeHoofdletterVars", "Twee-hoofdletter variabelen " },
	{ "OPT_tempoToets", "Tempotoets" },
	{ "OPT_opnieuwKnop", "'Alles opnieuw' mogelijk" },
	{ "OPT_itemOpnieuwKnop", "'Item opnieuw' mogelijk" },
	{ "OPT_checkPerOpdracht", "Check-knop per opdracht" },
	{ "OPT_hoekInGraden", "Hoekberekeningen in graden" },
	{ "OPT_opdrachtBolletjes", "Opdrachtbolletjes" },
	{ "OPT_volgendeKnop", "volgende-knop zichtbaar" },
	{ "OPT_VorigeKnop", "vorige-knop zichtbaar" },
	{ "OPT_paginaIpvOpdracht", "pagina ipv opdracht" },
	{ "OPT_fontFormaat", "formaat" },
	{ "OPT_fontNaam", "Basis lettertype" },
	{ "OPT_tijdsLimiet", "tijdslimiet (sec)" },
	{ "OPT_formTimes", "Formules in Times Roman" },
	{ "OPT_navigatieFormaat", "maat navigatiebalk" },
	{ "OPT_margesLabel", "Marges:" },
	{ "OPT_margeLinksLabel", "Links" },
	{ "OPT_margeRechtsLabel", "Rechts" },
	{ "OPT_margeBovenLabel", "Boven" },
	{ "OPT_margeOnderLabel", "Onder" },
	{ "OPT_fToets", "F-toetsen voor formules" },
	{ "OPT_globalParam", "Globale parameters" },
	{ "OPT_conditionalNav", "Voorwaardelijke navigatie" },
	{ "OPT_conditionalPercLabel", "Perc." },
	{ "OPT_deelOpdr", "Deelopdrachten a,b,c etc" },

			//grafiekenEditPanel
	{ "GEP_varLabel", "Variabelen van de functie" },
	{ "GEP_assenLabel", "Weergave assenstelsel" },
	{ "GEP_grafiekOptiesLabel", "Opties grafiekentool" },

	{ "GEP_varXLabel", "Variabele x-as" },
	{ "GEP_varYLabel", "Variabele y-as" },

	{ "GEP_assenOptie", "Assen zichtbaar" },
	{ "GEP_roosterOptie", "Rooster zichtbaar" },
	{ "GEP_schaalverdelingOptie", "Schaalverdeling" },
	{ "GEP_piOptie", "Weergave Pi" },

	{ "GEP_zoomOptie", "Zoom-optie" },
	{ "GEP_traceOptie", "Trace-optie" },
	{ "GEP_dragOptie", "Drag-Optie" },
	{ "GEP_tekenOptie", "Grafiek-tekentool" },
	{ "GEP_functieEditOptie", "FunctieEditor" },
	{ "GEP_formeleFunctieNotatieOptie", "Formele functienotatie f(x), g(x) enz." },

			//linkEditPanel
	{ "LEP_linkTekst", "Tekst" },
	{ "LEP_url", "URL" },
	{ "LEP_vensterBreedte", "Breedte van het window" },
	{ "LEP_vensterHoogte", "Hoogte van het window" },

			//ImageEditPanel
	{ "IEP_toevoegen", "Toevoegen" },
	{ "IEP_verwijderen", "Verwijderen" },
	{ "IEP_ok", "OK" },
	{ "IEP_cancel", "Annuleer" },

			//TekstVakEditPanel
	{ "TVEP_randZichtbaar", "Rand zichtbaar" },
	{ "TVEP_achtergrondKleurAanwezig", "Achtergrondkleur" },
	{ "TVEP_zwevend", "Zwevend boven de tekst" },
	{ "TVEP_anderFont", "Ander font" },
	{ "TVEP_rondingHoeken", "Ronding hoeken" },
	{ "TVEP_rotatieHoek", "Rotatiehoek" },
	{ "TVEP_centreerHor", "Centreer horizontaal" },
	{ "TVEP_centreerVert", "Centreer vertikaal" },
	{ "TVEP_pasAanH", "Past hoogte aan" },
	{ "TVEP_pasAanB", "Past breedte aan" },
	{ "TVEP_aantalRijen", "Aantal rijen" },
	{ "TVEP_aantalKolommen", "Aantal kolommen" },
	{ "TVEP_tabelRanden", "Tabelranden" },
	{ "TVEP_celMarge", "Marge links" },
	{ "TVEP_bovenMarge", "Marge boven" },
	{ "TVEP_fontType", "Lettertype" },
	{ "TVEP_achtergrondKleur", "Kleur" },
	{ "TVEP_interlinie", "Interlinie" },
	{ "TVEP_cellSpaceColumn", "tussenr." },
	{ "TVEP_cellSpaceRow", "tussenr." },
	{ "TVEP_layoutLabel", "Layout text box" },
	{ "TVEP_gebruikersInteractieLabel", "User interaction" },
	{ "TVEP_selectieObject", "Selectieobject" },
	{ "TVEP_selectieKleur", "Kleur" },
	{ "TVEP_sleepObject", "Sleepobject" },
	{ "TVEP_sleepDoel", "Sleepdoel" },
	{ "TVEP_sleepHandle", "handvat" },
	{ "TVEP_selectieSleepWaarde", "waarde" },
	{ "TVEP_fgKleurKnopLabel", "kleur" },

			//GeogebraEditPanel
	{ "GEP_bewaarOptie", "Bewaaroptie" },
	{ "GEP_alsTool", "Als tool" },
	{ "GEP_rand", "Rand" },
	{ "GEP_resetIcon", "Reset-optie" },
	{ "GEP_checkMetCheckDWO", "m.b.v checkDWO" },
	{ "GEP_checkMetObjecten", "m.b.v objecten" },

			//GetallenLijnSprongEditPanel
	{ "GSEP_minValue", "Kleinste waarde" },
	{ "GSEP_maxValue", "Grootste waarde" },
	{ "GSEP_eenheden", "Eenheden zichtbaar" },
	{ "GSEP_getallen", "Getallen" },
	{ "GSEP_10tallen", "10-tallen zichtbaar" },
	{ "GSEP_5tallen", "5-tallen zichtbaar" },
	{ "GSEP_nul", "Nul" },
	{ "GSEP_pijl", "Pijl zichtbaar" },
	{ "GSEP_pijlTerug", "Pijl terug" },
	{ "GSEP_horizontaal", "Horizontaal" },
	{ "GSEP_eenheid", "Eenheid" },

			//TekstEditorEditPanel
	{ "TEEP_menuBalkOptie", "Menubalk" },
	{ "TEEP_rekenToolOptie", "Calculator" },
	{ "TEEP_grafToolOptie", "Grafiekentool" },

			//Ideas
	{ "ideasTip", "tip" },
	{ "ideasHelp", "help" },
	{ "ideasStap", "stap" },
	{ "ideasLosop", "losop" },
	{ "ideasWordtDan", "wordt dan" },

	{ "algebra.equations.coverup.denominator", "bordjesmethode toepassen (bordje op de noemer)" },
	{ "algebra.equations.coverup.minus-left", "constante termen naar rechts brengen" },
	{ "algebra.equations.coverup.minus-right", "bordjesmethode toepassen" },
	{ "algebra.equations.coverup.negate", "delen door -1" },
	{ "algebra.equations.coverup.numerator", "bordjesmethode toepassen (bordje op de teller)" },
	{ "algebra.equations.coverup.plus", "constante termen naar rechts brengen" },
	{ "algebra.equations.coverup.power", "worteltrekken" },
	{ "algebra.equations.coverup.sqrt", "kwadrateren" },
	{ "algebra.equations.coverup.times", "variabele vrijmaken door beide kanten te delen" },
	{ "algebra.equations.coverup.times-positive", "variabele vrijmaken door beide kanten te delen" },
	{ "algebra.equations.coverup.onevar.minus-left", "constante termen naar rechts brengen door aan beide kanten een getal op te tellen" },
			//{"algebra.equations.coverup.onevar.minus-right"	,""	},
	{ "algebra.equations.coverup.onevar.plus", "constante termen naar rechts brengen door aan beide kanten een getal af te trekken" },

	{ "algebra.equations.linear.distr-times", "haakjes uitwerken" },
	{ "algebra.equations.linear.flip", "de vergelijking omdraaien" },
	{ "algebra.equations.linear.merge", "vereenvoudigen door samenvoegen of uitrekenen" },
			//{"algebra.equations.linear.norm-mixed"		,""	},
			//{"algebra.equations.linear.norm-rational"	,""	},
	{ "algebra.equations.linear.remove-div", "breukvormen verwijderen door te vermenigvuldigen met een getal" },
	{ "algebra.equations.linear.var-left", "termen met variabele naar links brengen" },

	{ "algebra.equations.buggy.cancel-minus", "termen kunnen niet weggestreept worden want het teken verschilt" },
	{ "algebra.equations.buggy.distr-times-denom", "haakjes verkeerd uitgewerkt: een van de termen is een breuk en de factor is vermenigvuldigd met de noemer van de breuk." },
	{ "algebra.equations.buggy.distr-times-plus", "bij haakjes wegwerken is een van de termen niet vermenigvuldigd" },
	{ "algebra.equations.buggy.distr-times-plus-forget", "bij haakjes wegwerken is een van de termen vergeten" },
	{ "algebra.equations.buggy.distr-times-plus-sign", "Let op de tekens bij haakjes wegwerken" },
	{ "algebra.equations.buggy.distr-times-too-many", "bij haakjes wegwerken alleen de termen tussen de haakjes vermenigvuldigen" },
	{ "algebra.equations.buggy.divide-negate", "Let op het teken bij delen" },
	{ "algebra.equations.buggy.divide-numdenom", "breuk omgekeerd. Bedenk door welk getal je moet delen" },
	{ "algebra.equations.buggy.flip-negate-one-side", "Bij teken veranderen moet dit aan beide kanten" },
	{ "algebra.equations.buggy.multiply-one-side", "Bij vermenigvuldigen aan beide kanten is een kant vergeten" },
	{ "algebra.equations.buggy.minus-minus", "Bij haakjes wegwerken: min maal min is plus" },
	{ "algebra.equations.buggy.multiply-forget-one", "Bij vermenigvuldigen aan beide kanten is een van de termen vergeten" },
	{ "algebra.equations.buggy.negate-all", "bij alle termen van teken veranderen is een term vergeten" },
	{ "algebra.equations.buggy.negate-one-side", "bij beide kanten van teken veranderen is een kant vergeten" },
	{ "algebra.equations.buggy.plus", "let op het teken als je een term naar de andere kant brengt" },
	{ "algebra.equations.buggy.priority-times", "let op de voorrangsregels of haakjes" },

	{ "algebra.equations.buggy.abc.minus-4ac", "let op: D=b^2-4ac en geen D=b^2+4ac" },
	{ "algebra.equations.buggy.abc.minus-b", "let op het minteken voor de b: " },
	{ "algebra.equations.buggy.abc.one-solution", "er is nog een tweede oplossing" },
	{ "algebra.equations.buggy.abc.two-a", "delen door 2a en niet a" },
	{ "algebra.equations.buggy.coverup.even-power", "je vergeet de ander (negatieve) wortel" },
	{ "algebra.equations.buggy.coverup.even-power-forget", "Voordat je wortels trekt is eerst nog een andere bewerking nodig" },
	{ "algebra.equations.buggy.coverup.even-power-too-early", "Voordat je wortels trekt is eerst nog een andere bewerking nodig" },
	{ "algebra.equations.buggy.coverup.square-minus", "je kunt geen wortel trekken uit een negatief getal" },
	{ "algebra.equations.buggy.coverup.times-mul", "in plaats van de rechterkant te delen vermenigvuldig je deze" },
	{ "algebra.equations.buggy.coverup.times-with-plus", "als je deelt moet je alle termen delen" },
	{ "algebra.equations.buggy.distr-square", "bij kwadrateren van een tweeterm is het dubbel product vergeten" },
	{ "algebra.equations.buggy.distr-square-forget", "bij kwadrateren van een tweeterm een van de termen vergeten" },
	{ "algebra.equations.buggy.square-multiplication", "term met twee factoren niet juist gekwadrateerd" },
	{ "algebra.equations.buggy.division-by-var-both", "bij delen door een variabele verlies je de oplossing var=0" },
	{ "algebra.equations.buggy.division-by-var-zero", "bij delen door een variabele verlies je de oplossing var=0" },
	{ "", "" },

	{ "algebra.equations.linear.balance.collect", "samenvoegen" },
	{ "algebra.equations.linear.balance.calculate", "berekenen" },
	{ "algebra.equations.linear.balance.div-to-fraction", "schrijf deling als vermenigvuldiging met een breuk" },
	{ "algebra.equations.linear.balance.smart-div", "deel door een gemeenschappelijke factor" },
	{ "algebra.equations.linear.balance.con-right-minus", "van beide kanten {?} aftrekken" },
	{ "algebra.equations.linear.balance.con-left-minus", "van beide kanten {?} aftrekken" },
	{ "algebra.equations.linear.balance.var-right-minus", "van beide kanten {?} aftrekken" },
	{ "algebra.equations.linear.balance.var-left-minus", "van beide kanten {?} aftrekken" },
	{ "algebra.equations.linear.balance.con-right-plus", "aan beide kanten {?} erbij optellen" },
	{ "algebra.equations.linear.balance.con-left-plus", "aan beide kanten {?} erbij optellen" },
	{ "algebra.equations.linear.balance.var-right-plus", "aan beide kanten {?} erbij optellen" },
	{ "algebra.equations.linear.balance.var-left-plus", "aan beide kanten {?} erbij optellen" },
	{ "algebra.equations.linear.balance.distribute", "haakjes uitwerken" },
	{ "algebra.equations.linear.balance.remove-div", "beide kanten vermenigvuldigen met {?}" },
	{ "algebra.equations.linear.balance.scale-to-one", "beide kanten delen door {?}" },
	{ "algebra.equations.linear.balance.negate", "maak beide kanten tegengesteld" },
	{ "algebra.equations.linear.balance.intro-false", "kan niet" },
	{ "algebra.equations.linear.balance.intro-true", "klopt altijd" },
			//{"algebra.equations.linear.balance.var-left"		,"van beide kanten {?} aftrekken"	},

	{ "algebra.equations.quadratic.abc", "de abc-formule toepassen" },
	{ "algebra.equations.quadratic.approx", "een benadering geven" },
	{ "algebra.equations.quadratic.cancel", "termen wegstrepen aan beiden kanten van het =-teken" },
	{ "algebra.equations.quadratic.common-factor", "factor buiten haakjes halen" },
	{ "algebra.equations.quadratic.distr-div", "uitdelen" },
	{ "algebra.equations.quadratic.distr-square", "kwadraat uitwerken" },
	{ "algebra.equations.quadratic.left-square", "schrijf linkerkant als kwadraat" },
	{ "algebra.equations.quadratic.move-left", "alles naar links brengen" },
	{ "algebra.equations.quadratic.nice-factors", "drieterm ontbinden" },
	{ "algebra.equations.quadratic.no-lin", "schrijf als kwadraat=getal" },
	{ "algebra.equations.quadratic.prepare-split", "aanvullen tot een kwadraat" },
	{ "algebra.equations.quadratic.product-zero", "product=0, factoren nul stellen" },
	{ "algebra.equations.quadratic.same-con-factor", "beide kanten delen door een gemeenschappelijke factor" },
	{ "algebra.equations.quadratic.same-factor", "A*B=A*C geeft A=0 of B=C" },
			//{"algebra.equations.quadratic.scale"			,""	},
	{ "algebra.equations.quadratic.simpler-poly", "vereenvoudigen door een factor uitdelen" },
	{ "algebra.equations.quadratic.simpler-sqrt", "wortels vereenvoudigen" },
	{ "algebra.equations.quadratic.square-both", "kwadrateer beide kanten" },

	{ "algebra.equations.polynomial.back-subst", "substitutie terugbrengen" },
	{ "algebra.equations.polynomial.expose-factor", "maak gemeenschappelijk factor zichtbaar" },
	{ "algebra.equations.polynomial.power-factors", "gemeenschappelijke factor x" },
	{ "algebra.equations.polynomial.subst", "substitutie gebruiken" },
			//{"algebra.equations.polynomial.factor-varpower"		,""	},
			//{"algebra.equations.polynomial.simpler-linfactor"	,""	},
	{ "algebra.equations.polynomial.def-power-nat", "schrijf de macht als herhaalde vermenigvuldiging" },

	{ "algebra.equations.rational.check-solution", "controleer de oplossing" },
	{ "algebra.equations.rational.cross-multiply", "kruislings vermenigvuldigen" },
	{ "algebra.equations.rational.division-one", "bij breuk=1 geldt teller = noemer" },
	{ "algebra.equations.rational.division-zero", "bij breuk=0 geldt teller=0 (indien noemer ongelijk nul)" },
	{ "algebra.equations.rational.multiply-one-div", "bemenigvuldig beide kanten met de noemer van de breuk" },
	{ "algebra.equations.rational.same-dividend", "A/B=A/C geeft A=0 of B=C" },
	{ "algebra.equations.rational.same-divisor", "zelfde noemer, stel tellers aan elkaar gelijk" },

	{ "algebra.inequalities.flip-sign", "teken omkeren" },
	{ "algebra.inequalities.give-solution", "geef oplossing van de ongelijkheid" },
	{ "algebra.inequalities.to-equation", "maak er eerst een vergelijking van" },
			//{"algebra.inequalities.trivial"			,""	},

	{ "algebra.manipulation.exponents.add-exponents", "vermenigvuldig de machten door de exponenten op te tellen" },
	{ "algebra.manipulation.exponents.factor-as-power", "schrijf (onderdelen) als macht " },
	{ "algebra.manipulation.exponents.mul-exponents", "een macht tot de macht: vermenigvuldig de exponenten" },
	{ "algebra.manipulation.exponents.reciprocal", "schrijf 1/getal als getal^-1" },
	{ "algebra.manipulation.exponents.simple-add-exponents", "schrijf als macht door exponenten op te tellen" },
	{ "algebra.manipulation.exponents.sub-exponents", "deel de machten door exponenten van elkaar af te trekken" },
	{ "algebra.manipulation.exponents.write-as-power", "schrijf als macht" },
			//{"algebra.manipulation.exponents.calc-power.minus"		,""	},
			//{"algebra.manipulation.exponents.calc-power.plus"		,""	},
	{ "algebra.manipulation.exponents.distr-power", "gebruik: macht van een product is product van de machten" },
			//{"algebra.manipulation.exponents.distr-power-div"		,""	},
			//{"algebra.manipulation.exponents.power-zero"			,""	},
	{ "algebra.manipulation.exponents.reciprocal-inverse", "schrijf de macht getal^-1 als breuk: 1/getal" },
	{ "algebra.manipulation.exponents.write-as-root", "schrijf als wortel" },
	{ "algebra.manipulation.exponents.reciprocal-var", "schrijf 1/macht als nieuwe macht met tegengestelde exponent" },
	{ "algebra.manipulation.exponents.push-negation-out", "minteken buiten de macht brengen (bij oneven exponent)" },
			//{"algebra.manipulation.exponents.power-ratio"			,""	},
	{ "algebra.manipulation.exponents.root", "geef wortel" },

	{ "algebra.manipulation.exponents.equation.equals-one", "macht=1 geeft exponent=0" },
	{ "algebra.manipulation.exponents.equation.same-base", "zelfde grondtal" },
	{ "algebra.manipulation.exponents.equation.approx-power", "benader deze macht of wortel" },
	{ "algebra.manipulation.exponents.equation.common-power", "gemeenschappelijke macht" },
	{ "algebra.manipulation.exponents.equation.greatest-power", "schrijf met grootste gemeenschappelijke macht" },
	{ "algebra.manipulation.exponents.equation.nth-root", "n-de wortel" },

	{ "algebra.manipulation.logarithmic.logarithm", "gebruik log definitie: glog(x)=a geeft x=g^a" },

			//{"arithmetic.operation.rational.power"				,""	},

	{ "calculus.differentiation.deriv-of-poly", "differentieer machtsfunctie" },
	{ "calculus.differentiation.min", "verschilregel toepassen" },
	{ "calculus.differentiation.negate", "minteken naar buiten halen voor differentieren" },
	{ "calculus.differentiation.plus", "somregel toepassen" },
	{ "calculus.differentiation.product", "productregel toepassen" },
	{ "calculus.differentiation.quotient", "quotientregel toepassen" },
	{ "", "" },

	{ "algebra.equations.linear.balance.buggy.addbal1", "addbal1. Je trekt er links {?} vanaf maar rechts tel je {?} erbij op." },
	{ "algebra.equations.linear.balance.buggy.addbal2", "addbal2. Je telt er links {?} bij op maar rechts trek je {?} ervan af." },
	{ "algebra.equations.linear.balance.buggy.addbal3", "addbal3. Je trekt er rechts {?} vanaf, maar links tel je {?} erbij op." },
	{ "algebra.equations.linear.balance.buggy.addbal4", "addbal4. Je telt er rechts {?} bij op, maar links trek je {?} er vanaf." },
	{ "algebra.equations.linear.balance.buggy.addbal5", "addbal5. Je trekt er links {?}  vanaf, maar rechts doe je dat niet" },
	{ "algebra.equations.linear.balance.buggy.addbal6", "addbal6. Je telt er links {?} bij op, maar rechts doe je dat niet" },
	{ "algebra.equations.linear.balance.buggy.addbal7", "addbal7. Je trekt er links {?} vanaf maar rechts tel je {?} erbij op." },
	{ "algebra.equations.linear.balance.buggy.addbal8", "addbal8. Je telt er links {?} bij op maar rechts trek je {?} ervan af." },
	{ "algebra.equations.linear.balance.buggy.addbal9", "addbal9. Je trekt er rechts {?} vanaf, maar links tel je {?} erbij op." },
	{ "algebra.equations.linear.balance.buggy.addbal10", "addbal10. Je telt er rechts {?} bij op, maar links trek je {?} er vanaf." },
	{ "algebra.equations.linear.balance.buggy.addbal11", "addbal11. Je trekt er rechts {?}  vanaf, maar links doe je dat niet" },
	{ "algebra.equations.linear.balance.buggy.addbal12", "addbal12. Je telt er rechts {?} bij op, maar links doe je dat niet" },
	{ "algebra.equations.linear.balance.buggy.addbal13", "addbal13. Je trekt er links {?}  vanaf, maar rechts doe je dat niet" },
	{ "algebra.equations.linear.balance.buggy.addbal14", "addbal14. Je telt er links {?} bij op, maar rechts doe je dat niet" },
	{ "algebra.equations.linear.balance.buggy.addbal15", "addbal15. Je trekt er rechts {?}  vanaf, maar links doe je dat niet" },
	{ "algebra.equations.linear.balance.buggy.addbal16", "addbal16. Je telt er rechts {?} bij op, maar links doe je dat niet" },
	{ "algebra.equations.linear.balance.buggy.flip1", "flip1. links en rechts niet alleen verwisseld, maar aan een kant het teken veranderd" },
	{ "algebra.equations.linear.balance.buggy.misc1", "misc1. rechts heb je er iets van afgetrokken, maar doe je dat links ook?" },
	{ "algebra.equations.linear.balance.buggy.misc2", "misc2. je vermenigvuldigt met een getal, maar niet de hele linkerkant" },
	{ "algebra.equations.linear.balance.buggy.misc3", "misc3. je neemt het tegengestelde, maar links niet volledig" },
	{ "algebra.equations.linear.balance.buggy.misc4", "misc4. je deelt door een getal, maar niet de hele linkerkant" },
	{ "algebra.equations.linear.balance.buggy.mulbal1", "mulbal1. je deelt door {}, maar rechts keer je de deling om" },
	{ "algebra.equations.linear.balance.buggy.mulbal2", "mulbal2. de linkerkant vermenigvuldig je met {1} en de rechterkant met {2}" },
	{ "algebra.equations.linear.balance.buggy.mulbal3", "mulbal3. de linkerkant vermenigvuldig je met {}, de rechterkant niet" },
	{ "algebra.equations.linear.balance.buggy.mulbal4", "mulbal4. de linkerkant deel je door {}, de rechterkant niet" },
	{ "algebra.equations.linear.balance.buggy.mulbal5", "mulbal5. de linkerkant maak je tegengesteld, de rechterkant niet" },
	{ "algebra.equations.linear.balance.buggy.mulbal6", "mulbal6. de ene kant deel je door {}, de andere kant niet" },
	{ "algebra.equations.linear.balance.buggy.multiply1", "multiply1. fout bij het vermenigvuldigen (1)" },
	{ "algebra.equations.linear.balance.buggy.multiply2", "multiply2. fout bij het vermenigvuldigen (2)" },
	{ "algebra.equations.linear.balance.buggy.multiply3", "multiply3. fout bij het vermenigvuldigen, je raakt de min kwijt" },
	{ "algebra.equations.linear.balance.buggy.multiply4", "multiply4. fout bij het vermenigvuldigen, min maal min is plus" },
	{ "algebra.equations.linear.balance.buggy.multiply5", "multiply5. fout bij delen, je deelt door een negatief getal" },
	{ "algebra.equations.linear.balance.buggy.par1", "par1. fout bij haakjes wegwerken, vermenigvuldig beide termen tussen de haakjes (1)" },
	{ "algebra.equations.linear.balance.buggy.par10", "par10. denk aan de voorrangsregels, eerst vermenigvuldigen, dan optellen" },
	{ "algebra.equations.linear.balance.buggy.par11", "par11. minteken niet op de juiste manier binnen de haakjes gebracht" },
	{ "algebra.equations.linear.balance.buggy.par2", "par2. fout bij haakjes wegwerken, vermenigvuldig beide termen tussen de haakjes (2)" },
	{ "algebra.equations.linear.balance.buggy.par4", "par4. fout bij haakjes wegwerken, rekenfout bij vermenigvuldigen (1)" },
	{ "algebra.equations.linear.balance.buggy.par5", "par5. fout bij haakjes wegwerken, vermenigvuldig beide termen tussen de haakjes (3)" },
	{ "algebra.equations.linear.balance.buggy.par6", "par6. fout bij haakjes wegwerken, vermenigvuldig beide termen tussen de haakjes (4)" },
	{ "algebra.equations.linear.balance.buggy.par7", "par7. fout bij haakjes wegwerken, beide termen tussen de haakjes maal -1" },
	{ "algebra.equations.linear.balance.buggy.par8", "par8. fout bij haakjes wegwerken, kijk goed waar de haakjes staan" },
	{ "algebra.equations.linear.balance.buggy.par9", "par9. fout bij haakjes wegwerken, rekenfout bij vermenigvuldigen (2)" },

	};
}
