#Property file
#To prevent stuff on the commandline
connectMode=Local
dbConnectString=jdbc:mysql://localhost/mydb?user=me&password=mysecret
servletConnectString=http://ws.fisme.science.uu.nl/servlet/fi.dwo.server.persistence.DbAccessServlet

