#Property file. It should be located in the working directory of the DWO application.
#connectMode can be 'Local' or 'Servlet'. In case local it requires a 
#dbConnectString properly set otherwise a servletConnectString. 
connectMode=Local
dbConnectString=jdbc:mysql://localhost/mydb?user=me&password=mysecret
servletConnectString=http://ws.fisme.science.uu.nl/servlet/fi.dwo.server.persistence.DbAccessServlet

