# Bij onderstaande instellingen vanaf (2) staat de in te stellen variabele (soms meer dan 1)
# telkens in comment op de laatste regel met in een aantal gevallen de waarde die zij default krijgt
# of een suggestie voor een mogelijke waarde.
# Wil je een variabele gebruiken?
# Verwijder # aan het begin van de regel en vul jouw waarde in.

####(1)
# er is _een_ aanpassing nodig in build.xml (het invullen van de projectnaam); zie aldaar

####(2) class name waarmee het programma wordt gestart
# default is is deze fi.${packagename}.${ant.project.name}
# uncomment als je afwijkt van deze standaard
#main-class: fi.packagename.AntProjectName


####(3) USED_JARS: som namen van jars op in de CODEBASE die nodig zijn bij compilatie
#                  of in runtime
#USED_JARS: mayscript.jar 


####(4) Dos drive letter, is N: op het Fi, wordt toegevoegd aan alle
#       absolute padnamen /home/.....
#	        Bij thuisgebruik veranderen in bijv. C:
#	        + zorgen voor de benodigde C:\home\... structuur
# in comment de default waarde
#dosdrive: N:


####(5) voeg uit de CODEBASE gebruikte class (+evt resource) files toe aan de jar.
# uncomment bijvoorbeeld:
#include.jar= fi/beans/scorm/*.class


####(6) geef jars aan die nodig zijn voor de opbouw van de jar van je project
# default wordt USED_JARS -zie (3)- gebruikt; dit kan te veel zijn waardoor de jar
# groter wordt dan strikt noodzakelijk; voor de executie is dit geen probleem.
# Algemeen gesteld: een jar uit USED_JARS is _niet_ nodig als die standaard
# aanwezig is in de run time environment van je programma.
# Voorbeeld: jsdk.jar voor een Servlet.
# Er is helaas nog geen documentatie over hoe het zit met de beschikbaarheid
# van voor ons gebruikelijke jars in de diverse Java run time environments.
# Vraag Wim.
# Uncomment en vul je jars in:
#extra.jar= ${USED_JARS}


####(7) bij de task .exe maken kun je kiezen voor een .exe met of zonder Java Console
# Uncommment de volgende regel voor een .exe zonder java console
#java.console=/w


####(8) applicatie argumenten voor targets test, testjar, testexe
# in comment de default
#args: language=nl bgcolor=#FFEEFF


####(9) gebruik de interface fi.packagename.VERSION voor versiegegevens.
# Uncomment de volgende regel daarvoor. Default is no.
#use.version=yes

####(10) installeer de scorm package "packagename.zip"  in .../javaclasses/scorm
# Uncomment de volgende regel daarvoor. Default is no.
#use.scorm=yes

####(11) scorm codebase
#uncomment voor Peter Boon's variant van scorm.zip's
#packagename.jar bevindt zich dan in de remote 'jars' subdir.
#scorm.codebase= http://www.fisme.uu.nl/javaclasses/

####(12) installeer en gebruik de obfuscated jar.
# Uncomment de volgende regel daarvoor. Default is no
#use.obfuscate=yes

####(13) welke packages moeten NIET geobfuscate worden.
#yguard en jshrink hebben verschillende syntax. TODO
#dont.obfuscate=fi.*
#dont.obfuscate=fi?

##patches ten behoeve van fi/beans
fi=fi/beans
no.jar=beans
jarfile.uptodate=beans
