#Property file. It should be located in the working directory of the DWO application.
#resourceURLPath should point to a webserver supplying the applet jar files loaded by WiskOpdr.
servletConnectString=https://ws.fisme.science.uu.nl/servlet/dwodsaccess
resourceURLPath=https://ws.fisme.science.uu.nl/dwo/jars/
#servletConnectString=https://spindle.fisme.uu.nl/DWO/DWOServer/xmlrpc
#resourceURLPath=https://ws.fisme.science.uu.nl/dwo/jars/

