#Property file. It should be located in the working directory of the DWO application.
#url on which the context paths jars, resources, rest and xmlrpc should exist. 
#serverUrlPath=/dwo/
#jarUrlPath=jars
#resourceUrlPath=resources
#jarUrlPath=http://cdn.dwo.nl/jars
#resourceUrlPath=http://cdn.dwo.nl/resources
# htttpAuthentication = {BASIC, DIGEST}
httpAuthentication=BASIC
serverUrlPath=/dwo/
jarUrlPath=/dwo/jars
resourceUrlPath=/dwo/resources
#httpAuthentication=BASIC
#serverUrlPath=http://test.dwo.nl/dwo/
#jarUrlPath=https://test.dwo.nl/dwo/jars
#resourceUrlPath=https://test.dwo.nl/dwo/resources
