#Property file. It should be located in the working directory of the DWO application.
#url on which the context paths jars, resources, rest and xmlrpc should exist. 
serverUrlPath=http://localhost/DWO/DWOServer
jarUrlPath=FILE:jars
resourceUrlPath=FILE:resources
# htttpAuthentication = {BASIC, DIGEST}
httpAuthentication=BASIC

