<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>notebook-parent</artifactId>
		<groupId>nl.numworx.notebook</groupId>
		<version>2.5.49-SNAPSHOT</version>
	</parent>
	<artifactId>notebookgwt</artifactId>
	<packaging>gwt-app</packaging>

	<dependencies>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<version>${gwtVersion}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-dev</artifactId>
			<version>${gwtVersion}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<scope>provided</scope>
			<classifier>sources</classifier>
		</dependency>
        <dependency>
            <groupId>org.fusesource.restygwt</groupId>
            <artifactId>restygwt</artifactId>
            <version>${restyVersion}</version>
			<scope>provided</scope>
        </dependency>
        <dependency>
        	<groupId>nl.numworx.notebook</groupId>
        	<artifactId>notebook-common</artifactId>
        	<version>2.5.49-SNAPSHOT</version>
			<scope>provided</scope>
        </dependency>
        <dependency>
        	<groupId>nl.numworx.notebook</groupId>
        	<artifactId>notebook-common</artifactId>
        	<version>2.5.49-SNAPSHOT</version>
        	<classifier>sources</classifier>
			<scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>2.0.1</version>
 			<scope>provided</scope>
       </dependency>
	<!-- https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api -->
		<dependency>
		    <groupId>javax.xml.bind</groupId>
		    <artifactId>jaxb-api</artifactId>
		    <version>2.2.11</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.numworx.notebook</groupId>
			<artifactId>notebook-service</artifactId>
			<version>2.5.49-SNAPSHOT</version>
			<classifier>classes</classifier>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>promise-api</artifactId>
			<version>2.5.49-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>promise-api</artifactId>
			<version>2.5.49-SNAPSHOT</version>
			<classifier>sources</classifier>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>net.ltgt.gwt.maven</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>1.0.1</version>
				<extensions>true</extensions>
				<configuration>
					<classpathScope>compile</classpathScope>
					<moduleName>nl.numworx.notebookgwt.NotebookGWT</moduleName>
					<moduleShortName>notebookgwt</moduleShortName>
					<moduleTemplate>src/main/module${debug}.gwt.xml</moduleTemplate>
					<warDir>${project.build.directory}/${project.build.finalName}</warDir>
					<devmodeWorkDir>${project.build.directory}/${project.build.finalName}</devmodeWorkDir>
					<style>PRETTY</style>
					<startupUrls>
						<startupUrl>NotebookGWT.html</startupUrl>
					</startupUrls>
					<compilerArgs>
						<arg>-generateJsInteropExports</arg>
					</compilerArgs>
					<useCompilerArgsForTests>true</useCompilerArgsForTests>
					<codeserverArgs>
						<arg>-generateJsInteropExports</arg>
					</codeserverArgs>
					<devmodeArgs>
						<arg>-generateJsInteropExports</arg>
					</devmodeArgs>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
					<attachClasses>true</attachClasses>
        			<packagingIncludes>*.css,*gwt/**</packagingIncludes>
				</configuration>
				<executions>
					<execution>
						<id>war</id>
						<phase>compile</phase>
						<goals>
							<goal>war</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin> <!-- attach-sources voor GWT -->
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>2.4</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
        <plugin>
          <groupId>org.eclipse.jetty</groupId>
          <artifactId>jetty-maven-plugin</artifactId>
          <version>9.4.46.v20220331</version>
          <configuration>
            <scanIntervalSeconds>1</scanIntervalSeconds>
           <httpConnector>
          <!--host>localhost</host-->
          <port>8888</port>
        </httpConnector>
            <webApp>
            	<resourceBase>target/${project.build.finalName}</resourceBase>
            </webApp>
        <systemProperties>
            <systemProperty>
                <name>CDNURL</name>
                <value>http://localhost:8082</value>
            </systemProperty>
            <systemProperty>
            	<name>DWO_HUB_TOKEN</name>
            	<value>${token}</value>
            </systemProperty>
        </systemProperties>
              <supportedPackagings>
                <supportedPackaging>gwt-app</supportedPackaging>
              </supportedPackagings>
          </configuration>
        </plugin>
 		</plugins>
	</build>
	<properties>
        <restyVersion>2.2.0</restyVersion>
        <debug />
		<jetty.http.port>8888</jetty.http.port>
		<gwtVersion>2.9.0</gwtVersion>
	</properties>
	<profiles>
		<profile>
			<id>debug</id>
			<properties>
				<debug>Debug</debug>
			</properties>
		
		</profile>
	</profiles>
</project>
