<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>nl.numworx.uploadwidget</groupId>
    <artifactId>uploadwidget-parent</artifactId>
    <version>2.5.49-SNAPSHOT</version>
  </parent>
  <artifactId>uploadwidget-az</artifactId>
  <properties>
    <dbrest.url>http://127.0.0.1/dwo/</dbrest.url> 		
  </properties>
  <dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-sdk-bom</artifactId>
            <version>1.2.10</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-storage-blob</artifactId>
	    <exclusions>
	    	<exclusion>
	    		<groupId>org.slf4j</groupId>
	    		<artifactId>slf4j-api</artifactId>
	    	</exclusion>
	    </exclusions>
	</dependency>
	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-identity</artifactId>
	    <exclusions>
	    	<exclusion>
	    		<groupId>org.slf4j</groupId>
	    		<artifactId>slf4j-api</artifactId>
	    	</exclusion>
	    </exclusions>
	</dependency>
	<dependency>
		<groupId>nl.numworx.uploadwidget</groupId>
		<artifactId>uploadwidget-common</artifactId>
	</dependency>
	<dependency>
		<groupId>nl.numworx.uploadwidget</groupId>
		<artifactId>uploadwidgetgwt</artifactId>
		<version>${project.version}</version>
		<classifier>classes</classifier>
		<exclusions>
			<exclusion>
				<artifactId>uploadwidget-s3</artifactId>
				<groupId>nl.numworx.uploadwidget</groupId>
			</exclusion>			
		</exclusions>
	</dependency>
      <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.1.0</version>
            <scope>provided</scope>
        </dependency>
  </dependencies>
  <build>
	  <plugins>
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
                    <filteringDeploymentDescriptors>true</filteringDeploymentDescriptors>
				<attachClasses>true</attachClasses>
				</configuration>
			</plugin>
	  </plugins>
  </build>
  	<profiles>	 	
	 	<profile>
	 		<id>local</id>
	 		<properties>
    			<dbrest.url>http://localhost:8080/dwo/</dbrest.url> 		
	 		</properties>
	 		<dependencies>
				<dependency> 
				  <groupId>org.slf4j</groupId>
				  <artifactId>slf4j-jdk14</artifactId>
				  <version>1.7.30</version>
				  <scope>runtime</scope>
				  <optional>true</optional>
				</dependency>
			 </dependencies>
	 	</profile>
	</profiles>
  <repositories>
    <repository>
      <id>my-repo1</id>
      <name>your custom repo</name>
      <url>https://repo1.maven.org/maven2/</url>
    </repository>
  </repositories>
  <packaging>war</packaging>
</project>
