<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<%
	String prosody = "https://chat-dev.dwo.nl";
%>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" type="text/css" media="screen" href="https://cdn.conversejs.org/dist/converse.min.css"/>

<script charset="utf-8" src="https://cdn.conversejs.org/dist/converse.min.js"></script>
<title>Prosody IM and Converse.js</title>

</head>
<body>
<noscript>
<h1>Converse.js</h1>
<p>I&apos;m sorry, but this XMPP client application won&apos;t work without JavaScript.</p>
<p>Perhaps you would like to try one of these clients:</p>
<dl>
<dt>Desktop</dt>
<dd><ul>
<li><a href="https://dino.im/">Dino</a></li>
<li><a href="https://gajim.org/">Gajim</a></li>
<li><a href="https://poez.io/">Poezio</a></li>
</ul></dd>
<dt>Mobile</dt>
<dd><ul>
<li><a href="https://github.com/siacs/Conversations">Conversations</a></li>
<li><a href="https://siskin.im/">Siskin</a></li>
<li><a href="https://yaxim.org/">Yaxim</a></li>
</ul></dd>
</dl>
<p><a href="https://xmpp.org/software/clients.html">More clients...</a></p>
</noscript>
<script>if(typeof converse == 'undefined') {
	/*
	 * This shows the content of <noscript> if there's a problem
	 * loading converse.js for some reason
	 */
	var div = document.createElement("div");
	var noscript = document.getElementsByTagName("noscript")[0];
	div.innerHTML = noscript.innerText;
	document.body.appendChild(div);
} else {
	var user = window.parent.user;
	var password = window.parent.password;
	/*
	 * converse.js should have loaded, so we initialize it with
	 * the settings generated by Prosody. This uses sprintf-style
	 * formatting to insert the settigs as a JSON object.
	 */
	converse.initialize({"debug":true
		,"bosh_service_url":"https://chat-dev.dwo.nl/http-bind",
		"default_domain":"chat-dev.dwo.nl",
		"allow_logout":false,"allow_registration":false,
		"show_client_info":false,
		"discover_connection_methods":false,
		"domain_placeholder":"chat-dev.dwo.nl",
		"jid": user + "@chat-dev.dwo.nl",
		"assets_path":"https://cdn.conversejs.org/dist/",
		"view_mode":"fullscreen",
		"websocket_url":"wss://chat-dev.dwo.nl/xmpp-websocket",
		"authentication":"login",
		"password": password});
}
</script>
</body>
</html>