//Source file:
//N:\\transferzone\\intern\\Afstudeerders_basw_thijsk\\April\\Implementatie\\fi\\dwo\\client\\system\\Text_en.java
package fi.dwo.commons.system.text;

import java.util.ListResourceBundle;

import fi.dwo.commons.system.TextMapper;

public class Text_jp extends ListResourceBundle {

    private final Object[][] contents = {
        {TextMapper.USER_GUEST, "ゲスト"},
        {TextMapper.BTN_LOGIN, "ログイン"},
        {TextMapper.BTN_CANCEL, "キャンセル"},
        {TextMapper.BTN_NO, "いいえ"},
        {TextMapper.BTN_OK, "OK"},
        {TextMapper.BTN_YES, "はい"},
        {TextMapper.BTN_CLOSE, "閉じます。"},
        {TextMapper.DLG_CONFIRM, "決定"},
        {TextMapper.DLG_ENTER_INPUT, "入力します。"},
        {TextMapper.DLG_MESSAGE, "メッセージ"},
        {TextMapper.EX_UNKNOWN_ERROR, "内部エラーが起こりました"},
        {TextMapper.EXR_USER_EXISTS, "入力されたユーザー名は既に存在しています"},
        {TextMapper.EXR_USER_EXISTS2, "ユーザー名{0}は既に存在しています"},
        {TextMapper.EXR_WRONG_SECOND_PASSWORD, "入力したパスワードは間違っています"},
        {TextMapper.EXR_WRONG_USERNAME_PASSWORD, "入力したユーザー名とパスワードは存在しません"},
        {TextMapper.EXR_UNKNOWN_SCHOOLGROUP, "使用されていない学校/グループ/パスワードの組み合わせ"},
        {TextMapper.EXR_MANDATORY, "{1}の{0}が入力されていません"},
        {TextMapper.EXR_WRONG_FORMAT, "{1}の{0}は不正な文字が含まれています"},
        {TextMapper.EXR_WRONG_EMAILFORMAT, "{1}の{0}は不正確です"},
        {TextMapper.EXC_CLASS_EXISTS, "入力されたクラスは既に存在しています"},
        {TextMapper.EXS_SCHOOL_EXISTS, "入力された学校用のログインは既に存在しています"},
        {TextMapper.EXL_UNKNOWN_USER, "入力されたユーザー名とパスワードは見つかりません"},
        {TextMapper.EXC_COURSE_EXISTS, "指定されたモジュールは既に存在しています"},
        {TextMapper.EXS_SCO_EXISTS, "指定されたアクティビティは既に存在しています"},
        {TextMapper.EXS_NO_APPLET, "アップレットは見つかりません"},
        {TextMapper.GUI_WAIT_A_MOMENT, "しばらくお待ちください"},
        {TextMapper.GUIW_LOGINDATA, "ログインデータ"},
        {TextMapper.GUIW_USERNAME, "ユーザー名"},
        {TextMapper.GUIW_PASSWORD, "パスワード"},
        {TextMapper.GUIW_WELCOME, "ようこそ"},
        {TextMapper.GUIW_GUESTLOGIN, "ゲストとしてログイン"},
        {TextMapper.GUIW_REGISTER, "登録する"},
        {TextMapper.GUIW_MSG_WORK_NOT_SAVE, "保存されていません"},
        {TextMapper.GUIW_MSG_REGISTER_NEW, "新しいメンバーとして登録します。"},
        {TextMapper.GUIW_BTN_GUESTLOGIN, "ゲストとしてログイン"},
        {TextMapper.GUIW_BTN_LOGIN, "ログイン"},
        {TextMapper.GUIW_BTN_REGISTER, "登録します。"},
        {TextMapper.GUIW_ERR_LOGIN, "ログインエラー"},
        {TextMapper.GUIR_REGISTER, "登録します。"},
        {TextMapper.GUIR_REGISTERINFO, "新しいユーザー登録"},
        {TextMapper.GUIR_PERSONALINFO, "個人情報"},
        {TextMapper.GUIR_SCHOOLINFO, "学校情報"},
        {TextMapper.GUIR_USERNAME, "ユーザー名"},
        {TextMapper.GUIR_PASSWORD, "パスワード"},
        {TextMapper.GUIR_RE_PASSWORD, "パスワードを確認します。"},
        {TextMapper.GUIR_FIRSTNAME, "名前"},
        {TextMapper.GUIR_MIDDLENAME, "ミドルネーム"},
        {TextMapper.GUIR_LASTNAME, "名字"},
        {TextMapper.GUIR_EMAIL, "E-mailアドレス"},
        {TextMapper.GUIR_SCHOOLLOGIN, "学校用のログイン"},
        {TextMapper.GUIR_SCHOOLGROUP, "はい、そうです"},
        {TextMapper.GUIR_SCHOOLPASSWORD, "パスワード"},
        {TextMapper.GUIR_BTN_REGISTER, "登録します。"},
        {TextMapper.GUIR_BTN_RESET, "リセット"},
        {TextMapper.GUIR_BTN_BACK, "モジュールに戻ります。"},
        {TextMapper.GUIR_MSG_PROVIDED_SCHOOL, "学校から提供されたデータ"},
        {TextMapper.GUIR_OPT_SELECT_GROUP, "選択します。"},
        {TextMapper.GUIR_OPT_STUDENT, "生徒"},
        {TextMapper.GUIR_OPT_TEACHER, "先生"},
        {TextMapper.GUIR_OPT_ADMIN, "管理人"},
        {TextMapper.GUIR_OPT_SCHOOLADMIN, "学校の管理人"},
        {TextMapper.GUIR_OPT_SCHOOLCODE, "キーコード"},
        {TextMapper.GUIR_ERR_REGISTER, "エラーが起こりました"},
        {TextMapper.GUIR_MSG_REGISTERED, "登録に成功しました"},
        {TextMapper.GUIM_DWO_FULL, ""},
        {TextMapper.GUIM_DWO_SHORT, ""},
        {TextMapper.GUIM_FI_NAME, "フロイデンタール"},
        {TextMapper.GUIM_MAIN_MENU, "モジュール"},
        {TextMapper.GUIL_LOGGED_IN_AS, "として記録されています"},
        {TextMapper.GUIL_NOT_LOGGED_IN, "として記録されていません"},
        {TextMapper.GUIL_BTN_LOGIN, "ログイン"},
        {TextMapper.GUIL_BTN_LOGOFF, "ログアウト"},
        {TextMapper.GUIMNU_MAIN_MENU, "モジュール"},
        {TextMapper.GUIMNU_MY_PROFILE, "マイプロフィール"},
        {TextMapper.GUIMNU_STUDENT_IN_CLASS, "クラスの生徒"},
        {TextMapper.GUIMNU_STUDENT_NO_CLASS_0, "まだクラスの生徒ではありません"},
        {TextMapper.GUIMNU_STUDENT_NO_CLASS_1, "クラスメンバー.  "},
        {TextMapper.GUIMNU_STUDENT_NO_CLASS_2, "参加します。"},
        {TextMapper.GUIMNU_STUDENT_NO_CLASS_3, "\"My profile\" and "},
        {TextMapper.GUIMNU_STUDENT_NO_CLASS_4, "クラスを選択します。"},
        {TextMapper.GUIMNU_CLASS_RESULTS, "クラスの結果"},
        {TextMapper.GUIMNU_RESULTS, "結果を見ます。"},
        {TextMapper.GUIMNU_CLASS_MANAGEMENT, "クラスマネージメント"},
        {TextMapper.GUIMNU_SCHOOL_MANAGEMENT, "学校マネージメント"},
        {TextMapper.GUIMNU_COURSE_MANAGEMENT, "モジュールマネージメント"},
        {TextMapper.GUIMNU_MSG_ADD_CLASS, "新しいクラスの名前"},
        {TextMapper.GUIMNU_MSG_ADD_CLASS_TITLE, "新しいクラスを加えます。"},
        {TextMapper.GUIMNU_MSG_ADD_SCHOOL, "新しい学校の名前"},
        {TextMapper.GUIMNU_MSG_ADD_SCHOOL_TITLE, "新しい学校を加えます。"},
        {TextMapper.GUIMNU_USERS_SCHOOL, "学校ユーザー"},
        {TextMapper.GUIMNU_CLASSES_SCHOOL, "学校のクラス"},
        {TextMapper.GUIMNU_FEATURES_SCHOOLADMIN, "主な学校管理人"},
        {TextMapper.GUIUMP_MANAGE_USERS, "管理ユーザー"},
        {TextMapper.GUIUMP_REMOVE_FROM_SCHOOL, "学校から削除します。"},
        {TextMapper.GUIUMP_REMOVE_COMPLETE, "完全にアカウントを削除します。"},
        {TextMapper.GUIUMP_ADD_STUDENTS, "新しい生徒を加えます。"},
        {TextMapper.GUIUMP_ADD_TEACHERS, "新しい先生を加えます。"},
        {TextMapper.GUIUMP_IMPORT_CLIPBOARD, "クリップボードからインポートします。"},
        {TextMapper.GUIUMP_MAKE_ACCOUNTS, "アカウントを作ります。"},
        {TextMapper.GUIUMP_EXTRA_ROW, "列の追加"},
        {TextMapper.GUICO_HEADER, "モジュール"},
        {TextMapper.GUICO_SCO_LIST_TITLE, "アクティビティー"},
        {TextMapper.GUIP_MY_PROFILE, "マイプロフィール"},
        {TextMapper.GUIP_REGISTERINFO, "情報登録"},
        {TextMapper.GUIP_PERSONALINFO, "個人情報"},
        {TextMapper.GUIP_SCHOOLINFO, "学校情報"},
        {TextMapper.GUIP_USERNAME, "ユーザー名"},
        {TextMapper.GUIP_OLD_PASSWORD, "現在のパスワード"},
        {TextMapper.GUIP_PASSWORD, "新しいパスワード"},
        {TextMapper.GUIP_RE_PASSWORD, "パスワードを確認します。"},
        {TextMapper.GUIP_FIRSTNAME, "名前"},
        {TextMapper.GUIP_MIDDLENAME, "ミドルネーム"},
        {TextMapper.GUIP_LASTNAME, "名字"},
        {TextMapper.GUIP_EMAIL, " Eメールアドレス"},
        {TextMapper.GUIP_SCHOOLLOGIN, "学校用のログイン"},
        {TextMapper.GUIP_SCHOOLGROUP, "はい、そうです"},
        {TextMapper.GUIP_SCHOOLPASSWORD, "パスワード"},
        {TextMapper.GUIP_CLASS, "クラス"},
        {TextMapper.GUIP_BTN_SAVE, "保存"},
        {TextMapper.GUIP_BTN_RESET, "リセット"},
        {TextMapper.GUIP_BTN_DELETE_PROFILE, "プロフィールを削除します"},
        {TextMapper.GUIP_MSG_PROVIDED_SCHOOL, "学校から提供されたデータ"},
        {TextMapper.GUIP_ERR_CHANGE, "エラーが起こりました"},
        {TextMapper.GUIP_OPT_SELECT_GROUP, "選択します"},
        {TextMapper.GUIP_CONFIRM_REMOVE_USER, "本当にあなたのアカウントを消しますか"},
        {TextMapper.GUIP_CONFIRM_REMOVE_USER_TITLE, "アカウントを削除します"},
        {TextMapper.GUIP_MSG_PROFILE_CHANGED, "あなたのアカウントは無事変更されました"},
        {TextMapper.GUIPT_SCHOOL, "学校"},
        {TextMapper.GUIPT_TEACHER_FROM_CLASS, "クラスの先生"},
        {TextMapper.GUIPT_BTN_ADD_CLASS, "クラスを加えます"},
        {TextMapper.GUIS_STUDENTS, "生徒"},
        {TextMapper.GUIS_TEACHERS, "先生"},
        {TextMapper.GUIS_SCHOOL_MANAGEMENT, "学校経営"},
        {TextMapper.GUIS_TLTP_DELETE_SCHOOL, "学校｛0｝を削除します"},
        {TextMapper.GUIS_TLTP_EDIT_SCHOOL, "学校名を編集します"},
        {TextMapper.GUIS_TLTP_USERS_SCHOOL, "｛0｝の生徒"},
        {TextMapper.GUIS_ADD_SCHOOL, "学校を追加します"},
        {TextMapper.GUIS_DELETE_SCHOOL, "学校を削除します"},
        {TextMapper.GUIS_RENAME_SCHOOL, "学校名を編集します"},
        {TextMapper.GUIS_MSG_RENAME_SCHOOL, "新しい学校名を入力します"},
        {TextMapper.GUIS_MSG_DELETE_SCHOOL, "この学校を削除しますか"},
        {TextMapper.GUIS_SCHOOL_NOT_EMPTY, "この学校にはユーザーがいます。本当にこの学校を削除しますか。"},
        {TextMapper.GUIS_SCHOOL_NOT_EMPTY_TITLE, "この学校はユーザーを持ちます"},
        {TextMapper.GUIS_MSG_DELETE_STUDENT, "本当にこの学校から｛0｝を削除したいですか。"},
        {TextMapper.GUIS_DELETE_STUDENT, "この学校から生徒を消します"},
        {TextMapper.GUIS_NO_STUDENTS, "スクール｛0｝は生徒を含みません"},
        {TextMapper.GUIC_STUDENTS, "生徒"},
        {TextMapper.GUIC_CLASS_MANAGEMENT, "クラス管理"},
        {TextMapper.GUIC_TLTP_DELETE_CLASS, "クラス｛0｝を削除します "},
        {TextMapper.GUIC_TLTP_EDIT_CLASS, "クラス名を変更します"},
        {TextMapper.GUIC_TLTP_USERS_CLASS, "クラス｛0｝の生徒"},
        ////peter
        {TextMapper.GUIC_TLTP_ASSIGN_CLASS, "モジュールにクラス｛0｝を割り当てます"},
        ////peter

        {TextMapper.GUIC_STUDENTS, "生徒"},
        {TextMapper.GUIC_ADD_CLASS, "クラスを創造します"},
        {TextMapper.GUIC_DELETE_CLASS, "クラスを削除します"},
        {TextMapper.GUIC_RENAME_CLASS, "クラスの名前を変更します"},
        {TextMapper.GUIC_MSG_RENAME_CLASS, "クラスの新しい名前"},
        {TextMapper.GUIC_MSG_DELETE_CLASS, "本当にこのクラスを削除したいですか"},
        {TextMapper.GUIC_CLASS_NOT_EMPTY, "何人かの生徒はこのクラスに含まれています。本当にこのクラスを削除したいですか"},
        {TextMapper.GUIC_CLASS_NOT_EMPTY_TITLE, "何人かの生徒はクラスに含まれます。"},
        {TextMapper.GUIC_MSG_DELETE_STUDENT, "本当にこのクラスから｛0｝を削除したいですか。"},
        {TextMapper.GUIC_DELETE_STUDENT, "このクラスから生徒を削除します"},
        {TextMapper.GUIC_NO_STUDENTS, "クラス｛0｝には生徒がいません"},
        {TextMapper.GUIRS_RESULTS, "結果"},
        {TextMapper.GUIRS_NO_RESULTS, "答えが見つかりません"},
        {TextMapper.GUIRS_BTN_SELECT_COURSES, "モジュールを選択します"},
        {TextMapper.GUIRS_BTN_COPY_TO_CLIPBOARD, "クリップボードにコピーします"},
        {TextMapper.GUIRS_TLTP_SELECT_COURSES, "モジュールを選択します"},
        {TextMapper.GUIRS_TLTP_ZOOM, "｛0｝からの結果"},
        {TextMapper.GUIRS_TLTP_ZOOM_ORDER, "｛0｝を分類します"},
        {TextMapper.GUIRS_TLTP_RESULT_SCORE_BUTTON, "｛1｝の活動｛0｝の結果を示します"},
        {TextMapper.GUIRSDLG_MSG, "｛1｝のために｛0｝の結果を全て削除します"},
        {TextMapper.UG_RESULTS_OF_STUDENT, "｛1｝の｛0｝の活動結果"},
        {TextMapper.GUISC_TITLE, "モジュールを選択します"},
        {TextMapper.GUISC_BTN_SELECT_ALL, "すべて選択します"},
        {TextMapper.GUISC_BTN_DESELECT_ALL, "すべてを非選択状態にします"},
        {TextMapper.UG_CLASSES, "クラス"},
        {TextMapper.UG_STUDENTS_OF_CLASS, "｛0｝の生徒"},
        {TextMapper.UG_USER_TITLE, " 生徒"},
        {TextMapper.UG_CLASS_TITLE, "クラス"},
        {TextMapper.UG_CLASS_CHILD, "｛0｝の生徒"},
        {TextMapper.UG_CLASS_ORDER_ASC, "（A-Z）のクラス名"},
        {TextMapper.UG_CLASS_ORDER_DESC, "（Z-A）のクラス名"},
        {TextMapper.UG_USER_PARENT, "クラス"},
        {TextMapper.UG_USER_ORDER_ASC, "A-Zの姓"},
        {TextMapper.UG_USER_ORDER_DESC, "Z-Aの姓"},
        {TextMapper.LG_COURSES, "モジュール"},
        {TextMapper.LG_SCOS_OF_COURSE, "｛0｝の活動"},
        {TextMapper.LG_COURSE_CHILD, "｛0｝の活動"},
        {TextMapper.LG_COURSE_ORDER_ASC, "（0-100）の結果"},
        {TextMapper.LG_COURSE_ORDER_DESC, "（100-0）の結果"},
        {TextMapper.LG_SCO_PARENT, "モジュール"},
        {TextMapper.LG_SCO_ORDER_ASC, "（0-100）の結果"},
        {TextMapper.LG_SCO_ORDER_DESC, "（100-0）の結果"},
        {TextMapper.LG_SCO_NAME, "｛0｝の活動"},
        {TextMapper.GUIC_ADD_COURSE, "新しいモジュールを加えます"},
        {TextMapper.GUIC_ADD_MAP, "新たなフォルダを加えます"},
        {TextMapper.GUIC_COURSE_MANAGEMENT, "モジュールの管理"},
        {TextMapper.GUIC_TLTP_DELETE_COURSE, "モジュール{0}の削除"},
        {TextMapper.GUIC_TLTP_DELETE_MAP, "フォルダ{0}の削除"},
        {TextMapper.GUIC_TLTP_EDIT_COURSE, "モジュールの編集"},
        {TextMapper.GUIC_TLTP_SCO_COURSE, "アクティブの管理"},
        {TextMapper.GUICDLG_COURSE_NAME, "モジュール名"},
        {TextMapper.GUICDLG_MAP_NAME, "フォルダ名"},
        {TextMapper.GUICDLG_COURSE_DESCRIPTION, "説明"},
        {TextMapper.GUICDLG_TTL_ADD_COURSE, "新規モジュールの追加"},
        {TextMapper.GUICDLG_TTL_EDIT_COURSE, "モジュールの編集"},
        {TextMapper.GUIC_TLTP_EDIT_MAP, "フォルダの編集"},
        {TextMapper.GUIC_NO_COURSES, "表示できるモジュールが見つかりません"},
        {TextMapper.GUIC_COURSE_SHARE, "共有モジュール"},
        {TextMapper.GUIC_MSG_COURSE_DELETE, " 選択されたモジュールは現在使用中です。\nこのモジュールを削除すると\nen今までのアクティブの結果も削除されます\n \nモジュールを削除してもよろしいですか？ "},
        {TextMapper.GUIC_MSG_COURSE_DELETE_NO_SCO, "モジュールを削除してもよろしいですか？ "},
        {TextMapper.GUIC_MSG_TTL_COURSE_DELETE, "モジュールの削除"},
        {TextMapper.GUIS_ADD_SCO, "新規アクティブの追加"},
        {TextMapper.GUIS_LBL_SCO_OF_COURSE, "モジュール{0}のアクティブ"},
        {TextMapper.GUIS_SCO_MANAGEMENT, "アクティブの管理"},
        {TextMapper.GUIS_SHOW_SCORE, "生徒が結果を見る"},
        {TextMapper.GUIS_TLTP_DELETE_SCO, "アクティブの削除"},
        {TextMapper.GUIS_TLTP_EDIT_SCO, "アクティブ名の編集"},
        {TextMapper.GUIS_TLTP_PARAMETERS_SCO, "アクティブの編集"},
        {TextMapper.GUIS_TLTP_COURSE_SCO, "モジュールに戻る"},
        {TextMapper.GUISDLG_SCO_NAME, "アクティブ名"},
        {TextMapper.GUISDLG_SCO_DESCRIPTION, "アクティブの説明"},
        {TextMapper.GUISDLG_TTL_ADD_SCO, "新規アクティブを追加"},
        {TextMapper.GUISDLG_TTL_EDIT_SCO, "アクティブの編集"},
        {TextMapper.GUIS_MSG_SCO_DELETE, "アクティブを削除すると、\nenこれまでのアクティブの結果も削除されます。\n \nアクティブを削除してよろしいですか？ "},
        {TextMapper.GUIS_MSG_TTL_SCO_DELETE, "アクティブの削除"},
        {TextMapper.GUIS_NO_SCOS, "モジュール{0}にはアクティブが見つかりません。"},
        {TextMapper.GUIS_LOAD_LOGO, "アイコン{0}のロード"},
        {TextMapper.GUISDLG_BTN_ADD_SCO, "追加"},
        {TextMapper.GUISDLG_BTN_PREVIEW_SCO, "アクティブのプレビュー"},
        {TextMapper.GUISDLG_MSG_SELECT_SCO, "アクティブの選択"},
        {TextMapper.GUISDLG_MSG_NO_APPLETS, "追加できるアクティブが見つかりません"},
        {TextMapper.GUISDLG_SHOW, "表示する"},
        {TextMapper.GUISDLG_ALL, "すべて"},
        {TextMapper.GUISDLG_MSG_NO_SELECTION, "アクティブが選択されていません"},
        {TextMapper.GUISDLG_RB_STANDARD_SCOS, "標準的なアクティブ"},
        {TextMapper.GUISDLG_RB_OWN_SCOS, "自分のアクティブ"},
        {TextMapper.GUIPA_BTN_PREVIEW, "アクティブのプレビュー"},
        {TextMapper.GUIPA_BTN_SAVE, "保存"},
        {TextMapper.GUIPA_BTN_RESET, "リセット"},
        {TextMapper.GUIPA_BTN_CANCEL, "閉じる"},
        {TextMapper.GUIPA_SCO_EDIT, "アクティブの編集"},
        {TextMapper.GUIPA_NO_PARAMS, "このアクティブは変更できません。"},
        {TextMapper.GUIPA_DLG_TTL, "アクティブ{0}の編集モード"},
        {TextMapper.GUIPA_MSG_PARAM_SAVE, "新しい配置を保存すると\n古いアイテムは削除されます。\n \nこの配置を保存してもよろしいですか？ "},
        {TextMapper.GUIPA_MSG_TTL_PARAM_SAVE, "配置の保存"},
        {TextMapper.GUIPA_PARAMS_OF_SCO, "パラメーター({0}) "},
        {" cut", "切り取り"},
        {"copy", "コピー"},
        {" paste", "貼り付け"},
        {" delete", "削除"},
        {" edit", "編集"},
        {" rename", "名前の変更"},
        {TextMapper.GUIA_INSERT_SCOS, "バックアップからアクティブを挿入する"},
        {TextMapper.GUIH_STOP_EDIT, "編集を中止"},
        {TextMapper.GUIH_EDIT, "編集"},
        {"Alle modules", "すべてのモジュール"},
        {" Standaard DWO modules", "標準DMOモジュール"},
        {"Nieuwe Modulemap", "新規モジュールフォルダ"},
        // classadminpanel
        {" Klassen toewijzen", "クラスを割り当てる"},
        {"Klas", "クラス"},
        {"Docent", "先生"},
        {"Verwijder", "削除"},
        // classpanel 
        {"boomstructuur?", "ツリーを見る？ "},
        // select courses dialog
        {" Leerlinggegevens verwijderen", "生徒の結果を削除する"},
        {"Wilt u alle resultaten van {0} voor {1} verwijderen?", "{0}から{1}の結果をすべて削除しますか？"},
        {"soort", "種類"},
        {"vanaf", "から"},
        {"tot aan", "まで"},
        {"tot", "まで"},
        {"Ll ggvns", "結果"},
        {"normaal", "ふつう"},
        {"afgeschermd", "確保"},
        {"Geef tijdstip {0}", "データと時間の設定\"{0}\""},
        {" dag: ", " データ"},
        {"tijd:", "時間"},
        // resultLoogger 
        {"Overzicht Logs", "ログの概要"},
        {" deel-scores", "部分的なスコア"},
        {"tijdsduur", "期限"},
        // default partial score
        {"resultaat", "結果"},
        //importexportdialog
        {"Kopiëer modules", "モジュールのコピー"},
        {"Toestaan", "許可"},
        {" Modules beschikbaar stellen", "モジュールの提供"},
        {"モModules opvragen", "モジュールのリクエスト"},
        {" Delen met", "共有する"},
        {" Alle scholen", "すべての学校All "},
        {"Scholen", "学校"},
        {"toepassen", "適用"},
        {TextMapper.GUIEID_MSG1, "学校の選択<html>(1) <br>"
            + "(2)表示済みのモジュールのプレビュー<br>"
            + "(3) あなたの学校で使用するいくつかのモジュールを選択する。<br><br>"
            + "選択されたモジュールはあなたのモジュールビューにコピーされました。<br>"
            + "あなたの学校で使用することができます。"},
        {TextMapper.GUIEID_MSG2, "<html>私は共有での参加とリストの学校として見られることを希望します。"},
        {TextMapper.GUIEID_MSG3, "<html>(1)モジュールの選択<br>⑵学校の選択<br><br>選択されたモジュールは利用されます<br>選択された学校で<html>"},
        {"leerlingen ook", "生徒"},
        {TextMapper.GUIUMP_REMOVE_CLASS, "すべての生徒を{0}から削除する"},
        {TextMapper.GUIUMP_ALL_STUDENTS, "すべての生徒"},
        {TextMapper.GUIC_SETTINGS, "{0}の配置"},
        {TextMapper.GUIH_SETTINGS, "学校の配置"},
        {TextMapper.GUIC_SETTINGS_STUDENT, "生徒が彼ら自身のクラスを選択する"},
        {TextMapper.GUIC_SETTINGS_TEACHER, "先生が自身の生徒がいるクラスを選択する"},
        {TextMapper.GUIC_SETTINGS_MODULE, "先生はモジュールの変更を許可される"},
        // google translate...
        {TextMapper.GUICDLG_LICENCE, "{0}の加入者がいっぱいです!\nこれ以上新規加入者を追加できません。\n学校のDME担当者に連絡をとってください。"},
        {TextMapper.DWOAPPLET_EXISTS, "DMEは既に存在します。"},};

    public Text_jp() {

    }

    /**
     * @return Object[][]
     */
    public Object[][] getContents() {
        return contents;
    }
}
