/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.dwo.dwojapplet.gui.panels;

import fi.dwo.commons.exceptions.LoginException;
import fi.dwo.commons.persistence.entities.PersistentUser;
import fi.dwo.dwojapplet.domain.DwoHelper;
import fi.dwo.dwojapplet.gui.GuiCreator;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author G.A.J. van der Plas
 */
public class JPanelCommonRoleOptions extends javax.swing.JPanel {
    private static final Logger log = Logger.getLogger(JPanelCommonRoleOptions.class.getName());
    private JPanelSchoolsRolesAndClassesProperties prop = new JPanelSchoolsRolesAndClassesProperties();

    /**
     * Creates new form JPanelSchoolAdmin
     */
    public JPanelCommonRoleOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonSwitchToProfile = new javax.swing.JButton();

        jButton1.setText("Profiel Verwijderen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonSwitchToProfile.setText("Naar profiel Switchen");
        jButtonSwitchToProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSwitchToProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSwitchToProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonSwitchToProfile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSwitchToProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSwitchToProfileActionPerformed
        //Update current Role
        
        //relogin
        PersistentUser user = DwoHelper.getCurrentUser();
        GuiCreator.instance().clearCurrentUserData();
        try {
            GuiCreator.instance().login(user.getUsername(), user.getPasswd());
        } catch (LoginException ex) {
            log.log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jButtonSwitchToProfileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO remove profile. After a popup.
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSwitchToProfile;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the prop
     */
    public JPanelSchoolsRolesAndClassesProperties getProp() {
        return prop;
    }

    /**
     * @param prop the prop to set
     */
    public void setProp(JPanelSchoolsRolesAndClassesProperties prop) {
        this.prop = prop;
    }
}
