package fi.dwo.dwojapplet.gui.panels;

import fi.dwo.commons.system.TextMapper;
import fi.dwo.dwojapplet.gui.GuiConstants;
import java.awt.Dimension;

/**
 *
 * @author G.A.J. van der Plas
 */
public class JPanelMyProfile extends javax.swing.JPanel  {

    /**
     * Creates new form JPaneMylProfile
     */
    public JPanelMyProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneProfile = new javax.swing.JTabbedPane();
        jPanelAcountData1 = new fi.dwo.dwojapplet.gui.panels.JPanelAcountData();
        jPanelSchoolsAndClasses = new fi.dwo.dwojapplet.gui.panels.JPanelSchoolsAndRoles();

        setBackground(GuiConstants.MAIN_BACKGROUND);
        setPreferredSize(new Dimension(GuiConstants.CENTER_WIDTH,GuiConstants.CENTER_HEIGHT));

        jTabbedPaneProfile.setBackground(GuiConstants.MAIN_BACKGROUND);
        jTabbedPaneProfile.setName("Profile panel"); // NOI18N
        jTabbedPaneProfile.setPreferredSize(new java.awt.Dimension(32767, 32767));
        jTabbedPaneProfile.setRequestFocusEnabled(false);
        jTabbedPaneProfile.addTab(TextMapper.getText(TextMapper.GUIP_ACCOUNTANDCONTACTINFO)
            , jPanelAcountData1);

        jPanelSchoolsAndClasses.setBackground(jPanelSchoolsAndClasses.getBackground());
        jTabbedPaneProfile.addTab("Schools and Classes", jPanelSchoolsAndClasses);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fi.dwo.dwojapplet.gui.panels.JPanelAcountData jPanelAcountData1;
    private fi.dwo.dwojapplet.gui.panels.JPanelSchoolsAndRoles jPanelSchoolsAndClasses;
    private javax.swing.JTabbedPane jTabbedPaneProfile;
    // End of variables declaration//GEN-END:variables

}
