/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.dwo.dwojapplet.gui.panels;

import fi.dwo.commons.system.MD5;
import fi.dwo.commons.system.TextMapper;
import fi.dwo.dwojapplet.gui.GuiConstants;
import java.awt.Color;
import java.util.logging.Logger;

/**
 * Panel to update the account data.
 *
 * @author G.A.J. van der Plas
 */
public class JPanelAcountData extends javax.swing.JPanel {

    private static final Logger log = Logger.getLogger(JPanelAcountData.class.getName());

    private JPanelAccountDataProperties prop = new JPanelAccountDataProperties();
    private Color originalBackground;

    /**
     * Creates new form NewJPanelAcountData
     */
    public JPanelAcountData() {
        initComponents();
        try{prop.init();

//        jLabelTitle = new javax.swing.JLabel();
//        jLabelUserName = new javax.swing.JLabel();
//        jLabelPassword = new javax.swing.JLabel();
//        jLabelNewPassword = new javax.swing.JLabel();
//        jLabelConfirmPassword = new javax.swing.JLabel();
//        jLabelGivenName.setText();
//        jLabelFamilyName = new javax.swing.JLabel();
//        jLabelInsertion = new javax.swing.JLabel();
//        jLabelEmail = new javax.swing.JLabel();
        jTextFieldUserName.setText(prop.getUser().getUsername());
        jPasswordFieldConfirmPassword.setText("");
        jPasswordFieldNewPassword.setText("");
        jPasswordFieldPassword.setText("");
        jTextFieldInsertion.setText(prop.getUser().getMiddlename());
        jTextFieldGivenName.setText(prop.getUser().getFirstname());
        jTextFieldFamilyName.setText(prop.getUser().getLastname());
        jTextFieldEmail.setText(prop.getUser().getEmail());
//        jButtonEditAndCancel.setText(user.getUsername());
//        jButtonUpdate.setText(user.getUsername());
       }catch(Exception e){
           
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPersonalData = new javax.swing.JPanel();
        jLabelUserName = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jLabelNewPassword = new javax.swing.JLabel();
        jLabelConfirmPassword = new javax.swing.JLabel();
        jLabelFamilyName = new javax.swing.JLabel();
        jTextFieldInsertion = new javax.swing.JTextField();
        jLabelGivenName = new javax.swing.JLabel();
        jLabelInsertion = new javax.swing.JLabel();
        jTextFieldGivenName = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldFamilyName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonEditAndCancel = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jPasswordFieldNewPassword = new javax.swing.JPasswordField();
        jPasswordFieldConfirmPassword = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(320, 320));

        jPanelPersonalData.setBackground(GuiConstants.MAIN_BACKGROUND);
        jPanelPersonalData.setMinimumSize(new java.awt.Dimension(550, 353));
        jPanelPersonalData.setPreferredSize(new java.awt.Dimension(550, 353));

        jLabelUserName.setText(TextMapper.getText(TextMapper.GUIP_USERNAME));

        jTextFieldUserName.setEditable(false);
        jTextFieldUserName.setMinimumSize(new java.awt.Dimension(320, 320));

        jLabelPassword.setText(TextMapper.getText(TextMapper.GUIP_OLD_PASSWORD)
        );

        jLabelNewPassword.setText(TextMapper.getText(TextMapper.GUIP_PASSWORD));
        jLabelNewPassword.setEnabled(false);

        jLabelConfirmPassword.setText(TextMapper.getText(TextMapper.GUIP_RE_PASSWORD));
        jLabelConfirmPassword.setEnabled(false);

        jLabelFamilyName.setText(TextMapper.getText(TextMapper.GUIP_LASTNAME)
        );

        jTextFieldInsertion.setEditable(false);
        jTextFieldInsertion.setMinimumSize(new java.awt.Dimension(320, 320));

        jLabelGivenName.setText(TextMapper.getText(TextMapper.GUIP_FIRSTNAME));

        jLabelInsertion.setText(TextMapper.getText(TextMapper.GUIP_MIDDLENAME)
        );

        jTextFieldGivenName.setEditable(false);
        jTextFieldGivenName.setMinimumSize(new java.awt.Dimension(320, 320));
        jTextFieldGivenName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGivenNameActionPerformed(evt);
            }
        });
        jTextFieldGivenName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFieldGivenNamePropertyChange(evt);
            }
        });

        jLabelEmail.setText(TextMapper.getText(TextMapper.GUIP_EMAIL));

        jTextFieldFamilyName.setEditable(false);
        jTextFieldFamilyName.setMinimumSize(new java.awt.Dimension(320, 320));

        jTextFieldEmail.setEditable(false);
        jTextFieldEmail.setMinimumSize(new java.awt.Dimension(320, 320));

        jButtonEditAndCancel.setText(TextMapper.getText(TextMapper.GUIP_BTN_EDIT)
        );
        jButtonEditAndCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditAndCancelActionPerformed(evt);
            }
        });

        jButtonUpdate.setText(TextMapper.getText(TextMapper.GUIP_BTN_SAVE));
        jButtonUpdate.setEnabled(false);
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jPasswordFieldPassword.setText("jPasswordField1");

        jPasswordFieldNewPassword.setText("jPasswordField2");

        jPasswordFieldConfirmPassword.setText("jPasswordField3");

        javax.swing.GroupLayout jPanelPersonalDataLayout = new javax.swing.GroupLayout(jPanelPersonalData);
        jPanelPersonalData.setLayout(jPanelPersonalDataLayout);
        jPanelPersonalDataLayout.setHorizontalGroup(
            jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabelGivenName, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGivenName, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabelInsertion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabelFamilyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFamilyName, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabelUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabelNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalDataLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditAndCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jLabelConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelPersonalDataLayout.setVerticalGroup(
            jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalDataLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGivenName)
                    .addComponent(jTextFieldGivenName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInsertion)
                    .addComponent(jTextFieldInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFamilyName)
                    .addComponent(jTextFieldFamilyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewPassword)
                    .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfirmPassword)
                    .addComponent(jPasswordFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditAndCancel)
                    .addComponent(jButtonUpdate))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPersonalData, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPersonalData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGivenNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGivenNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGivenNameActionPerformed

    private void jTextFieldGivenNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextFieldGivenNamePropertyChange
    }//GEN-LAST:event_jTextFieldGivenNamePropertyChange

    private void jButtonEditAndCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditAndCancelActionPerformed
        if (prop.getUser().getPasswd().equals(MD5.getHashString(jPasswordFieldPassword.getText())
        )) {
            //clear the password field if red
            jPasswordFieldPassword.setBackground(originalBackground);
            //allow update
            prop.setUpdate(true);
            jButtonEditAndCancel.setEnabled(false);
            jButtonUpdate.setEnabled(true);

            jTextFieldUserName.setEditable(true);
            jPasswordFieldConfirmPassword.setEditable(true);
            jLabelConfirmPassword.setEnabled(true);
            jPasswordFieldNewPassword.setEditable(true);
            jLabelNewPassword.setEnabled(true);
            jPasswordFieldPassword.setEditable(true);
            jTextFieldInsertion.setEditable(true);
            jTextFieldGivenName.setEditable(true);
            jTextFieldFamilyName.setEditable(true);
            jTextFieldEmail.setEditable(true);
        } else {
            originalBackground = jPasswordFieldPassword.getBackground();
            jPasswordFieldPassword.setBackground(Color.RED);
            jPasswordFieldPassword.grabFocus();
        }
    }//GEN-LAST:event_jButtonEditAndCancelActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        //try update else fail.
        if (prop.getUser().getPasswd().equals(MD5.getHashString(jPasswordFieldPassword.getText())
        )) {
            //update data and disable mode
            prop.setUpdate(false);
            jButtonEditAndCancel.setEnabled(true);
            jButtonUpdate.setEnabled(false);

            jTextFieldUserName.setEditable(false);
            jPasswordFieldConfirmPassword.setEditable(false);
            jPasswordFieldNewPassword.setEditable(false);
            jTextFieldInsertion.setEditable(false);
            jTextFieldGivenName.setEditable(false);
            jTextFieldFamilyName.setEditable(false);
            jTextFieldEmail.setEditable(false);

            prop.getUser().setFirstname(jTextFieldGivenName.getText());
            prop.getUser().setMiddlename(jTextFieldInsertion.getText());
            prop.getUser().setLastname(jTextFieldFamilyName.getText());
            prop.getUser().setEmail(jTextFieldEmail.getText());
            if (jPasswordFieldNewPassword.getText().equals("")) {
                jPasswordFieldConfirmPassword.setBackground(originalBackground);
            } else if (!jPasswordFieldNewPassword.getText().equals("")
                    && jPasswordFieldNewPassword.getPassword().equals(jPasswordFieldConfirmPassword.getPassword())) {
                //updates password following some logic.
                prop.getUser().setPasswd(MD5.getHashString(jPasswordFieldNewPassword.getPassword().toString()));
                jPasswordFieldConfirmPassword.setBackground(originalBackground);
            } else {
                jPasswordFieldConfirmPassword.setBackground(Color.RED);
            }
        } else {
            jPasswordFieldPassword.setCaretColor(Color.RED);
            jPasswordFieldPassword.grabFocus();
            jButtonEditAndCancel.setEnabled(true);
            jButtonUpdate.setEnabled(false);

        }
        jPasswordFieldPassword.setText("");
        prop.Update();
    }//GEN-LAST:event_jButtonUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditAndCancel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelConfirmPassword;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFamilyName;
    private javax.swing.JLabel jLabelGivenName;
    private javax.swing.JLabel jLabelInsertion;
    private javax.swing.JLabel jLabelNewPassword;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanelPersonalData;
    private javax.swing.JPasswordField jPasswordFieldConfirmPassword;
    private javax.swing.JPasswordField jPasswordFieldNewPassword;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFamilyName;
    private javax.swing.JTextField jTextFieldGivenName;
    private javax.swing.JTextField jTextFieldInsertion;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables

}
