/*Copyrighted 2015. */
package fi.dwo.dwojapplet.gui.panels;

import fi.dwo.commons.dom.entities.DomFullUser;
import fi.dwo.commons.dom.entities.DomSchoolRoleAndClass;
import fi.dwo.commons.exceptions.Dwo2Exception;
import fi.dwo.commons.exceptions.LoginException;
import fi.dwo.dwojapplet.domain.DwoHelper;
import fi.dwo.dwojapplet.gui.GuiConstants;
import fi.dwo.dwojapplet.gui.GuiCreator;
import fi.dwo.dwojapplet.gui.RegisterMoreSchoolsPanel;
import fi.dwo.dwojapplet.gui.ShowJPanelAsDialog;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author G.A.J. van der Plas
 */
public class JPanelSchoolsAndRoles extends javax.swing.JPanel {

    private static final Logger LOG = Logger.getLogger(JPanelSchoolsAndRoles.class.getName());

    private JPanelSchoolsandRolesProperties prop = new JPanelSchoolsandRolesProperties();
    private SchoolsAndRolesTableModel tableModel;

    /**
     * Creates new form JPanelSchoolsAndClasses
     */
    public JPanelSchoolsAndRoles() {
        try{
        prop.init();
        }catch(Dwo2Exception e){
            GuiCreator.instance().ShowMessageToUser(this, e.getLocalizedMessage(), "", JOptionPane.ERROR_MESSAGE);
        }
        tableModel = new SchoolsAndRolesTableModel();
        tableModel.init(prop.getSelectedSchoolRoleAndClass(), prop.getSchoolsRolesAndClasses());
        initComponents();
        jTableSchoolsAndClasses.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                    // do some actions here, for example
                    // print first column value from selected row
                if(!event.getValueIsAdjusting()){//
                    DomSchoolRoleAndClass src = (DomSchoolRoleAndClass) tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(),4);
//                    System.out.println(tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(), 3).toString());
                    prop.setSelectedSchoolRoleAndClass(src);
                    prop.setActiveSchoolRoleAndClass();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSchoolsAndClasses = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(GuiConstants.MAIN_BACKGROUND);
        setMinimumSize(new java.awt.Dimension(640, 400));
        setName(""); // NOI18N

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 400));

        jTableSchoolsAndClasses.setAutoCreateRowSorter(true);
        jTableSchoolsAndClasses.setModel(tableModel);
        jTableSchoolsAndClasses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSchoolsAndClasses.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSchoolsAndClasses);

        jButton1.setText("Add School Registration");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("switch");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            ShowJPanelAsDialog dialog = new ShowJPanelAsDialog(new RegisterMoreSchoolsPanel());
            dialog.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        prop.setActiveSchoolRoleAndClass();
        //get user data
        DomFullUser user = DwoHelper.getCurrentUser();
        // clear user data
        GuiCreator.instance().clearCurrentUserData();
        try {
            GuiCreator.instance().loginWithMd5(user.getUsername(), user.getPassword());
        } catch (LoginException ex) {
            LOG.log(Level.SEVERE, null, ex);
            GuiCreator.instance().ShowMessageToUser(this, ex.getLocalizedMessage(), "Eror", JDialog.ERROR);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSchoolsAndClasses;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the prop
     */
    public JPanelSchoolsandRolesProperties getProp() {
        return prop;
    }

    /**
     * @param prop the prop to set
     */
    public void setProp(JPanelSchoolsandRolesProperties prop) {
        this.prop = prop;
    }
}
