/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.dwo.dwojapplet.gui.panels;

import fi.dwo.commons.rest.entities.SchoolRoleAndClass;
import fi.dwo.dwojapplet.gui.GuiConstants;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author G.A.J. van der Plas
 */
public class JPanelSchoolsRolesAndClasses extends javax.swing.JPanel {
    private static final Logger log = Logger.getLogger(JPanelSchoolsRolesAndClasses.class.getName());

    private JPanelSchoolsRolesAndClassesProperties prop = new JPanelSchoolsRolesAndClassesProperties();
    private SchoolsRolesAndClassesTableModel tableModel;

    /**
     * Creates new form JPanelSchoolsAndClasses
     */
    public JPanelSchoolsRolesAndClasses() {
        prop.init();
        tableModel = new SchoolsRolesAndClassesTableModel();
        tableModel.init(prop.getSchoolsRolesAndClasses());
        initComponents();
        jTableSchoolsAndClasses.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                    // do some actions here, for example
                    // print first column value from selected row
                if(!event.getValueIsAdjusting()){//
                    String srcString = ""+ tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(), 0)
                            + ", " + tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(), 1);
                    if((Integer) tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(), 5)!=-1){
                            srcString += ", " + tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(), 2);
                    }
                    jTextFieldSchoolRoleClass.setText(srcString);
                    System.out.println(tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(), 3).toString());
                }
            }
        });

        try {
            SchoolRoleAndClass src = prop.getActiveSchoolRoleAndClass();
            String srcString = src.getSchoolName() + ", " + src.getRoleName();

            if (src.getRoleName().equals("STUDENT")) {
                srcString += ", " + src.getSchoolClassName();
            }
            jTextFieldSchoolRoleClass.setText(srcString);
            //fill table Model

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSchoolsAndClasses = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelSchoolRoleClass = new javax.swing.JLabel();
        jTextFieldSchoolRoleClass = new javax.swing.JTextField();

        setBackground(GuiConstants.MAIN_BACKGROUND);
        setMinimumSize(new java.awt.Dimension(640, 400));
        setName(""); // NOI18N

        jSplitPane1.setBackground(GuiConstants.MAIN_BACKGROUND);
        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(600, 300));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 400));

        jTableSchoolsAndClasses.setAutoCreateRowSorter(true);
        jTableSchoolsAndClasses.setModel(tableModel);
        jTableSchoolsAndClasses.setCellSelectionEnabled(false);
        jTableSchoolsAndClasses.setRowSelectionAllowed(true);
        jTableSchoolsAndClasses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSchoolsAndClasses.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSchoolsAndClasses);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel1.setBackground(jTableSchoolsAndClasses.getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel1);

        jLabelSchoolRoleClass.setText("Activated school, role and class");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSchoolRoleClass, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSchoolRoleClass)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSchoolRoleClass)
                    .addComponent(jTextFieldSchoolRoleClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSchoolRoleClass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableSchoolsAndClasses;
    private javax.swing.JTextField jTextFieldSchoolRoleClass;
    // End of variables declaration//GEN-END:variables
}
