/*Copyrighted 2015. */
package fi.dwo.dwojapplet.gui.panels;

import fi.dwo.commons.rest.entities.SchoolRoleAndClass;
import fi.dwo.dwojapplet.gui.GuiConstants;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author G.A.J. van der Plas
 */
public class JPanelSchoolsRolesAndClasses extends javax.swing.JPanel {
    private static final Logger LOG = Logger.getLogger(JPanelSchoolsRolesAndClasses.class.getName());

    private JPanelSchoolsRolesAndClassesProperties prop = new JPanelSchoolsRolesAndClassesProperties();
    private SchoolsRolesAndClassesTableModel tableModel;

    /**
     * Creates new form JPanelSchoolsAndClasses
     */
    public JPanelSchoolsRolesAndClasses() {
        prop.init();
        tableModel = new SchoolsRolesAndClassesTableModel();
        tableModel.init(prop.getSelectedSchoolRoleAndClass(), prop.getSchoolsRolesAndClasses());
        initComponents();
        jPanelCommonRoleOptions2.setProp(prop);
        jTableSchoolsAndClasses.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                    // do some actions here, for example
                    // print first column value from selected row
                if(!event.getValueIsAdjusting()){//
                    SchoolRoleAndClass src = (SchoolRoleAndClass) tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(),3);
                    String srcString = ""+ tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(), 0)
                            + ", " + tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(), 1);
                    if(src.getSchoolClassId()!=null){
                            srcString += ", " + tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(), 2);
                    }
                    jTextFieldSchoolRoleClass.setText(srcString);
//                    System.out.println(tableModel.getValueAt(jTableSchoolsAndClasses.getSelectedRow(), 3).toString());
                    prop.setSelectedSchoolRoleAndClass(src);
                }
            }
        });

        try {
            SchoolRoleAndClass src = prop.getSelectedSchoolRoleAndClass();
            String srcString = src.getSchoolName() + ", " + src.getRoleName();

            if (src.getRoleName().equals("STUDENT") && src.getSchoolClassId()!=null){
                srcString += ", " + src.getSchoolClassName();
            }
            jTextFieldSchoolRoleClass.setText(srcString);
        } catch (Exception e) {
            LOG.log(Level.SEVERE, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSchoolsAndClasses = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanelCommonRoleOptions2 = new fi.dwo.dwojapplet.gui.panels.JPanelCommonRoleOptions();
        jLabelSchoolRoleClass = new javax.swing.JLabel();
        jTextFieldSchoolRoleClass = new javax.swing.JTextField();

        setBackground(GuiConstants.MAIN_BACKGROUND);
        setMinimumSize(new java.awt.Dimension(640, 400));
        setName(""); // NOI18N

        jSplitPane1.setBackground(GuiConstants.MAIN_BACKGROUND);
        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(600, 300));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 400));

        jTableSchoolsAndClasses.setAutoCreateRowSorter(true);
        jTableSchoolsAndClasses.setBackground(new java.awt.Color(255, 255, 255));
        jTableSchoolsAndClasses.setModel(tableModel);
        jTableSchoolsAndClasses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSchoolsAndClasses.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSchoolsAndClasses);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel1.setBackground(getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(535, 360));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jPanel1, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jPanelCommonRoleOptions2, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCommonRoleOptions2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCommonRoleOptions2, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel1);

        jLabelSchoolRoleClass.setText("Selected school, role and class");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSchoolRoleClass, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSchoolRoleClass, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSchoolRoleClass)
                    .addComponent(jTextFieldSchoolRoleClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSchoolRoleClass;
    private javax.swing.JPanel jPanel1;
    private fi.dwo.dwojapplet.gui.panels.JPanelCommonRoleOptions jPanelCommonRoleOptions2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableSchoolsAndClasses;
    private javax.swing.JTextField jTextFieldSchoolRoleClass;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the prop
     */
    public JPanelSchoolsRolesAndClassesProperties getProp() {
        return prop;
    }

    /**
     * @param prop the prop to set
     */
    public void setProp(JPanelSchoolsRolesAndClassesProperties prop) {
        this.prop = prop;
    }
}
