/* Copyrighted 2015. */
package fi.dwo.dwojapplet.gui.panels;

import fi.dwo.commons.exceptions.LoginException;
import fi.dwo.commons.persistence.entities.PersistentUser;
import fi.dwo.commons.system.TextMapper;
import static fi.dwo.commons.system.TextMapper.GUIP_BTN_SWITCH_PROFILE;
import fi.dwo.dwojapplet.domain.DwoHelper;
import fi.dwo.dwojapplet.gui.AccountPanel;
import fi.dwo.dwojapplet.gui.GuiCreator;
import fi.dwo.dwojapplet.gui.ReauthenticatePanel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author G.A.J. van der Plas
 */
public class JPanelCommonRoleOptions extends javax.swing.JPanel {

    private static final Logger LOG = Logger.getLogger(JPanelCommonRoleOptions.class.getName());
    private JPanelSchoolsRolesAndClassesProperties prop = new JPanelSchoolsRolesAndClassesProperties();

    /**
     * Creates new form JPanelSchoolAdmin
     */
    public JPanelCommonRoleOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDeleteProfile = new javax.swing.JButton();
        jButtonSwitchToProfile = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(387, 353));

        jButtonDeleteProfile.setText("Add schools");
        jButtonDeleteProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteProfileActionPerformed(evt);
            }
        });

        jButtonSwitchToProfile.setText(TextMapper.getText(GUIP_BTN_SWITCH_PROFILE));
        jButtonSwitchToProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSwitchToProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSwitchToProfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteProfile)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteProfile)
                    .addComponent(jButtonSwitchToProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSwitchToProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSwitchToProfileActionPerformed
        //Update current active Role, knows selected role.
        prop.setActiveSchoolRoleAndClass();
        //get user data
        PersistentUser user = DwoHelper.getCurrentUser();
        // clear user data
        GuiCreator.instance().clearCurrentUserData();
        try {
            GuiCreator.instance().loginWithMd5(user.getUsername(), user.getPasswd());
        } catch (LoginException ex) {
            LOG.log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonSwitchToProfileActionPerformed

    private void jButtonDeleteProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteProfileActionPerformed
        boolean r = ReauthenticatePanel.Reauthenticate(TextMapper.getText(TextMapper.GUIREAUTH_AREYOUSURE));
        JPanel p = new AccountPanel(null);
        JFrame f  = new JFrame();
        f.add(p);
        f.setEnabled(true);
        f.setVisible(true);
        p.setVisible(true);
    }//GEN-LAST:event_jButtonDeleteProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteProfile;
    private javax.swing.JButton jButtonSwitchToProfile;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the prop
     */
    public JPanelSchoolsRolesAndClassesProperties getProp() {
        return prop;
    }

    /**
     * @param prop the prop to set
     */
    public void setProp(JPanelSchoolsRolesAndClassesProperties prop) {
        this.prop = prop;
    }
}
