<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
        <groupId>nl.uu.fi.dwo</groupId>
        <artifactId>dwo</artifactId>
        <relativePath>../DWO/pom.xml</relativePath>
        <version>2.5.49-SNAPSHOT</version>
	</parent>
	<groupId>fi.writemathgwt</groupId>
	<artifactId>writemathgwt</artifactId>
	<name>DWO WriteMath GWT</name>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <webappDirectory>${project.build.directory}/${project.build.finalName}</webappDirectory>
        <maven.javadoc.failOnError>false</maven.javadoc.failOnError>
        <maven.test.skip>true</maven.test.skip>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <gwtVersion>2.10.0</gwtVersion>
        <gwt.compiler.skip>true</gwt.compiler.skip>
    </properties>
	<dependencies>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<version>${gwtVersion}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>lineairealgebra</artifactId>
			<version>2.5.49-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>lineairealgebra</artifactId>
			<version>2.5.49-SNAPSHOT</version>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-dev</artifactId>
			<scope>test</scope>
			<version>${gwtVersion}</version>
		</dependency>
		<dependency>
		    <groupId>com.vaadin.addon</groupId>
		    <artifactId>pointer-events</artifactId>
		    <version>1.0</version>
		</dependency>
	</dependencies>
	<build>
		<finalName>writemath</finalName>
		<resources>
			<resource>
				<directory>src</directory>
			</resource>
		</resources>
		<sourceDirectory>src</sourceDirectory>
	</build>
	<description>Recognize handwritten mathematics.</description>
</project>
