<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>nl.uu.fi.dwo</groupId>
		<artifactId>DWO-GWT</artifactId>
		<version>1.1</version>
		<relativePath>../DWO-GWT</relativePath>
	</parent>
	<groupId>fi.writemathgwt</groupId>
	<artifactId>WriteMathGWT</artifactId>
	<name>DWO WriteMath GWT</name>
	<dependencies>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<version>0.1.11</version>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>lineairealgebra</artifactId>
			<version>0.0.1</version>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>lineairealgebra</artifactId>
			<version>0.0.1</version>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-dev</artifactId>
			<scope>test</scope>
			<version>${gwtVersion}</version>
		</dependency>
		<dependency>
		    <groupId>com.vaadin.addon</groupId>
		    <artifactId>pointer-events</artifactId>
		    <version>1.0</version>
		</dependency>
	</dependencies>
	<build>
		<finalName>writemath</finalName>
		<resources>
			<resource>
				<directory>src</directory>
			</resource>
		</resources>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>2.5.3</version>
				<configuration>
					<goals>deploy</goals>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<description>Recognize handwritten mathematics.</description>
	<version>2.5.5</version>
  <scm>
  	<developerConnection>scm:svn:https://svn.science.uu.nl/repos/project.fisme.java/WriteMathGWT/trunk</developerConnection>
  </scm>
	<repositories>
		<repository>
			<id>vaadin-addons</id>
			<url>http://vaadin.com/nexus/content/repositories/vaadin-addons/</url>
		</repository>
	</repositories>
</project>