package fi.dwo.client.persistence;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Hashtable;
import java.util.Vector;

import org.apache.xmlrpc.applet.XmlRpcException;

import fi.dwo.server.persistence.DwoXmlRpcException;
import fi.servlet.persistence.PersistenceClient;

/**
 * This class is automaticly generated by the xmlrpcc-command
 * @author M.J.B. Kupers
 *
 */
public class DbAccessClient extends PersistenceClient implements fi.dwo.client.persistence.DbAccessIF
{
  public DbAccessClient(java.net.URL u)
  {
     super(u);
  }

//public abstract boolean fi.dwo.client.persistence.DbAccessIF.register(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean register (
    java.lang.String a,
    java.lang.String b,
    java.lang.String c,
    java.lang.String d,
    java.lang.String e,
    java.lang.String f
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(6);
    params.addElement(a);
    params.addElement(b);
    params.addElement(c);
    params.addElement(d);
    params.addElement(e);
    params.addElement(f);
    boolean  result;
    Object o = 
        invoke("register", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.register(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,int,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean register (
    java.lang.String a,
    java.lang.String b,
    java.lang.String c,
    java.lang.String d,
    java.lang.String e,
    java.lang.String f,
    java.lang.String g,
    int h,
    java.lang.String i
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(9);
    params.addElement(a);
    params.addElement(b);
    params.addElement(c);
    params.addElement(d);
    params.addElement(e);
    params.addElement(f);
    params.addElement(g);
    params.addElement( new Integer( h));
    params.addElement(i);
    boolean  result;
    Object o = 
        invoke("register", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract java.util.Hashtable fi.dwo.client.persistence.DbAccessIF.addClass(int,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Hashtable addClass (
    int a,
    java.lang.String b
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(2);
    params.addElement( new Integer( a));
    params.addElement(b);
    java.util.Hashtable  result;
    Object o = 
        invoke("addClass", params);
    result = (java.util.Hashtable) o;
    return result;
  }
  
 //  public abstract java.util.Hashtable fi.dwo.client.persistence.DbAccessIF.addSchool(int,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Hashtable addSchool (
    java.lang.String a,
    java.lang.String b,
    java.lang.String c, java.lang.String d
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(4);
    params.addElement(a);
    params.addElement(b);
    params.addElement(c);
    params.addElement(d);
    java.util.Hashtable  result;
    Object o = 
        invoke("addSchool", params);
    result = (java.util.Hashtable) o;
    return result;
  }

  //  public abstract java.util.Hashtable fi.dwo.client.persistence.DbAccessIF.addSchool(int,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Hashtable addSchool (
    int id,
    java.lang.String a,
    java.lang.String b,
    java.lang.String c,
    java.lang.String d
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(5);
    params.addElement(new Integer(id));
    params.addElement(a);
    params.addElement(b);
    params.addElement(c);
    params.addElement(d);
    java.util.Hashtable  result;
    Object o = 
        invoke("addSchool", params);
    result = (java.util.Hashtable) o;
    return result;
  }
  
 //  public abstract java.util.Hashtable fi.dwo.client.persistence.DbAccessIF.editSchool(int,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Hashtable editSchool (
    int a,
    java.lang.String b,
    java.lang.String c,
    java.lang.String d,
    java.lang.String e
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(5);
    params.addElement(new Integer(a));
    params.addElement(b);
    params.addElement(c);
    params.addElement(d);
    params.addElement(e);
    java.util.Hashtable  result;
    Object o = 
        invoke("editSchool", params);
    result = (java.util.Hashtable) o;
    return result;
  }
  
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.log(java.lang.String) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException
  public boolean log (
    java.lang.String a
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(1);
    params.addElement(a);
    boolean  result;
    Object o = 
        invoke("log", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getCoursesForClass(int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getCoursesForClass (
    int a
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(1);
    params.addElement( new Integer( a));
    java.util.Vector  result;
    Object o = 
        invoke("getCoursesForClass", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.selectCoursesForClass(int,int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean selectCoursesForClass (
    int a,
    int b
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(2);
    params.addElement( new Integer( a));
    params.addElement( new Integer( b));
    boolean  result;
    Object o = 
        invoke("selectCoursesForClass", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.deSelectCoursesForClass(int,int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean deSelectCoursesForClass (
    int a,
    int b
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(2);
    params.addElement( new Integer( a));
    params.addElement( new Integer( b));
    boolean  result;
    Object o = 
        invoke("deSelectCoursesForClass", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getCourses(int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getCourses (
    int a
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(1);
    params.addElement( new Integer( a));
    java.util.Vector  result;
    Object o = 
        invoke("getCourses", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getCourses(int,boolean) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getCourses (
    int a,
    boolean b
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(2);
    params.addElement( new Integer( a));
    params.addElement( new Boolean( b));
    java.util.Vector  result;
    Object o = 
        invoke("getCourses", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getEditableCourses(int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getEditableCourses (
    int a
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(1);
    params.addElement( new Integer( a));
    java.util.Vector  result;
    Object o = 
        invoke("getEditableCourses", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getEditableCoursesAdmin() throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getEditableCoursesAdmin ()
  throws IOException, XmlRpcException
  {
    Vector params = new Vector();
    java.util.Vector  result;
    Object o = 
        invoke("getEditableCoursesAdmin", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract java.util.Hashtable fi.dwo.client.persistence.DbAccessIF.getRecord(java.lang.String,java.lang.String,int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Hashtable getRecord (
    java.lang.String a,
    java.lang.String b,
    int c
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(3);
    params.addElement(a);
    params.addElement(b);
    params.addElement( new Integer( c));
    java.util.Hashtable  result;
    Object o = 
        invoke("getRecord", params);
    result = (java.util.Hashtable) o;
    return result;
  }

  public java.util.Vector getTable (
          java.lang.String a,
          java.lang.String b
          )
        throws IOException, XmlRpcException
        {
          Vector params = new Vector(1);
          params.addElement(a);
          params.addElement(b);
          java.util.Vector  result;
          Object o = 
              invoke("getTable", params);
          result = (java.util.Vector) o;
          return result;
        }
  
  //  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getTable(java.lang.String) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getTable (
    java.lang.String a
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(1);
    params.addElement(a);
    java.util.Vector  result;
    Object o = 
        invoke("getTable", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getTable(java.lang.String,java.util.Hashtable) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getTable (
    java.lang.String a,
    java.util.Hashtable b
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(2);
    params.addElement(a);
    params.addElement(b);
    java.util.Vector  result;
    Object o = 
        invoke("getTable", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getTable(java.lang.String,java.util.Hashtable,java.lang.String) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getTable (
    java.lang.String a,
    java.util.Hashtable b,
    java.lang.String c
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(3);
    params.addElement(a);
    params.addElement(b);
    params.addElement(c);
    java.util.Vector  result;
    Object o = 
        invoke("getTable", params);
    result = (java.util.Vector) o;
    return result;
  }
//public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getTable(java.lang.String,java.util.Vector,java.util.Hashtable,java.lang.String) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getTable (
    java.lang.String a,
    java.util.Vector a0,
    java.util.Hashtable b,
    java.lang.String c
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(4);
    params.addElement(a);
    params.addElement(a0);
    params.addElement(b);
    params.addElement(c);
    java.util.Vector  result;
    Object o = 
        invoke("getTable", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.renameClass(int,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean renameClass (
    int a,
    java.lang.String b
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(2);
    params.addElement( new Integer( a));
    params.addElement(b);
    boolean  result;
    Object o = 
        invoke("renameClass", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract java.lang.String fi.dwo.client.persistence.DbAccessIF.LMSGetValue(int,int,java.lang.String) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.lang.String LMSGetValue (
    int a,
    int b,
    java.lang.String c
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(3);
    params.addElement( new Integer( a));
    params.addElement( new Integer( b));
    params.addElement(c);
    java.lang.String  result;
    Object o = 
        invoke("LMSGetValue", params);
    result = (java.lang.String) o;
    return result;
  }
//  public abstract java.lang.String fi.dwo.client.persistence.DbAccessIF.LMSSetValue(int,int,java.lang.String,java.lang.String) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.lang.String LMSSetValue (
    int a,
    int b,
    java.lang.String c,
    java.lang.String d
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(4);
    params.addElement( new Integer( a));
    params.addElement( new Integer( b));
    params.addElement(c);
    params.addElement(d);
    java.lang.String  result;
    Object o = 
        invoke("LMSSetValue", params);
    result = (java.lang.String) o;
    return result;
  }
//  public abstract java.util.Hashtable fi.dwo.client.persistence.DbAccessIF.login(java.lang.String,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Hashtable login (
    java.lang.String a,
    java.lang.String b
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(2);
    params.addElement(a);
    params.addElement(b);
    java.util.Hashtable  result;
    Object o = 
        invoke("login", params);
    result = (java.util.Hashtable) o;
    return result;
  }
//  public abstract java.util.Hashtable fi.dwo.client.persistence.DbAccessIF.addToSchool(int,java.lang.String,int,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Hashtable addToSchool (
    int a,
    java.lang.String b,
    int c,
    java.lang.String d
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(4);
    params.addElement( new Integer( a));
    params.addElement(b);
    params.addElement( new Integer( c));
    params.addElement(d);
    java.util.Hashtable  result;
    Object o = 
        invoke("addToSchool", params);
    result = (java.util.Hashtable) o;
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.changeAccount(int,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,int) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean changeAccount (
    int a,
    java.lang.String b,
    java.lang.String c,
    java.lang.String d,
    java.lang.String e,
    java.lang.String f,
    java.lang.String g,
    int h
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(8);
    params.addElement( new Integer( a));
    params.addElement(b);
    params.addElement(c);
    params.addElement(d);
    params.addElement(e);
    params.addElement(f);
    params.addElement(g);
    params.addElement( new Integer( h));
    boolean  result;
    Object o = 
        invoke("changeAccount", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.changeAccount(int,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean changeAccount (
    int a,
    java.lang.String b,
    java.lang.String c,
    java.lang.String d,
    java.lang.String e,
    java.lang.String f,
    java.lang.String g
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(7);
    params.addElement( new Integer( a));
    params.addElement(b);
    params.addElement(c);
    params.addElement(d);
    params.addElement(e);
    params.addElement(f);
    params.addElement(g);
    boolean  result;
    Object o = 
        invoke("changeAccount", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.deleteUser(int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean deleteUser (
    int a
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(1);
    params.addElement( new Integer( a));
    boolean  result;
    Object o = 
        invoke("deleteUser", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.deleteClass(int,boolean) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean deleteClass (
    int a,
    boolean b
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(2);
    params.addElement( new Integer( a));
    params.addElement( new Boolean( b));
    boolean  result;
    Object o = 
        invoke("deleteClass", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getResults(java.util.Vector,int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getResults (
    java.util.Vector a,
    int b
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(2);
    params.addElement(a);
    params.addElement( new Integer( b));
    java.util.Vector  result;
    Object o = 
        invoke("getResults", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getResults(java.util.Vector,int,int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getResults (
    java.util.Vector a,
    int b,
    int c
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(3);
    params.addElement(a);
    params.addElement( new Integer( b));
    params.addElement( new Integer( c));
    java.util.Vector  result;
    Object o = 
        invoke("getResults", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getResults(int,int,int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getResults (
    int a,
    int b,
    int c
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(3);
    params.addElement( new Integer( a));
    params.addElement( new Integer( b));
    params.addElement( new Integer( c));
    java.util.Vector  result;
    Object o = 
        invoke("getResults", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract java.util.Vector fi.dwo.client.persistence.DbAccessIF.getResults(int,int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public java.util.Vector getResults (
    int a,
    int b
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(2);
    params.addElement( new Integer( a));
    params.addElement( new Integer( b));
    java.util.Vector  result;
    Object o = 
        invoke("getResults", params);
    result = (java.util.Vector) o;
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.disconnectFromClass(int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean disconnectFromClass (
    int a
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(1);
    params.addElement( new Integer( a));
    boolean  result;
    Object o = 
        invoke("disconnectFromClass", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.selectJar(java.lang.String,java.lang.String) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean selectJar (
    java.lang.String a,
    java.lang.String b
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(2);
    params.addElement(a);
    params.addElement(b);
    boolean  result;
    Object o = 
        invoke("selectJar", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.reconnect() throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean reconnect (
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(0);
    boolean  result;
    Object o = 
        invoke("reconnect", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract int fi.dwo.client.persistence.DbAccessIF.addCourse(int,java.lang.String,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public int addCourse (
    int a,
    java.lang.String b,
    java.lang.String c,
    int d
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(4);
    params.addElement( new Integer( a));
    params.addElement(b);
    params.addElement(c);
    params.addElement( new Integer( d));
    int  result;
    Object o = 
        invoke("addCourse", params);
    result = ((Integer)o).intValue();
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.changeCourse(int,java.lang.String,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean changeCourse (
    int a,
    java.lang.String b,
    java.lang.String c
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(3);
    params.addElement( new Integer( a));
    params.addElement(b);
    params.addElement(c);
    boolean  result;
    Object o = 
        invoke("changeCourse", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.deleteCourse(int) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean deleteCourse (
    int a
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(1);
    params.addElement( new Integer( a));
    boolean  result;
    Object o = 
        invoke("deleteCourse", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract int fi.dwo.client.persistence.DbAccessIF.addSco(int,java.lang.String,java.lang.String,int,int) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public int addSco (
    int a,
    java.lang.String b,
    java.lang.String c,
    int d,
    int e
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(5);
    params.addElement( new Integer( a));
    params.addElement(b);
    params.addElement(c);
    params.addElement( new Integer( d));
    params.addElement( new Integer( e));
    int  result;
    Object o = 
        invoke("addSco", params);
    result = ((Integer)o).intValue();
    return result;
  }
  
  public int addSco (
		    int a,
		    java.lang.String b,
		    java.lang.String c,
		    int d,
		    String launchdata,
		    int e
		    )
		  throws IOException, XmlRpcException
		  {
		    Vector params = new Vector(6);
		    params.addElement( new Integer( a));
		    params.addElement(b);
		    params.addElement(c);
		    params.addElement( new Integer( d));
		    params.addElement(launchdata);
		    params.addElement( new Integer( e));
		    int  result;
		    Object o = 
		        invoke("addSco", params);
		    result = ((Integer)o).intValue();
		    return result;
		  }
		   
  
  
  
  
  
  
  
  
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.changeSco(int,java.lang.String,java.lang.String) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean changeSco (
    int a,
    java.lang.String b,
    java.lang.String c,
    java.lang.String d
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(3);
    params.addElement( new Integer( a));
    params.addElement(b);
    params.addElement(c);
    params.addElement(d);
    boolean  result;
    Object o = 
        invoke("changeSco", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
//  public abstract boolean fi.dwo.client.persistence.DbAccessIF.deleteSco(int) throws fi.dwo.server.persistence.DwoXmlRpcException,java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
  public boolean deleteSco (
    int a
    )
  throws IOException, XmlRpcException
  {
    Vector params = new Vector(1);
    params.addElement( new Integer( a));
    boolean  result;
    Object o = 
        invoke("deleteSco", params);
    result = ((Boolean)o).booleanValue();
    return result;
  }
 
//public abstract boolean fi.dwo.client.persistence.DbAccessIF.deleteSchool(int) throws java.io.IOException,org.apache.xmlrpc.applet.XmlRpcException,java.sql.SQLException
public boolean deleteSchool (
  int a
  )
throws IOException, XmlRpcException
{
  Vector params = new Vector(1);
  params.addElement( new Integer( a));
  boolean  result;
  Object o = 
      invoke("deleteSchool", params);
  result = ((Boolean)o).booleanValue();
  return result;
}

public Hashtable getFidentitySchools() throws IOException, XmlRpcException {
	Vector params = new Vector(0);
	return (Hashtable) invoke("getFidentitySchools", params);
}

public boolean changeScoSequenceNr(int scoID, int sequencenr, int scoID2, int sequencenr2) throws IOException, XmlRpcException {
    Vector params = new Vector(4);
    params.addElement( new Integer( scoID));
    params.addElement( new Integer( sequencenr));
    params.addElement( new Integer( scoID2));
    params.addElement( new Integer( sequencenr2));
    boolean  result;
    Object o = 
        invoke("changeScoSequenceNr", params);
    result = ((Boolean)o).booleanValue();
    return result;
}

public Vector getUserResults(int a, int b) throws IOException,
		XmlRpcException {
    Vector params = new Vector(2);
    params.addElement( new Integer( a));
    params.addElement( new Integer( b));
    java.util.Vector  result;
    Object o = 
        invoke("getUserResults", params);
    result = (java.util.Vector) o;
    return result;
}

public Vector getUserResults(Vector a, int b) throws IOException, XmlRpcException {
    Vector params = new Vector(2);
    params.addElement( a);
    params.addElement( new Integer( b));
    java.util.Vector  result;
    Object o = 
        invoke("getUserResults", params);
    result = (java.util.Vector) o;
    return result;
}

public boolean setLogo(int id, byte[] image) throws IOException,
		XmlRpcException {
    Vector params = new Vector(2);
    params.addElement( new Integer(id));
    params.addElement( image );
    Object o = 
    	invoke("setLogo", params);
    return Boolean.TRUE.equals(o);
}

}