<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.uu.fi.dwo</groupId>
        <artifactId>dwo</artifactId>
        <relativePath>../DWO/pom.xml</relativePath>
        <version>2.5.49-SNAPSHOT</version>
    </parent>

    <groupId>nl.uu.fi.dwo.account</groupId>
    <artifactId>account</artifactId>
    <packaging>war</packaging>

    <name>${project.build.finalName}</name>
    <url>http://www.dwo.nl</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <webappDirectory>${project.build.directory}/${project.build.finalName}</webappDirectory>
        <maven.javadoc.failOnError>false</maven.javadoc.failOnError>
        <maven.test.skip>true</maven.test.skip>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <gwtVersion>2.10.0</gwtVersion>
        <gwt.compiler.skip>true</gwt.compiler.skip>
    </properties>
    <build>
        <outputDirectory>target/${project.build.finalName}/WEB-INF/classes</outputDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.0.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>exploded</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <warSourceDirectory>war</warSourceDirectory>
                    <attachClasses>true</attachClasses>
                    <webappDirectory>${webappDirectory}</webappDirectory> 
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>${gwtVersion}</version>
                <configuration>
                    <module>nl.uu.fi.dwo.account.Account</module>
                    
                    <runTarget>Account.html</runTarget>
                    <hostedWebapp>${webappDirectory}</hostedWebapp>
                    <warSourceDirectory>war</warSourceDirectory>
                    <extraJvmArgs>-Xms768m -Xmx1024m</extraJvmArgs>
                    <hostedWebapp>${webappDirectory}</hostedWebapp> 
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <!-- <goal>i18n</goal> -->
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.tomcat.maven</groupId>
                <artifactId>tomcat7-maven-plugin</artifactId>
                <version>2.2</version>
                <configuration>
                    <server>TomcatServer</server>
                    <path>/Account</path>
                    <warFile>target/${project.artifactId}-${project.version}.war</warFile>
                    <warSourceDirectory>target/${project.artifactId}-${project.version}</warSourceDirectory>
<!--                    <webapps> 
                        <webapp> 
                            <groupId>nl.uu.fi.dwo</groupId>
                            <artifactId>dwoserver</artifactId>
                            <version>2.1.9</version>
                            <type>war</type>
                            <asWebapp>true</asWebapp> 
                        </webapp> 
                    </webapps>
                            <dependencies>
                                <dependency>
                                    <groupId>mysql</groupId>
                                    <artifactId>mysql-connector-java</artifactId>
                                    <version>5.1.34</version>
                                </dependency>
                                <dependency>
                                    <groupId>com.jamonapi</groupId>
                                    <artifactId>jamon</artifactId>
                                    <version>2.80</version>
                                </dependency>        
                            </dependencies>                    -->
                </configuration>                                        
            </plugin>            
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>nl.uu.fi.dwo</groupId>
            <artifactId>dwo-gwt-lib</artifactId>
        </dependency>
        <dependency>
            <groupId>nl.uu.fi.dwo</groupId>
            <artifactId>dwo-gwt-lib</artifactId>
            <classifier>sources</classifier>
        </dependency>         

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-user</artifactId>
            <scope>provided</scope>
            <version>${gwtVersion}</version>
        </dependency>
        <dependency>
        	<groupId>com.google.gwt</groupId>
        	<artifactId>gwt-dev</artifactId>
        	<version>${gwtVersion}</version>
        	<scope>provided</scope>
        </dependency>
		<dependency>
			<groupId>org.mitre.dsmiley.httpproxy</groupId>
			<artifactId>smiley-http-proxy-servlet</artifactId>
			<version>1.7</version>
			<scope>runtime</scope>
		</dependency>
<dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.3.0</version>
	  <classifier>sources</classifier>
      <scope>provided</scope>
    </dependency>
    	<dependency>
    		<groupId>javax.inject</groupId>
    		<artifactId>javax.inject</artifactId>
    		<version>1</version>
    	</dependency>
    	<dependency>
    		<groupId>javax.inject</groupId>
    		<artifactId>javax.inject</artifactId>
    		<version>1</version>
    		<classifier>sources</classifier>
    	</dependency>
    </dependencies>
    <description>Gebruiker: profiel en klas panels</description>
</project>
