fi.ltiwidget.LTIWidget: ltiwidget.jar,jfxrt.jar
widgetsample.SampleWidget: widgetsample.jar
ewcbook.EpsilonWidget: http://www.epsilonwriter.com/mcs/EpsilonWidget.jar
ewcbook.EpsilonChatWidget: http://www.epsilonwriter.com/mcs/EpsilonWidget.jar
de.cinderella.CindyWidget: \
 http://cinderella.de/files/widget/cindyrun2.jar, \
 http://cinderella.de/files/widget/cdyextras.jar, \
 http://cinderella.de/files/widget/cdyimages.jar, \
 http://cinderella.de/files/widget/cdymessages.jar, \
 http://cinderella.de/files/widget/i2geo-server-api.jar, \
 http://cinderella.de/files/widget/javaosc.jar, \
 http://cinderella.de/files/widget/jilt.jar, \
 http://cinderella.de/files/widget/LeapJava.jar, \
 http://cinderella.de/files/widget/yajtl.jar, \
 http://cinderella.de/files/widget/log4j.jar, \
 http://cinderella.de/files/widget/antlr.jar, \
 http://cinderella.de/files/widget/gson-2.2.4.jar, \
 http://cinderella.de/files/widget/jmdns.jar
widgetESlate.ESlateWidget: http://www.talent.gr/mws/widgeteslate.jar
org.cbook.mediaman.MediaMan: mediaman.jar, cortado.jar, jl1.0.1.jar, jmf.jar, tritonus_share.jar, vorbisspi1.0.3.jar 
