# Localization information for exception types.
# DwoPersistenceExceptions
DwoPersistenceException.ObjectNotFound=The persistent object cound not be found.
DwoPersistenceException.DataModelConstraintViolated=The operation violates a data model constraint.

#DwoRestExceptionExceptions
DwoRestException.ServerCommunicationError="Server communication error."
DwoRestException.ServerAuthenticationError= "Server not valid."
DwoRestException.ServerUserAuthenticationError= "User credentials invalid."
DwoRestException.RestInterfaceError= "Rest-interface threw an error."
