<?xml version='1.0' ?>
<project name='DWOmAccess' basedir='../../../..' default='war' >
	<description>
	Auteur: Wim

	Deze ant build kan je gebruiken voor het automatiseren van common tasks in de referentie omgeving.
	!Let op de eis dat de main application name gelijk is aan de project name!


	</description>

	<dirname property="ant.dir" file="${ant.file}"  />
	<property file="${ant.dir}/build.properties"/>

	<property name='dosdrive' value='N:' />
	<property name='java.resources' value='/home/java/resources' />
	<property name='common.build' value='${java.resources}/ant/common-build.xml' />
	<condition property='dos' value='dos' >
	   	<os family='dos' />
	</condition>
	<condition property='drive' value='${dosdrive}'>
		<os family='dos' />
	</condition>
	<condition property='drive' value=''  >
		<os family='unix' />
	</condition>

	<import file="${drive}${common.build}" />

	<target name='war' depends='jar' >
    	<war
    		warfile="build/DWOmAccess.war"
    		webxml="WebContent/WEB-INF/web.xml"	 
    		duplicate="preserve"
    		manifest="WebContent/META-INF/MANIFEST.MF"
    	>
    		<fileset dir="WebContent" />
        	<lib file="${packagename.jar}"  />
    		<lib dir="WebContent/WEB-INF/lib" />
    	</war>
	
	</target>

	<target name='jar' depends='resources, compile, syncjc' >
		<echo message='building ${packagename.jar}'></echo>
		<jar
			destfile='${packagename.jar}'
			duplicate='preserve'
		>
			<fileset dir='${classes}'
				includes='**/*.class **/resources/*'
			/>
		</jar>
	</target>

</project>
