#Property file. It should be located in the working directory of the DWO application.
#resourceURLPath should point to a webserver supplying the applet jar files loaded by WiskOpdr.
#serverUrlPath=https://www.dwo.nl/servlet/dwodsaccess
serverUrlPath=/dwo/
resourceUrlPath=http://cdn.dwo.nl/resources
jarUrlPath=http://cdn.dwo.nl/jars/
httpAuthentication=BASIC
