<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>nl.numworx.uploadwidget</groupId>
    <artifactId>UploadWidget-parent</artifactId>
    <version>2.5.47-SNAPSHOT</version>
  </parent>
  <artifactId>uploadwidgetrm</artifactId>
  <name>Upload Widget Resource Manager</name>
	<properties>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
	</properties>
  <dependencies>
		<dependency>
    		<groupId>javax.activation</groupId>
    		<artifactId>activation</artifactId>
    		<version>1.1.1</version>
    		<optional>true</optional>
    		<scope>provided</scope>
		</dependency>
  	<dependency>
  		<groupId>org.c-book</groupId>
  		<artifactId>cbookif</artifactId>
  		<version>1.0.2</version>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>junit</groupId>
  		<artifactId>junit</artifactId>
  		<version>4.13.1</version>
  		<scope>test</scope>
  	</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>DWO-commons-lib</artifactId>
			<scope>provided</scope>
		</dependency>
  	<dependency>
		<groupId>fi.wiskopdr.beans</groupId>
		<artifactId>wiskopdrbeans</artifactId>
		<version>1.0.3-SNAPSHOT</version>
		<scope>provided</scope>
  	</dependency>
  	  </dependencies>
  <build>
  	<finalName>${project.artifactId}</finalName>
		<plugins>
        <plugin>   
		  <groupId>org.apache.felix</groupId>
		  <artifactId>maven-bundle-plugin</artifactId>
          <version>2.5.3</version>
		  <executions>
		    <execution>
		      <id>bundle-manifest</id>
		      <phase>process-classes</phase>
		      <goals>    
		        <goal>manifest</goal>
		      </goals>   
		    </execution>
		  </executions>
       	  <configuration>
       	    <niceManifest>true</niceManifest>
          	<instructions>
 				<_snapshot>${osgi.qualifier}</_snapshot>
          		<Bundle-SymbolicName>nl.numworx.uploadwidget.rm</Bundle-SymbolicName>
 				<Export-Package>nl.numworx.uploadwidget.rm</Export-Package>
          	</instructions>
          </configuration>
         </plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.4</version>
				<configuration>
					<archive>
						<manifestFile>target/classes/META-INF/MANIFEST.MF</manifestFile>
					</archive>
				</configuration>
			</plugin>
		</plugins>
  </build>
</project>
