<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.uu.fi.dwo</groupId>
        <artifactId>dwo.master.pom</artifactId>
        <version>3.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>dwo</artifactId>
    <packaging>pom</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jdk.version>8</jdk.version>
        <jdk>${env.JAVA_HOME_8}</jdk>
        <maven.javadoc.failOnError>false</maven.javadoc.failOnError>
        <maven.javadoc.skip>true</maven.javadoc.skip>
        <chatGWTVersion>2.5.26</chatGWTVersion>
        <tomcat7.version>7.0.108</tomcat7.version>
    </properties>
    
    <!-- should move project role names here that fall in the full project scope -->
    <modules>
<!--	   <module>../Register</module>-->
       <module>../DWO-rest-lib</module> 
<!--        <module>../DWO-gwt-lib</module> -->
<!--   	   <module>../Account</module> -->
<!--  	   <module>../DWOformule</module> -->
<!--  	 	<module>../DWOmAccess</module> -->
       <module>../DWO-commons-lib</module>
<!--         <module>../DWO-jclient-lib</module> -->
   	 	<module>../DWO-apps</module>
<!--  		<module>../chatgwt</module> -->
 	 	<module>../DWOGwtClient</module> 
<!--   	 	<module>../DWOinteraction</module> -->
        <module>../DWOJClient</module>
       	<module>../DWOServer</module> 
     	<module>../DWOplayer</module>
<!--         <module>../edexml</module> -->
<!--         <module>../KeyboardGWT</module> -->
<!--      	<module>../UploadWidget</module> -->
<!--       	<module>../WriteMathGWT</module> -->
<!-- 	<module>../osiris-import</module> -->
<!--  		<module>../notebook</module> -->
        <module>../oauth2client</module>
        <module>../EBServer</module>
<!--         <module>../schoolyear-jclient-lib</module> -->
<!--        <module>../schoolyear-war</module> -->
<!-- 	    <module>../redis-config</module> -->
<!-- 	    <module>../WiskOpdrGWT</module> -->
<!-- 	    <module>../gwtpatch</module> -->
    </modules>
    
    <name>${project.build.finalName}</name>
    
    <dependencyManagement>
    	<dependencies>
    		<dependency>
    			<artifactId>dwo-rest-lib</artifactId>
    			<groupId>nl.uu.fi.dwo.rest</groupId>
    			<version>3.0.1-SNAPSHOT</version>
    		</dependency>
    		<dependency>
    			<artifactId>dwo-rest-lib</artifactId>
    			<groupId>nl.uu.fi.dwo.rest</groupId>
    			<version>3.0.1-SNAPSHOT</version>
			<classifier>sources</classifier>
    		</dependency>
    		<dependency>
    			<groupId>nl.uu.fi.dwo</groupId>
    			<artifactId>dwo-commons-lib</artifactId>
    			<version>3.0.1-SNAPSHOT</version>
    		</dependency>
    		<dependency>
    			<groupId>nl.uu.fi.dwo.rest</groupId>
    			<artifactId>dwo-jclient-lib</artifactId>
    			<version>2.5.48</version>
    		</dependency>
        <dependency>
            <groupId>nl.uu.fi.dwo</groupId>
            <artifactId>dwo-gwt-lib</artifactId>
            <version>2.5.48</version>
        </dependency>
        <dependency>
            <groupId>nl.uu.fi.dwo</groupId>
            <artifactId>dwo-gwt-lib</artifactId>
            <version>2.5.48</version>
            <classifier>sources</classifier>
        </dependency>
        <dependency>
        	<groupId>nl.uu.fi.dwo</groupId>
        	<artifactId>dwoserver</artifactId>
        	<version>3.0.1-SNAPSHOT</version>
        	<type>war</type>
        </dependency>
         <dependency>
        	<groupId>nl.uu.fi.dwo</groupId>
        	<artifactId>dwoserver</artifactId>
        	<version>3.0.1-SNAPSHOT</version>
        	<classifier>classes</classifier>
        </dependency>
         <dependency>
         	<groupId>nl.uu.fi.dwo</groupId>
         	<artifactId>dwojclient</artifactId>
         	<version>3.0.1-SNAPSHOT</version>
         </dependency>
         <dependency>
         	<groupId>fi.beans</groupId>
         	<artifactId>numworxlf</artifactId>
         	<version>2.5.48</version>
         </dependency>
		<dependency>
			<groupId>nl.numworx.swingbrowser</groupId>
			<artifactId>swingbrowser-api</artifactId>
			<version>0.0.20</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx.swingbrowser</groupId>
			<artifactId>swingbrowser-jxb</artifactId>
			<version>0.0.20</version>
		</dependency>
		<dependency>
	  		<groupId>nl.uu.fi.dwo.mobile</groupId>
	  		<artifactId>dwoplayer</artifactId>
	  		<version>3.0.1-SNAPSHOT</version>
	  		<classifier>classes</classifier>		
		</dependency>
 		<dependency>
	  		<groupId>nl.uu.fi.dwo.mobile</groupId>
	  		<artifactId>dwoplayer</artifactId>
	  		<version>3.0.1-SNAPSHOT</version>
	  		<classifier>sources</classifier>		
		</dependency>
 		<dependency>
	  		<groupId>nl.uu.fi.dwo.mobile</groupId>
	  		<artifactId>dwoplayer</artifactId>
	  		<version>3.0.1-SNAPSHOT</version>
  			<type>war</type>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<version>2.5.48</version>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<scope>provided</scope>
			<version>2.5.48</version>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>formule</artifactId>
			<version>2.5.48</version>
		</dependency>
	   	<dependency>
	   		<groupId>nl.numworx.schoolyear</groupId>
	   		<artifactId>schoolyear-jclient-lib</artifactId>
	   		<version>2.5.48</version>
	   	</dependency>
		<dependency>
    		<groupId>nl.uu.fi.dwo.rest</groupId>
			<artifactId>redis-config</artifactId>
			<version>2.5.48</version>
		</dependency>
		<dependency>
  			<groupId>nl.numworx.uploadwidget</groupId>
  			<artifactId>uploadwidget-common</artifactId>
			<version>2.5.48</version>
		</dependency>
		<dependency>
			<groupId>fi.wiskopdrgwt</groupId>
			<artifactId>wiskopdrgwt</artifactId>
			<version>2.5.48</version>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>lineairealgebra</artifactId>
			<version>2.5.48</version>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>lineairealgebra</artifactId>
			<version>2.5.48</version>
			<classifier>sources</classifier>
		</dependency>
		<!-- dwo-apps en writemathgwt -->
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>dwo-apps</artifactId>
			<version>3.0.1-SNAPSHOT</version>
			<classifier>classes</classifier>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>dwo-apps</artifactId>
			<version>3.0.1-SNAPSHOT</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>fi.writemathgwt</groupId>
			<artifactId>writemathgwt</artifactId>
			<version>2.5.48</version>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>fi.dwo.eawt</artifactId>
			<version>2.5.48</version>
		</dependency>

    	</dependencies>
    </dependencyManagement>

    <scm>
        <developerConnection>scm:git:git@github.com:UtrechtUniversity/numworx-dwo-project.git</developerConnection>
    </scm>

	<repositories>
        <repository>
		  <id>vaadin-addons</id>
		  <url>https://maven.vaadin.com/vaadin-addons/</url>
	    </repository>		
	</repositories>
    <build>
        <plugins>
    		<plugin>
            	<groupId>external.atlassian.jgitflow</groupId>
            	<artifactId>jgitflow-maven-plugin</artifactId>
            	<version>1.0-m5.1</version>
            	<configuration>
                	<!-- see goals wiki page for configuration options -->
                	<flowInitContext>
             			<developBranchName>develop</developBranchName>  
             			<masterBranchName>main</masterBranchName>    	
                	</flowInitContext>
                	<localOnly>false</localOnly>
                	<allowSnapshots>false</allowSnapshots>
                	<enableSshAgent>true</enableSshAgent>
                	<noDeploy>true</noDeploy>
                	<autoVersionSubmodules>true</autoVersionSubmodules>
            	</configuration>
			  <dependencies>
			    <dependency>
			      <groupId>com.jcraft</groupId>
			      <artifactId>jsch</artifactId>
			      <version>0.1.54</version>
			    </dependency>
				<dependency>
				  <groupId>net.java.dev.jna</groupId>
				  <artifactId>jna-platform</artifactId>
				  <version>5.12.1</version>
				</dependency>
			  </dependencies>
        	</plugin>
         </plugins>
         <pluginManagement>
         	<plugins>
         		<plugin>
         			<artifactId>maven-war-plugin</artifactId>
         			<version>3.2.3</version>
         		</plugin>
			<plugin>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.4.0</version>
			</plugin>
         	</plugins>
         
         </pluginManagement>
    </build>
    
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>2.6</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>2.6</version>
                <reportSets>
                    <reportSet>
                        <reports><!-- select reports -->
                            <report>index</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.9</version>
                <reportSets>
                    <reportSet><!-- by default, id = "default" -->
                        <reports><!-- select non-aggregate reports -->
                            <report>javadoc</report>
                            <report>test-javadoc</report>
                        </reports>
                    </reportSet>
                    <reportSet><!-- aggregate reportSet, to define in poms having modules -->
                        <id>aggregate</id>
                        <inherited>false</inherited><!-- don't run aggregate in child modules -->
                        <reports>
                            <report>aggregate</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5.3</version>
            </plugin>            
        </plugins>
    </reporting>
    <profiles> <!-- profiles used in modules and jenkins -->
    	<profile>
    		<id>DWO2player</id>
    	</profile>
    	<profile>
    		<id>test</id>
    	</profile>
	<profile>
		<id>github</id>
		<repositories>
        	  <repository>
          	     <id>numworx-vendor-geogebra</id>
          	     <snapshots>
              		<enabled>true</enabled>
          	     </snapshots>
          	     <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-vendor-geogebra</url>
        	  </repository>
                    <repository>
                     <id>numworx-dwo-openmath</id>
                     <snapshots>
                        <enabled>true</enabled>
                     </snapshots>
                     <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-openmath</url>
                  </repository>
                  <repository>
					  <id>vaadin-addons</id>
					  <url>https://maven.vaadin.com/vaadin-addons/</url>
				  </repository>
		</repositories>
	</profile>
	<profile>
		<id>repos</id>
		<repositories>	<!-- als de mirror uit staat -->
           <repository>
             <id>vaadin-addons</id>
             <url>https://maven.vaadin.com/vaadin-addons/</url>
           </repository>
        <repository>
          <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-vendor-jxbrowser</url>
          <id>numworx-vendor-jxbrowser</id>
          <snapshots>
                <enabled>true</enabled>
          </snapshots>
        </repository>
	    </repositories>		
	</profile>
    </profiles>
</project>
