<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.uu.fi.dwo</groupId>
        <artifactId>dwo</artifactId>
        <relativePath>../DWO/pom.xml</relativePath>
        <version>3.0.0</version>
    </parent>
    <!-- Adjust artifact, name and description for new projects -->
    <groupId>nl.uu.fi.dwo.lms</groupId>
    <artifactId>dwogwtclient</artifactId>
    <packaging>war</packaging>

    <url>http://www.dwo.nl</url>
    <!-- Update year to current when starting a new project -->
    <inceptionYear>2017</inceptionYear> 
    <organization>
        <name>Freudenthal Institute</name>
        <url>http://www.uu.nl/onderzoek/freudenthal-instituut</url>
    </organization>
    
    <properties>
        <webappDirectory>${project.build.directory}/${project.build.finalName}</webappDirectory>
        <maven.javadoc.failOnError>false</maven.javadoc.failOnError>
        <maven.test.skip>true</maven.test.skip>
        <!-- Convenience property to set the GWT version -->
        <gwt.version>2.10.0</gwt.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <daggerVersion>2.42</daggerVersion>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <gwt.style>OBFUSCATED</gwt.style>
        <maven.test.skip>true</maven.test.skip>
        <context.xml>context-dwo_devel.xml</context.xml>
        <copy.ui.skip>true</copy.ui.skip>
        <registerVersion>2.5.48</registerVersion>
        <gwtModule>nl.uu.fi.dwo.lms.gwtclient.gwtclient</gwtModule>
        <smModule>nl.uu.fi.dwo.lms.gwtclient.smclient</smModule>
        <local.dwo>/dwo</local.dwo>
    </properties>

    <!-- Running with Maven -->
    <!-- mvn clean package -->
    <!-- mvn tomcat7:run package -->
    <!-- mvn gwt:run-codeserver - start gwt code server -->
    <!-- goto http://localhost:8080 -->
  
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.gwt</groupId>
                <artifactId>gwt</artifactId>
                <version>${gwt.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
		<dependency><!-- before GWT -->
			<groupId>org.vectomatic</groupId>
			<artifactId>lib-gwt-svg</artifactId>
			<version>0.5.15</version>
		</dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-user</artifactId>
            <!-- "provided" so that we don't deploy -->
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-dev</artifactId>
            <!-- "provided" so that we don't deploy -->
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-codeserver</artifactId>
            <!-- "provided" so that we don't deploy -->
            <scope>provided</scope>
        </dependency>

        <!-- Unit tests -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.1</version>
            <scope>test</scope>
        </dependency>

        <!-- dwo dependencies -->
        <dependency>
            <groupId>nl.uu.fi.dwo</groupId>
            <artifactId>dwo-gwt-lib</artifactId>
        </dependency>
        <dependency>
            <groupId>nl.uu.fi.dwo</groupId>
            <artifactId>dwo-gwt-lib</artifactId>
            <classifier>sources</classifier>
        </dependency>
        <dependency>
            <groupId>nl.uu.fi.dwo.rest</groupId>
            <artifactId>dwo-rest-lib</artifactId>
        </dependency>      
        <dependency>
            <groupId>nl.uu.fi.dwo.rest</groupId>
            <artifactId>dwo-rest-lib</artifactId>
            <classifier>sources</classifier>
        </dependency>
        
        <dependency>
            <groupId>com.owlike</groupId>
            <artifactId>genson</artifactId>
            <version>1.6</version>
        </dependency> 
        <dependency>
            <groupId>com.github.nmorel.gwtjackson</groupId>
            <artifactId>gwt-jackson</artifactId>
            <version>0.14.2</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.squareup</groupId>
                    <artifactId>javapoet</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.mitre.dsmiley.httpproxy</groupId>
            <artifactId>smiley-http-proxy-servlet</artifactId>
            <version>1.7</version>
            <scope>runtime</scope>
        </dependency>
        <!-- code injection at compile time -->
        <dependency>
            <groupId>com.google.dagger</groupId>
            <artifactId>dagger-gwt</artifactId>
            <version>${daggerVersion}</version>
        </dependency>
        <dependency>
            <groupId>com.google.dagger</groupId>
            <artifactId>dagger-compiler</artifactId>
            <version>${daggerVersion}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
        	<groupId>nl.uu.fi.dwo.lms</groupId>
        	<artifactId>dwogwtclienthtmlui</artifactId>
        	<version>3.0.0</version>
        	<scope>runtime</scope>
        	<type>war</type>
        </dependency>
		<dependency>
			<groupId>org.vectomatic</groupId>
			<artifactId>lib-gwt-file</artifactId>
			<version>0.3.8</version>
		</dependency>
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.0</version>
			<classifier>sources</classifier>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.lms</groupId>
			<artifactId>chatgwt-shared</artifactId>
			<version>2.5.48</version>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.lms</groupId>
			<artifactId>chatgwt-shared</artifactId>
			<version>2.5.48</version>
			<classifier>sources</classifier>
		</dependency>
    </dependencies>
    
    <build>
        <!-- Output classes directly into the webapp, so that IDEs and "mvn process-classes" update them in DevMode -->
        <outputDirectory>${project.build.directory}/${project.build.finalName}/WEB-INF/classes</outputDirectory>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>1.3</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>create</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!--
                     doCheck and doUpdate actually talk to repository if it's true,
                     Check would check that there are no local changes.
                     Update would update it
                    -->
                    <doCheck>false</doCheck>
                    <doUpdate>false</doUpdate>
               </configuration>
            </plugin>                   
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>templating-maven-plugin</artifactId>
                <version>1.0.0</version>
                <executions>
                    <execution>
                        <id>filter-src</id>
                        <goals>
                            <goal>filter-sources</goal>
                        </goals>
                        <configuration>
                            <sourceDirectory>${basedir}/src/main/java-templates</sourceDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>     
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>${gwt.version}</version>
                <executions>
                    <execution>
                        <!-- gwt:run-codeserver with options, cmdline options needed
                        -Dgwt.compiler.generateJsInteropExports=true 
                        -Dgwt.compiler.incremental=false 
                        -Dgwt.compiler.precompile=false 
                        -Dgwt.codeserver.generateJsInteropExports=true - -debug -->
                        <!-- Paste into netbeans config window.
                        gwt.style=DETAILED
                        gwt.compiler.generateJsInteropExports=true
                        gwt.compiler.incremental=false
                        gwt.compiler.precompile=false
                        gwt.codeserver.generateJsInteropExports=true
                        -->
                        <configuration>
                        	<localWorkers>1</localWorkers>
                            <incremental>false</incremental>
                            <precompile>false</precompile>
                            <superDevMode>true</superDevMode>
                            <sourceLevel>1.8</sourceLevel>
                            <generateJsInteropExports>true</generateJsInteropExports>
                            <modules>
                            	<module>${gwtModule}</module>
                            	<module>${smModule}</module>
                            </modules>
                            <i18nConstantsBundles>
                                <i18nConstantsBundle>nl.uu.fi.dwo.lms.gwtclient.gwt.locale.GwtClientMessages</i18nConstantsBundle>
                            </i18nConstantsBundles>
                            <i18nConstantsWithLookupBundles>
								<i18nConstantsWithLookupBundle>nl.uu.fi.dwo.lms.gwtclient.gwt.locale.GwtClientModulesOnly</i18nConstantsWithLookupBundle>
							</i18nConstantsWithLookupBundles>
                        </configuration>                           
                        <goals>
                            <goal>i18n</goal>
                            <goal>compile</goal>
                            <goal>generateAsync</goal>
                            <goal>test</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin> 
             <plugin> <!-- attach-sources voor GWT -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.4</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>         
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>exploded</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <warSourceDirectory>war</warSourceDirectory>
                    <attachClasses>true</attachClasses>
                    <webappDirectory>${webappDirectory}</webappDirectory> 
                    <packagingExcludes>WEB-INF/lib/**,WEB-INF/classes/**</packagingExcludes>
                    <!-- exclude angular 2 dir: /src/main/ngapp -->
                    <dependentWarExcludes>css/scss/**</dependentWarExcludes>                
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.1</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.dagger</groupId>
                            <artifactId>dagger-compiler</artifactId>
                            <version>${daggerVersion}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.cargo</groupId>
                <artifactId>cargo-maven2-plugin</artifactId>
                <version>1.6.4</version>
                <configuration>
                    <container>
                        <containerId>tomcat9x</containerId>
                        <!--<output>target/catalina-output.log</output>-->
                        <artifactInstaller>
                            <groupId>org.apache.tomcat</groupId>
                            <artifactId>tomcat</artifactId>
                            <version>9.0.87</version>
                        </artifactInstaller>
                    </container>
                    <dependencies>
					<dependency>
					  <groupId>mysql</groupId>
					  <artifactId>mysql-connector-java</artifactId>
					  <version>8.0.28</version>
					</dependency>                    </dependencies>           
                    <configuration>
                        <type>standalone</type>            
                        <home>
                            ${project.build.directory}/apache-tomcat
                        </home>
                        <properties>
                            <cargo.servlet.port>8080</cargo.servlet.port>
                            <cargo.logging>low</cargo.logging>
                        </properties>
                        
                    </configuration>
                    <deployables>
                        <deployable>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                            <type>war</type>
                            <properties>
                                <context>/</context>
                            </properties>
                        </deployable>
                        <!--    useful in case war is part of compiled local code, hence no version in deployable.-->
                        <deployable>
                            <groupId>nl.uu.fi.dwo</groupId>
                            <artifactId>dwoserver</artifactId> 
                            <type>war</type>    
                            <properties>
                                <context>{local.dwo}</context>
                            </properties>
                        </deployable>
                    </deployables>
                    <configfiles>
                        <configfile>
                            <file>src/test/tomcat/${context.xml}</file>
                            <todir>${project.build.directory}/apache-tomcat/conf/Catalina/localhost/</todir>
                            <tofile>context.xml.default</tofile>
                        </configfile>     
                    </configfiles>                                         
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>5.1.49</version>
                    </dependency>
                </dependencies>    
            </plugin>
            <plugin>
                <groupId>org.apache.tomcat.maven</groupId>
                <artifactId>tomcat7-maven-plugin</artifactId>
                <version>2.2</version>
                <configuration>
                    <server>TomcatServer</server>
                    <path>/</path>
                    <systemProperties>
                    	<CDN_HOST>localhost:8082</CDN_HOST>
						<CDNURL>http://localhost:8082</CDNURL>
                    	<DWO_ENV>testkiosk</DWO_ENV>
                    	<ALLOW_ORIGIN>http://localhost:8080</ALLOW_ORIGIN>
<!--                    	<XAPI_ENDPOINT>http://localhost:8089/xapi/</XAPI_ENDPOINT>-->
                    	<XAPI_AUTH>bXlfa2V5Om15X3NlY3JldA==</XAPI_AUTH>               
                    	<AZ_ENDPOINT>http://127.0.0.1:10000/devstoreaccount1/</AZ_ENDPOINT>
                    	<AZ_SHAREDKEY>Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==</AZ_SHAREDKEY>
                    	<S3_BUCKET>devstoreaccount1</S3_BUCKET>      
                    </systemProperties>
                    <warSourceDirectory>target/${project.artifactId}-${project.version}</warSourceDirectory>
					<contextFile>src/test/tomcat/${context.xml}</contextFile>
                    <webapps>
                        <webapp>
                            <groupId>nl.uu.fi.dwo</groupId>
                            <artifactId>dwoserver</artifactId>
                            <version>${project.version}</version>
                            <type>war</type>    
                            <asWebapp>true</asWebapp> 
                            <contextPath>${local.dwo}</contextPath>
                            <contextFile>src/test/tomcat/${context.xml}</contextFile>
                        </webapp>
                        <webapp>
                            <groupId>fi.dwo</groupId>
                            <artifactId>dwo-apps</artifactId> 
                            <version>2.5.50</version> 
                            <type>war</type>    
                            <asWebapp>true</asWebapp> 
                            <contextPath>/dwo/apps</contextPath>
                        </webapp>
                       <webapp>
                            <groupId>nl.uu.fi.dwo.mobile</groupId>
                            <artifactId>dwoplayer</artifactId>
                            <version>${project.version}</version>
                            <type>war</type>
                            <contextPath>/dwo/tablet</contextPath>
                            <asWebapp>true</asWebapp>
                        </webapp>
                        <webapp>
                        	<groupId>nl.uu.fi.dwo.register</groupId>
							<artifactId>register</artifactId>
							<version>${registerVersion}</version>
                            <type>war</type>
                            <contextPath>/dwo/register</contextPath>
                            <asWebapp>true</asWebapp>
                        </webapp>
                        <webapp>
                          <groupId>fi.servlet</groupId>
  						  <artifactId>ideas-war</artifactId>
 						  <version>0.0.16</version>
                          <type>war</type>
                          <contextPath>/ideas</contextPath>
                          <asWebapp>true</asWebapp>              
                        </webapp>
                         <webapp>
						    <groupId>nl.numworx.uploadwidget</groupId>
						    <artifactId>uploadwidget-local</artifactId>
						    <version>2.5.48</version>
                            <type>war</type>
                            <contextPath>/dwo/dav/upload</contextPath>
                            <asWebapp>true</asWebapp>
                         </webapp>
                         <webapp>
						    <groupId>nl.numworx.xapi</groupId>
						    <artifactId>xapiserver</artifactId>
  							<version>2.5.48</version>
							<contextPath>/data/xAPI</contextPath>
                            <type>war</type>
							<asWebapp>true</asWebapp>
						 </webapp>
                    </webapps>                         
                </configuration> 
                <dependencies>
 		<dependency>
		    <groupId>javax.xml.bind</groupId>
		    <artifactId>jaxb-api</artifactId>
		    <version>2.3.0</version>
		</dependency>
                   <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>5.1.49</version>
                    </dependency>
<!-- werkt niet, omdat cache-api in de wars zit en die gaat voor. -->
					<dependency>
					    <groupId>javax.cache</groupId>
					    <artifactId>cache-api</artifactId>
					    <version>1.1.1</version>
					</dependency>
                    <dependency>
                        <groupId>org.apache.tomcat.embed</groupId>
                        <artifactId>tomcat-embed-core</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-util</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-coyote</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-api</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-jdbc</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-dbcp</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-servlet-api</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-jsp-api</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-jasper</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-jasper-el</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-el-api</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-catalina</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-tribes</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-catalina-ha</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-annotations-api</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat</groupId>
                        <artifactId>tomcat-juli</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>

                    <dependency>
                        <groupId>org.apache.tomcat.embed</groupId>
                        <artifactId>tomcat-embed-logging-juli</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.tomcat.embed</groupId>
                        <artifactId>tomcat-embed-logging-log4j</artifactId>
                        <version>${tomcat7.version}</version>
                    </dependency>                                
				<dependency>
				    <groupId>org.redisson</groupId>
				    <artifactId>redisson-all</artifactId>
				    <version>3.22.1</version>
				</dependency>
				<dependency>
    				<groupId>nl.uu.fi.dwo.rest</groupId>
					<artifactId>redis-config</artifactId>
					<version>2.5.48</version>
				</dependency>
                </dependencies>
            </plugin>            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>copy-HtmlUi</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                        	<skip>${copy.ui.skip}</skip>
                            <outputDirectory>${project.build.directory}/${project.build.finalName}/</outputDirectory>
                            <overwrite>true</overwrite>
                            <resources>
                                <resource>
                                    <directory>../DwoGwtClientHtmlUi/src/main/html</directory>
                                    <includes>
                                        <include>helppage/**</include>
                                        <include>css/**</include>
                                        <include>js/**</include>
                                        <include>third-party/**</include>
                                        <include>images/**</include>
                                        <include>index.html</include>
                                        <include>library.html</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>            
        </plugins>
        <finalName>${project.artifactId}-${project.version}</finalName>
    </build>

    <description>DwoGwtClient</description>
    
    
    <profiles>
		<profile>
			<id>running11</id>
			<activation>
				<jdk>[9,)</jdk>
			</activation>
			<dependencies>
				<dependency>
				    <groupId>javax.annotation</groupId>
				    <artifactId>javax.annotation-api</artifactId>
				    <version>1.3.2</version>
				</dependency>
			</dependencies>
		</profile>
    	<profile>
    		<id>debug</id>
    		<properties>
    			<gwtModule>nl.uu.fi.dwo.lms.gwtclient.gwtclientDebug</gwtModule>
        		<gwt.style>PRETTY</gwt.style>
  				<gwt.compiler.localWorkers>3</gwt.compiler.localWorkers>
  		</properties>
    	</profile>
    	    <profile>
		        <id>aarch64-macos-users</id>
		        <activation>
		            <os>
		                <family>mac</family>
		                <arch>aarch64</arch>
		            </os>
		        </activation>
		        <dependencies>
		            <dependency>
		                <groupId>io.netty</groupId>
		                <artifactId>netty-resolver-dns-native-macos</artifactId>
		                <classifier>osx-aarch_64</classifier>
		                <version>4.1.86.Final</version>
		                <scope>runtime</scope>
		                <optional>true</optional>
		            </dependency>
		        </dependencies>
		    </profile>
    	    <profile>
		        <id>x86_64-macos-users</id>
		        <activation>
		            <os>
		                <family>mac</family>
		                <arch>x86_64</arch>
		            </os>
		        </activation>
		        <dependencies>
		            <dependency>
		                <groupId>io.netty</groupId>
		                <artifactId>netty-resolver-dns-native-macos</artifactId>
		                <classifier>osx-x86_64</classifier>
		                <version>4.1.86.Final</version>
		                <scope>runtime</scope>
		                <optional>true</optional>
		            </dependency>
		        </dependencies>
		    </profile>
		    <profile>
				<id>github</id>
				<repositories>
					<repository>
						<id>numworx-dwo-gwtclienthtmlui</id>
						<url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-gwtclienthtmlui</url>
						<snapshots>
							<enabled>true</enabled>
						</snapshots>
					</repository>			
			 	    <repository>
				      <id>numworx-dwo-project</id>
				      <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-project</url>
				      <snapshots>
						  <enabled>true</enabled>
					  </snapshots>
			 	    </repository>
				</repositories>
			</profile>
    </profiles>
</project>
