<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.uu.fi.dwo</groupId>
        <artifactId>dwo</artifactId>
        <relativePath>../DWO</relativePath>
        <version>2.5.49-SNAPSHOT</version>
    </parent>
	<groupId>nl.uu.fi.dwo.keyboard</groupId>
	<artifactId>keyboardgwt</artifactId>
	<name>Keyboard</name>
	<dependencies>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<version>${gwtVersion}</version>
		</dependency>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-dev</artifactId>
			<version>${gwtVersion}</version>
			<scope>test</scope>
		</dependency>
<!-- 		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
		</dependency>
 -->		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>fi.writemathgwt</groupId>
			<artifactId>writemathgwt</artifactId>
			<version>2.5.49-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>fi.wiskopdrgwt</groupId>
			<artifactId>wiskopdrgwt</artifactId>
			<version>2.5.49-SNAPSHOT</version>
			<exclusions>
				<exclusion>
					<artifactId>IdeasGWT</artifactId>
					<groupId>nl.uu.fi.dwo.ideas</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.googlecode.mgwt/mgwt -->

	</dependencies>
	<build>
		<resources>
			<resource>
				<directory>src</directory>
			</resource>
		</resources>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>${gwtVersion}</version>
				<configuration>
					<module>${project.groupId}.${project.artifactId}</module>
					<i18nConstantsBundles>
						<i18nConstantsBundle>nl.uu.fi.dwo.keyboard.client.i18n.Key</i18nConstantsBundle>
					</i18nConstantsBundles>
				</configuration>
				<executions>
					<execution>
						<id>i18n</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>i18n</goal>
						</goals>
					</execution>
				</executions>			
			</plugin>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.0.2</version>
        <executions>
          <execution>
            <id>copy-resources</id>
            <phase>process-classes</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.outputDirectory}</outputDirectory>
              <resources>          
                <resource>
                  <directory>${basedir}/target/generated-sources/gwt</directory>
                  <filtering>false</filtering>
                </resource>
              </resources>              
            </configuration>            
          </execution>
        </executions>
      </plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>2.5.3</version>
			</plugin>
		</plugins>
	</build>
	<description>Keyboard voor desktop en tablet
DWO en Noordhoff/Plantyn variant</description>
	<properties>
		<maven.javadoc.failOnError>false</maven.javadoc.failOnError>
		<interactionVersion>0.1.4</interactionVersion>
  		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  		<gwtVersion>2.10.0</gwtVersion>
  		<maven.compiler.source>1.8</maven.compiler.source>
  		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
</project>
