#See Dwo2ExceptionCode for details.
Dwo2ExceptionCode.User_AuthenticationError = Invalid authentication details.
Dwo2ExceptionCode.Rest_InterfaceError = Invalid REST-request.

#Rest internal errors
Dwo2ExceptionCode.Rest_InternalError=An internal error occurred, please notify the software developer.

#Rest Registration errors
Dwo2ExceptionCode.Rest_Registration_UserName_exists=That username already exists in the database.