//Source file:
//N:\\transferzone\\intern\\Afstudeerders_basw_thijsk\\April\\Implementatie\\fi\\dwo\\client\\system\\Text_en.java
package fi.dwo.commons.system.text;

import java.util.ListResourceBundle;

import fi.dwo.commons.system.TextMapper;

public class Text_cn extends ListResourceBundle {

    private final Object[][] contents = {
        {TextMapper.USER_GUEST, "來賓"},
        {TextMapper.BTN_LOGIN, "登入"},
        {TextMapper.BTN_CANCEL, "取消"},
        {TextMapper.BTN_NO, "否"},
        {TextMapper.BTN_OK, "OK"},
        {TextMapper.BTN_YES, "是"},
        {TextMapper.BTN_CLOSE, "關閉"},
        {TextMapper.DLG_CONFIRM, "確定"},
        {TextMapper.DLG_ENTER_INPUT, "輸入"},
        {TextMapper.DLG_MESSAGE, "訊息"},
        {TextMapper.EX_UNKNOWN_ERROR, "發生內部錯誤"},
        {TextMapper.EXR_USER_EXISTS, "此登入名稱已被使用"},
        {TextMapper.EXR_USER_EXISTS2, "登入名稱 {0} 已被使用"},
        {TextMapper.EXR_WRONG_SECOND_PASSWORD, "登入密碼不符"},
        {TextMapper.EXR_WRONG_USERNAME_PASSWORD, "沒有此登入名稱或密碼"},
        {TextMapper.EXR_UNKNOWN_SCHOOLGROUP, "學校名稱/機構/密碼不符"},
        {TextMapper.EXR_MANDATORY, "沒有填寫 {1} 內的 {0}。這是必填項"},
        {TextMapper.EXR_WRONG_FORMAT, "{1} 內的 {0} 包含不可用字元"},
        {TextMapper.EXR_WRONG_EMAILFORMAT, "{1} 內的 {0} 是不可用"},
        {TextMapper.EXC_CLASS_EXISTS, "此班別已被使用"},
        {TextMapper.EXS_SCHOOL_EXISTS, "此學校名稱已被使用"},
        {TextMapper.EXL_UNKNOWN_USER, "未找到學校名稱及密碼"},
        {TextMapper.EXC_COURSE_EXISTS, "這模組已被使用"},
        {TextMapper.EXS_SCO_EXISTS, "這活動已被使用"},
        {TextMapper.EXS_NO_APPLET, "未找到應用程式"},
        {TextMapper.GUI_WAIT_A_MOMENT, "請等候"},
        {TextMapper.GUIW_LOGINDATA, "登入資料"},
        {TextMapper.GUIW_USERNAME, "登入名稱"},
        {TextMapper.GUIW_PASSWORD, "密碼"},
        {TextMapper.GUIW_WELCOME, "歡迎"},
        {TextMapper.GUIW_GUESTLOGIN, "以來賓身份登入"},
        {TextMapper.GUIW_REGISTER, "登記"},
        {TextMapper.GUIW_MSG_WORK_NOT_SAVE, "你的工作未被保存"},
        {TextMapper.GUIW_MSG_REGISTER_NEW, "以新成員登記"},
        {TextMapper.GUIW_BTN_GUESTLOGIN, "以來賓身份登入"},
        {TextMapper.GUIW_BTN_LOGIN, "登入"},
        {TextMapper.GUIW_BTN_REGISTER, "登記"},
        {TextMapper.GUIW_ERR_LOGIN, "登入錯誤"},
        {TextMapper.GUIR_REGISTER, "登記"},
        {TextMapper.GUIR_REGISTERINFO, "新用戶登記"},
        {TextMapper.GUIR_PERSONALINFO, "個人資料"},
        {TextMapper.GUIR_SCHOOLINFO, "學校資料"},
        {TextMapper.GUIR_USERNAME, "登入名稱"},
        {TextMapper.GUIR_PASSWORD, "密碼"},
        {TextMapper.GUIR_RE_PASSWORD, "確定密碼"},
        {TextMapper.GUIR_FIRSTNAME, "名"},
        {TextMapper.GUIR_MIDDLENAME, "中間名"},
        {TextMapper.GUIR_LASTNAME, "姓"},
        {TextMapper.GUIR_EMAIL, "電郵地址"},
        {TextMapper.GUIR_SCHOOLLOGIN, "學校登入"},
        {TextMapper.GUIR_SCHOOLGROUP, "我是"},
        {TextMapper.GUIR_SCHOOLPASSWORD, "密碼"},
        {TextMapper.GUIR_BTN_REGISTER, "登記"},
        {TextMapper.GUIR_BTN_RESET, "重設"},
        {TextMapper.GUIR_BTN_BACK, "返回模組"},
        {TextMapper.GUIR_MSG_PROVIDED_SCHOOL, "由學校提供資料"},
        {TextMapper.GUIR_OPT_SELECT_GROUP, "請選擇"},
        {TextMapper.GUIR_OPT_STUDENT, "學生"},
        {TextMapper.GUIR_OPT_TEACHER, "老師"},
        {TextMapper.GUIR_OPT_ADMIN, "管理員"},
        {TextMapper.GUIR_OPT_SCHOOLADMIN, "學校管理員"},
        {TextMapper.GUIR_OPT_SCHOOLCODE, "關鍵碼"},
        {TextMapper.GUIR_ERR_REGISTER, "發生錯誤"},
        {TextMapper.GUIR_MSG_REGISTERED, "你已成功登記"},
        {TextMapper.GUIM_DWO_FULL, "數碼數學環境 Digital Mathematics Environment"},
        {TextMapper.GUIM_DWO_SHORT, "DME"},
        {TextMapper.GUIM_FI_NAME, "弗賴登塔爾研究所"},
        {TextMapper.GUIM_MAIN_MENU, "模組"},
        {TextMapper.GUIL_LOGGED_IN_AS, "你已登入為"},
        {TextMapper.GUIL_NOT_LOGGED_IN, "你仍未登入"},
        {TextMapper.GUIL_BTN_LOGIN, "登入"},
        {TextMapper.GUIL_BTN_LOGOFF, "登出"},
        {TextMapper.GUIMNU_MAIN_MENU, "模組"},
        {TextMapper.GUIMNU_MY_PROFILE, "我的個人資料"},
        {TextMapper.GUIMNU_STUDENT_IN_CLASS, "班別學生"},
        {TextMapper.GUIMNU_STUDENT_NO_CLASS_0, "你仍未 "},
        {TextMapper.GUIMNU_STUDENT_NO_CLASS_1, "是班別的成員  "},
        {TextMapper.GUIMNU_STUDENT_NO_CLASS_2, "去"},
        {TextMapper.GUIMNU_STUDENT_NO_CLASS_3, "\"我的個人資料\" 及 "},
        {TextMapper.GUIMNU_STUDENT_NO_CLASS_4, "選擇班別"},
        {TextMapper.GUIMNU_CLASS_RESULTS, "班別成績"},
        {TextMapper.GUIMNU_RESULTS, "查看成績"},
        {TextMapper.GUIMNU_CLASS_MANAGEMENT, "班別管理"},
        {TextMapper.GUIMNU_SCHOOL_MANAGEMENT, "學校管理"},
        {TextMapper.GUIMNU_COURSE_MANAGEMENT, "模組管理"},
        {TextMapper.GUIMNU_MSG_ADD_CLASS, "新班別名稱"},
        {TextMapper.GUIMNU_MSG_ADD_CLASS_TITLE, "加入新班別"},
        {TextMapper.GUIMNU_MSG_ADD_SCHOOL, "新學校名稱"},
        {TextMapper.GUIMNU_MSG_ADD_SCHOOL_TITLE, "新入新學校"},
        {TextMapper.GUIMNU_USERS_SCHOOL, "學校用戶"},
        {TextMapper.GUIMNU_CLASSES_SCHOOL, "學校班別"},
        {TextMapper.GUIMNU_FEATURES_SCHOOLADMIN, "學校管理功能"},
        {TextMapper.GUIUMP_MANAGE_USERS, "管理用戶"},
        {TextMapper.GUIUMP_REMOVE_FROM_SCHOOL, "只能由學校刪除"},
        {TextMapper.GUIUMP_REMOVE_COMPLETE, "刪除全部戶口"},
        {TextMapper.GUIUMP_ADD_STUDENTS, "加入新學生"},
        {TextMapper.GUIUMP_ADD_TEACHERS, "加入新老師"},
        {TextMapper.GUIUMP_IMPORT_CLIPBOARD, "由剪貼板輸入"},
        {TextMapper.GUIUMP_MAKE_ACCOUNTS, "製作戶口"},
        {TextMapper.GUIUMP_EXTRA_ROW, "附加行"},
        {TextMapper.GUICO_HEADER, "模組"},
        {TextMapper.GUICO_SCO_LIST_TITLE, "活動"},
        {TextMapper.GUIP_MY_PROFILE, "我的個人資料"},
        {TextMapper.GUIP_REGISTERINFO, "登記資料"},
        {TextMapper.GUIP_PERSONALINFO, "個人資料"},
        {TextMapper.GUIP_SCHOOLINFO, "學校資料"},
        {TextMapper.GUIP_USERNAME, "登入名稱"},
        {TextMapper.GUIP_OLD_PASSWORD, "現行密碼"},
        {TextMapper.GUIP_PASSWORD, "新密碼"},
        {TextMapper.GUIP_RE_PASSWORD, "確認密碼"},
        {TextMapper.GUIP_FIRSTNAME, "名"},
        {TextMapper.GUIP_MIDDLENAME, "中間名"},
        {TextMapper.GUIP_LASTNAME, "姓"},
        {TextMapper.GUIP_EMAIL, "電郵地址"},
        {TextMapper.GUIP_SCHOOLLOGIN, "學校登入"},
        {TextMapper.GUIP_SCHOOLGROUP, "我是"},
        {TextMapper.GUIP_SCHOOLPASSWORD, "密碼"},
        {TextMapper.GUIP_CLASS, "班別"},
        {TextMapper.GUIP_BTN_SAVE, "保存"},
        {TextMapper.GUIP_BTN_RESET, "重設"},
        {TextMapper.GUIP_BTN_DELETE_PROFILE, "刪除戶口"},
        {TextMapper.GUIP_MSG_PROVIDED_SCHOOL, "由學校提供資料"},
        {TextMapper.GUIP_ERR_CHANGE, "發生錯誤"},
        {TextMapper.GUIP_OPT_SELECT_GROUP, "請選擇"},
        {TextMapper.GUIP_CONFIRM_REMOVE_USER, "你是否確認刪除你的戶口"},
        {TextMapper.GUIP_CONFIRM_REMOVE_USER_TITLE, "刪除戶口"},
        {TextMapper.GUIP_MSG_PROFILE_CHANGED, "你的戶口已成功更新"},
        {TextMapper.GUIPT_SCHOOL, "學校"},
        {TextMapper.GUIPT_TEACHER_FROM_CLASS, "班別老師"},
        {TextMapper.GUIPT_BTN_ADD_CLASS, "加入班別"},
        {TextMapper.GUIS_STUDENTS, "學生"},
        {TextMapper.GUIS_TEACHERS, "老師"},
        {TextMapper.GUIS_SCHOOL_MANAGEMENT, "學校管理"},
        {TextMapper.GUIS_TLTP_DELETE_SCHOOL, "刪除學校 {0} "},
        {TextMapper.GUIS_TLTP_EDIT_SCHOOL, "修改學校名稱"},
        {TextMapper.GUIS_TLTP_USERS_SCHOOL, "學生 {0}"},
        {TextMapper.GUIS_ADD_SCHOOL, "加入學校"},
        {TextMapper.GUIS_DELETE_SCHOOL, "刪除學校"},
        {TextMapper.GUIS_RENAME_SCHOOL, "修改學校名稱"},
        {TextMapper.GUIS_MSG_RENAME_SCHOOL, "輸入新的學校名稱"},
        {TextMapper.GUIS_MSG_DELETE_SCHOOL, "你是否確認刪除此學校"},
        {TextMapper.GUIS_SCHOOL_NOT_EMPTY, "此學校戶口內包含用戶，你是否確認刪除此學校"},
        {TextMapper.GUIS_SCHOOL_NOT_EMPTY_TITLE, "此學校戶口內包含用戶"},
        {TextMapper.GUIS_MSG_DELETE_STUDENT, "你是否確認在此學校戶口內刪除 {0}"},
        {TextMapper.GUIS_DELETE_STUDENT, "在此學校戶口內刪除學生"},
        {TextMapper.GUIS_NO_STUDENTS, "學校 {0} 沒有學生"},
        {TextMapper.GUIC_STUDENTS, "學生"},
        {TextMapper.GUIC_CLASS_MANAGEMENT, "班別管理"},
        {TextMapper.GUIC_TLTP_DELETE_CLASS, "刪除班別 {0} "},
        {TextMapper.GUIC_TLTP_EDIT_CLASS, "修改班別名稱"},
        {TextMapper.GUIC_TLTP_USERS_CLASS, "班別中的學生 {0}"},
        ////peter
        {TextMapper.GUIC_TLTP_ASSIGN_CLASS, "向班別指派模組 {0}"},
        ////peter

        {TextMapper.GUIC_STUDENTS, "學生"},
        {TextMapper.GUIC_ADD_CLASS, "建立班別"},
        {TextMapper.GUIC_DELETE_CLASS, "刪除班別"},
        {TextMapper.GUIC_RENAME_CLASS, "修改班別名稱"},
        {TextMapper.GUIC_MSG_RENAME_CLASS, "新的班別名稱"},
        {TextMapper.GUIC_MSG_DELETE_CLASS, "你是否確認刪除班別"},
        {TextMapper.GUIC_CLASS_NOT_EMPTY, "此班別內包含用戶，你是否確認刪除此班別"},
        {TextMapper.GUIC_CLASS_NOT_EMPTY_TITLE, "此班別內包含用戶"},
        {TextMapper.GUIC_MSG_DELETE_STUDENT, "你是否確認在此班別內刪除 {0}"},
        {TextMapper.GUIC_DELETE_STUDENT, "在此班別內刪除學生"},
        {TextMapper.GUIC_NO_STUDENTS, "在班別 {0} 內沒有學生"},
        {TextMapper.GUIRS_RESULTS, "成績"},
        {TextMapper.GUIRS_NO_RESULTS, "沒有成績記錄"},
        {TextMapper.GUIRS_BTN_SELECT_COURSES, "選擇模組"},
        {TextMapper.GUIRS_BTN_COPY_TO_CLIPBOARD, "複製到剪貼板"},
        {TextMapper.GUIRS_TLTP_SELECT_COURSES, "選擇模組"},
        {TextMapper.GUIRS_TLTP_ZOOM, "{0} 的成績"},
        {TextMapper.GUIRS_TLTP_ZOOM_ORDER, "{0} 排序"},
        {TextMapper.GUIRS_TLTP_RESULT_SCORE_BUTTON, "顯示 {1}  的 {0} 的活動成績"},
        {TextMapper.GUIRSDLG_MSG, "是否刪除{1}  的 {0} 的所有成績？"},
        {TextMapper.UG_RESULTS_OF_STUDENT, "{1}  的 {0} 的成績"},
        {TextMapper.GUISC_TITLE, "選擇模組"},
        {TextMapper.GUISC_BTN_SELECT_ALL, "全選"},
        {TextMapper.GUISC_BTN_DESELECT_ALL, "取消所有選擇"},
        {TextMapper.UG_CLASSES, "班別"},
        {TextMapper.UG_STUDENTS_OF_CLASS, "{0} 中的學生"},
        {TextMapper.UG_USER_TITLE, "學生"},
        {TextMapper.UG_CLASS_TITLE, "班別"},
        {TextMapper.UG_CLASS_CHILD, "學生 {0}"},
        {TextMapper.UG_CLASS_ORDER_ASC, "班別名稱 (A-Z)"},
        {TextMapper.UG_CLASS_ORDER_DESC, "班別名稱 (Z-A)"},
        {TextMapper.UG_USER_PARENT, "班別"},
        {TextMapper.UG_USER_ORDER_ASC, "姓(A-Z)"},
        {TextMapper.UG_USER_ORDER_DESC, "姓 (Z-A)"},
        {TextMapper.LG_COURSES, "模組"},
        {TextMapper.LG_SCOS_OF_COURSE, "{0} 的活動"},
        {TextMapper.LG_COURSE_CHILD, "{0} 的活動"},
        {TextMapper.LG_COURSE_ORDER_ASC, "成績 (0-100)"},
        {TextMapper.LG_COURSE_ORDER_DESC, "成績 (100-0)"},
        {TextMapper.LG_SCO_PARENT, "模組"},
        {TextMapper.LG_SCO_ORDER_ASC, "成績 (0-100)"},
        {TextMapper.LG_SCO_ORDER_DESC, "成績 (100-0)"},
        {TextMapper.LG_SCO_NAME, "活動 {0}"},
        {TextMapper.GUIC_ADD_COURSE, "加入新模組"},
        {TextMapper.GUIC_ADD_MAP, "加入新資料夾"},
        {TextMapper.GUIC_COURSE_MANAGEMENT, "模組管理"},
        {TextMapper.GUIC_TLTP_DELETE_COURSE, "刪除模組 {0}"},
        {TextMapper.GUIC_TLTP_DELETE_MAP, "刪除資料夾 {0}"},
        {TextMapper.GUIC_TLTP_EDIT_COURSE, "修改模組"},
        {TextMapper.GUIC_TLTP_SCO_COURSE, "活動管理"},
        {TextMapper.GUICDLG_COURSE_NAME, "模組名稱"},
        {TextMapper.GUICDLG_MAP_NAME, "資料夾名稱"},
        {TextMapper.GUICDLG_COURSE_DESCRIPTION, "說明"},
        {TextMapper.GUICDLG_TTL_ADD_COURSE, "加入新模組"},
        {TextMapper.GUICDLG_TTL_EDIT_COURSE, "修改模組"},
        {TextMapper.GUIC_TLTP_EDIT_MAP, "修改資料夾"},
        {TextMapper.GUIC_NO_COURSES, "沒有可顯示模組"},
        {TextMapper.GUIC_COURSE_SHARE, "分享模組"},
        {TextMapper.GUIC_MSG_COURSE_DELETE, "現在活動進行。\n當刪除此模組時\nen活動內的成績亦會被刪除\n \n你是否確認刪除此模組？"},
        {TextMapper.GUIC_MSG_COURSE_DELETE_NO_SCO, "你是否確認刪除此模組？"},
        {TextMapper.GUIC_MSG_TTL_COURSE_DELETE, "刪除模組"},
        {TextMapper.GUIS_ADD_SCO, "加入新活動"},
        {TextMapper.GUIS_LBL_SCO_OF_COURSE, "模組 {0} 的活動"},
        {TextMapper.GUIS_SCO_MANAGEMENT, "活動管理"},
        {TextMapper.GUIS_SHOW_SCORE, "學生可查閱成績"},
        {TextMapper.GUIS_TLTP_DELETE_SCO, "刪除活動 {0}"},
        {TextMapper.GUIS_TLTP_EDIT_SCO, "修改活動名稱"},
        {TextMapper.GUIS_TLTP_PARAMETERS_SCO, "修改活動"},
        {TextMapper.GUIS_TLTP_COURSE_SCO, "返回模組"},
        {TextMapper.GUISDLG_SCO_NAME, "活動名稱"},
        {TextMapper.GUISDLG_SCO_DESCRIPTION, "活動說明"},
        {TextMapper.GUISDLG_TTL_ADD_SCO, "加入新活動"},
        {TextMapper.GUISDLG_TTL_EDIT_SCO, "修改活動"},
        {TextMapper.GUIS_MSG_SCO_DELETE, "當刪除此活動時\nen成績亦會被刪除\n \n你是否確認刪除此活動？"},
        {TextMapper.GUIS_MSG_TTL_SCO_DELETE, "刪除活動"},
        {TextMapper.GUIS_NO_SCOS, "在模組 {0} 中沒有活動"},
        {TextMapper.GUIS_LOAD_LOGO, "加載圖像 {0}"},
        {TextMapper.GUISDLG_BTN_ADD_SCO, "加入"},
        {TextMapper.GUISDLG_BTN_PREVIEW_SCO, "預覽活動"},
        {TextMapper.GUISDLG_MSG_SELECT_SCO, "選擇活動"},
        {TextMapper.GUISDLG_MSG_NO_APPLETS, "沒有可加入的活動"},
        {TextMapper.GUISDLG_SHOW, "顯示"},
        {TextMapper.GUISDLG_ALL, "全部"},
        {TextMapper.GUISDLG_MSG_NO_SELECTION, "你沒有選擇活動"},
        {TextMapper.GUISDLG_RB_STANDARD_SCOS, "標準活動"},
        {TextMapper.GUISDLG_RB_OWN_SCOS, "已有活動"},
        {TextMapper.GUIPA_BTN_PREVIEW, "預覽活動"},
        {TextMapper.GUIPA_BTN_SAVE, "儲存"},
        {TextMapper.GUIPA_BTN_RESET, "重設"},
        {TextMapper.GUIPA_BTN_CANCEL, "關閉"},
        {TextMapper.GUIPA_SCO_EDIT, "修改活動"},
        {TextMapper.GUIPA_NO_PARAMS, "活動不可更改"},
        {TextMapper.GUIPA_DLG_TTL, "活動 {0} 修改模式"},
        {TextMapper.GUIPA_MSG_PARAM_SAVE, "若你儲存新的設定，\n舊有的成績將會被刪除\n \n你是否確認儲存此設定？"},
        {TextMapper.GUIPA_MSG_TTL_PARAM_SAVE, "儲存設定"},
        {TextMapper.GUIPA_PARAMS_OF_SCO, "參數 ({0})"},
        {"cut", "剪下"},
        {"copy", "複製"},
        {"paste", "貼上"},
        {"delete", "刪除"},
        {"edit", "修改"},
        {"file", "檔案"},
        {"rename", "重新命名"},
        {TextMapper.GUIA_INSERT_SCOS, "從備份中插入活動"},
        {TextMapper.GUIH_STOP_EDIT, "停止修改"},
        {TextMapper.GUIH_EDIT, "修改"},
        {"Alle modules", "全部模組"},
        {"Standaard DWO modules", "標準DME模組"},
        {"Nieuwe Modulemap", "新模組資料夾"},
        // classadminpanel
        {"Klassen toewijzen", "分配班別"},
        {"Klas", "班別"},
        {"Docent", "老師"},
        {"Verwijder", "移除"},
        // classpanel 
        {"boomstructuur?", "樹視圖?"},
        // select courses dialog
        {"Leerlinggegevens verwijderen", "移除學生成績"},
        {"Wilt u alle resultaten van {0} voor {1} verwijderen?", "你是否確認移除學所有在 {1} 中 {0} 的成績？"},
        {"soort", "種類"},
        {"vanaf", "從"},
        {"tot aan", "至"},
        {"tot", "至"},
        {"Ll ggvns", "成績"},
        {"normaal", "正常"},
        {"afgeschermd", "確保"},
        {"Geef tijdstip {0}", "設定日期及時間 \"{0}\""},
        {" dag: ", " 日期： "},
        {"tijd:", "時間："},
        // resultLoogger 
        {"Overzicht Logs", "記錄總覽"},
        {"deel-scores", "部份分數"},
        {"tijdsduur", "時間"},
        // default partial score
        {"resultaat", "成績"},
        //importexportdialog
        {"Kopiëer modules", "複製模組"},
        {"Toestaan", "允許"},
        {"Modules beschikbaar stellen", "提供模組"},
        {"Modules opvragen", "檢索模組"},
        {"Delen met", "分享"},
        {"Alle scholen", "所有學校"},
        {"Scholen", "學校"},
        {"toepassen", "申請"},
        {TextMapper.GUIEID_MSG1, "<html>(1) 選擇學校<br>"
            + "(2) 預覽可顯示的模組<br>"
            + "(3) 選擇一個或多個模組到你的學校<br><br>"
            + "選擇的模組已被複製至你的模組<br>"
            + "及可於你的學校使用。"},
        {TextMapper.GUIEID_MSG2, "<html>我想以分享方式參與並將學校列在名單上"},
        {TextMapper.GUIEID_MSG3, "<html>(1) 選擇模組<br>(2) 選擇學校<br><br>選擇的模組可被使用<br>至已選擇的學校。"},
        {"leerlingen ook", "學生亦可"},
        {TextMapper.GUIUMP_REMOVE_CLASS, "由 {0} 刪除全部學生？"},
        {TextMapper.GUIUMP_ALL_STUDENTS, "全部學生"},
        {TextMapper.GUIC_SETTINGS, "{0} 組態"},
        {TextMapper.GUIH_SETTINGS, "學校組態"},
        {TextMapper.GUIC_SETTINGS_STUDENT, "學生選擇其班別"},
        {TextMapper.GUIC_SETTINGS_TEACHER, "老師選擇學生班別"},
        {TextMapper.GUIC_SETTINGS_MODULE, "老師可改變模組"},
        // google translate...
        {TextMapper.GUICDLG_LICENCE, "預訂 ''{0}'' 已過期！\n不可加入新的用戶。\n請與DME學校聯絡人接洽。"},
        {TextMapper.DWOAPPLET_EXISTS, "DME已準備！"},};

    public Text_cn() {

    }

    /**
     * @return Object[][]
     */
    public Object[][] getContents() {
        return contents;
    }
}
