<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>nl.uu.fi.dwo.lms</groupId>
    <artifactId>chatgwt</artifactId>
    <version>2.5.49-SNAPSHOT</version>
    <relativePath>..</relativePath>
  </parent>

  <artifactId>chatgwt-client</artifactId>
  <packaging>gwt-app</packaging>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>chatgwt-shared</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>chatgwt-shared</artifactId>
      <version>${project.version}</version>
      <classifier>sources</classifier>
    </dependency>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-user</artifactId>
      <version>${gwtVersion}</version>
    </dependency>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-dev</artifactId>
      <version>${gwtVersion}</version>
    </dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<scope>provided</scope>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.ideas</groupId>
			<artifactId>ideasgwt</artifactId>
			<version>0.1.9</version>
		</dependency>
	<dependency>
	  <groupId>fi.wiskopdrgwt</groupId>
  	  <artifactId>wiskopdrgwt</artifactId>
	  <version>2.5.49-SNAPSHOT</version>
	</dependency>
	<dependency>
		<groupId>nl.uu.fi.dwo.keyboard</groupId>
		<artifactId>keyboardgwt</artifactId>
		<version>2.5.49-SNAPSHOT</version>	
	</dependency>
        <dependency>
            <groupId>org.fusesource.restygwt</groupId>
            <artifactId>restygwt</artifactId>
            <version>${restyVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.fusesource.restygwt</groupId>
            <artifactId>restygwt</artifactId>
            <version>${restyVersion}</version>
            <classifier>sources</classifier>
        </dependency>
        <dependency>
        	<groupId>junit</groupId>
        	<artifactId>junit</artifactId>
        	<version>4.13.1</version>
        	<scope>test</scope>
        </dependency>
        <dependency>
            <groupId>nl.uu.fi.dwo.mobile</groupId>
            <artifactId>promise-api</artifactId>
            <version>2.5.49-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>nl.uu.fi.dwo.mobile</groupId>
            <artifactId>promise-api</artifactId>
            <version>2.5.49-SNAPSHOT</version>
            <classifier>sources</classifier>
        </dependency>
        <dependency>
        	<groupId>nl.uu.fi.dwo</groupId>
        	<artifactId>dwo-gwt-lib</artifactId>
        </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>net.ltgt.gwt.maven</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <configuration>
          <moduleName>nl.uu.fi.dwo.lms.chatgwt.ChatGWT</moduleName>
          <moduleShortName>chatgwt</moduleShortName>
          <style>PRETTY</style>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
