logout=Je ben afgemeld. Je kan dit venster sluiten.
quit=Stop
title=Logout
html=<!DOCTYPE html><html><head><meta charset="ISO-8859-1"><title>{2}</title></head><body><p>{0}</p><p><a href="logout.html">{1}</a></p></body></html>