<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>nl.numworx.uploadwidget</groupId>
    <artifactId>uploadwidget-parent</artifactId>
    <version>2.5.49-SNAPSHOT</version>
  </parent>
  <artifactId>uploadwidget-s3</artifactId>
  <dependencies>
	<dependency> <!-- Force correct version httpclient -->
	    <groupId>org.apache.httpcomponents</groupId>
	    <version>4.5.14</version>
 	    <artifactId>httpclient</artifactId>
	</dependency>
	 <dependency>
	    <groupId>software.amazon.awssdk</groupId>
	    <artifactId>s3</artifactId>
	    <version>2.31.40</version>
	    <scope>compile</scope>
	</dependency>
	<dependency>
	    <groupId>software.amazon.awssdk</groupId>
	    <artifactId>sdk-core</artifactId>
	    <version>2.31.40</version>
	    <scope>compile</scope>
	</dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.1</version>
      <scope>test</scope>
    </dependency>
	<dependency>
		<groupId>nl.numworx.uploadwidget</groupId>
		<artifactId>uploadwidget-common</artifactId>
	</dependency>
      <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.1.0</version>
            <scope>provided</scope>
      </dependency>
  </dependencies>
</project>
