<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>nl.numworx.uploadwidget</groupId>
    <artifactId>uploadwidget-parent</artifactId>
    <version>2.5.49-SNAPSHOT</version>
    <relativePath>../</relativePath>
  </parent>
  <artifactId>uploadwidget-common</artifactId>
  <name>UploadWidget common</name>
  <description>common code</description>
  <dependencies>
  	<dependency>
  		<groupId>nl.uu.fi.dwo</groupId>
  		<artifactId>dwo-commons-lib</artifactId>
  	</dependency>
  	<dependency>
	  <groupId>commons-fileupload</groupId>
	  <artifactId>commons-fileupload</artifactId>
<!-- LET OP: FIXED versie 1.3.3 niet upgraden!
	XXX gwtupload heeft een serializable diskfileitem nodig!
-->
	  <version>1.3.3</version>
  	</dependency>
      <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.1.0</version>
            <scope>provided</scope>
      </dependency>
  </dependencies>
  
  <build>
  	<plugins>
            <plugin> <!-- attach-sources voor GWT -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.4</version>
               <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
  	</plugins>
  </build>
</project>
