<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>nl.uu.fi.dwo</groupId>
		<artifactId>dwo</artifactId>
		<version>2.5.49-SNAPSHOT</version>
		<relativePath>../DWO/pom.xml</relativePath>
	</parent>
	<artifactId>ebserver</artifactId>
	<packaging>war</packaging>
	<name>${project.build.finalName}</name>
	<repositories>	
		<repository>
		  <id>com.teamdev</id>
		  <url>https://europe-maven.pkg.dev/jxbrowser/releases</url>
		</repository>
		<repository>
			<id>numworx-vendor-oauth</id>
			<url>https://maven.pkg.github.com/UtrechtUniversity/numworx-vendor-oauth</url>
		</repository>
	    <repository>
	      <id>github-uoc-lti-core</id>
	      <name>GitHub UOC Apache Maven Packages</name>
	      <url>https://maven.pkg.github.com/uoc/java-lti-1.3-core</url>
	    </repository>				
	    <repository>
	      <id>github-uoc-lti-jwt</id>
	      <name>GitHub UOC Apache Maven Packages</name>
	      <url>https://maven.pkg.github.com/uoc/java-lti-1.3-jwt</url>
	    </repository>				
	    <repository>
	      <id>github-uoc-lti</id>
	      <name>GitHub UOC Apache Maven Packages</name>
	      <url>https://maven.pkg.github.com/uoc/java-lti-1.3</url>
	    </repository>
 	    <repository>
	      <id>numworx-dwo-project</id>
	      <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-project</url>
	      <snapshots>
			  <enabled>true</enabled>
		  </snapshots>
	    </repository>		
 	    <repository>
	      <id>numworx-dwo-openmath</id>
	      <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-openmath</url>
	      <snapshots>
			  <enabled>true</enabled>
		  </snapshots>
	    </repository>		
	</repositories>
	<pluginRepositories>
		<pluginRepository>
	      <id>numworx-dwo-project</id>
	      <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-project</url>
	      <snapshots>
			  <enabled>true</enabled>
		  </snapshots>			
		</pluginRepository>
	</pluginRepositories>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>bom</artifactId>
        <version>${aws.java.sdk.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
	<dependencies>
<!-- jackson 2.13.4.2 voor Azure -->
				<dependency>
				    <groupId>com.fasterxml.jackson.core</groupId>
				    <artifactId>jackson-databind</artifactId>
				    <version>2.13.4.2</version>
				</dependency>
				<dependency>
				    <groupId>com.fasterxml.jackson.datatype</groupId>
				    <artifactId>jackson-datatype-jsr310</artifactId>
				    <version>2.13.4</version>
				</dependency>
				<dependency>
				    <groupId>com.fasterxml.jackson.core</groupId>
				    <artifactId>jackson-annotations</artifactId>
				    <version>2.13.4</version>
				</dependency>
				<dependency>
				    <groupId>com.fasterxml.jackson.core</groupId>
				    <artifactId>jackson-core</artifactId>
				    <version>2.13.4</version>
				</dependency>
					 <dependency>
					  <groupId>commons-fileupload</groupId>
					  <artifactId>commons-fileupload</artifactId>
					  <version>1.3.3</version>
					</dependency>
				<dependency>			
				    <groupId>nl.uu.fi.dwo.lms</groupId>
    				<artifactId>dwogwtclient</artifactId>
					<version>2.5.49-SNAPSHOT</version>
					<classifier>classes</classifier>
					<exclusions>
						<exclusion>
							<groupId>org.vectomatic</groupId>
							<artifactId>lib-gwt-svg</artifactId>
						</exclusion>
						<exclusion>
							<groupId>nl.uu.fi.dwo</groupId>
							<artifactId>dwo-gwt-lib</artifactId>
						</exclusion>
						<exclusion>
							<groupId>com.google.dagger</groupId>
							<artifactId>dagger-gwt</artifactId>
						</exclusion>
						<exclusion>
							<groupId>org.vectomatic</groupId>
							<artifactId>lib-gwt-file</artifactId>
						</exclusion>
						<exclusion>
							<groupId>nl.uu.fi.dwo.ideas</groupId>
							<artifactId>IdeasGWT</artifactId>
						</exclusion>
						<exclusion>
							<groupId>nl.uu.fi.dwo.lms</groupId>
							<artifactId>chatgwt-shared</artifactId>
						</exclusion>
						<exclusion>
							<groupId>nl.uu.fi.dwo.mobile</groupId>
							<artifactId>promise-api</artifactId>
						</exclusion>
						<exclusion>
				        	<groupId>nl.uu.fi.dwo.lms</groupId>
				        	<artifactId>dwogwtclienthtmlui</artifactId>							
						</exclusion>
						<exclusion>
						    <groupId>nl.uu.fi.dwo.rest</groupId>
    						<artifactId>dwo-rest-lib</artifactId>
						</exclusion>
					</exclusions>
				</dependency>

		<dependency>
			<groupId>commons-dbcp</groupId>
			<artifactId>commons-dbcp</artifactId>
			<version>1.4</version>
		</dependency>

		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>dwoserver</artifactId>
			<classifier>classes</classifier>
			<exclusions>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-annotations</artifactId>
				</exclusion>
				<exclusion>
					<groupId>software.amazon.jdbc</groupId>
					<artifactId>aws-advanced-jdbc-wrapper</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jsr107.ri</groupId>
					<artifactId>cache-ri-impl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>8.4.0</version>
            <!--comment scope for elastic beanstalk-->
            <scope>runtime</scope>
            <exclusions>
            	<exclusion>
            		<groupId>com.google.protobuf</groupId>
            		<artifactId>protobuf-java</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>fi.servlet</groupId>
			<artifactId>dwomaccess</artifactId>
			<version>2.5.48</version>
			<classifier>classes</classifier>
			<exclusions>
				<exclusion>
					<groupId>aelfred</groupId>
					<artifactId>aelfred</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>fi.servlet</groupId>
			<artifactId>ideas-servlet</artifactId>
			<version>0.0.17</version>
		</dependency>
		<dependency>
			<groupId>nl.tue.win.riaca.openmath</groupId>
			<artifactId>om-lib</artifactId>
			<version>1.3.18b</version>
		</dependency>
		<dependency>
			<groupId>nl.tue.win.riaca.mathematica</groupId>
			<artifactId>mathematica-phrasebook</artifactId>
			<version>1.3.7</version>
		</dependency>
		<dependency>
			<groupId>fi.servlet</groupId>
			<artifactId>openmath</artifactId>
			<version>0.0.4</version>
		</dependency>
		<dependency>
			<groupId>fi.mpreduce</groupId>
			<artifactId>mpreduce-phrasebook</artifactId>
			<version>0.0.4</version>
		</dependency>
		<dependency>
			<groupId>nl.tue.win.riaca.mathml</groupId>
			<artifactId>mathml-phrasebook</artifactId>
			<version>1.3.2</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx.geogebra</groupId>
			<artifactId>geogebra_cas</artifactId>
			<version>2.5.46</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx.geogebra</groupId>
			<artifactId>geogebra_main</artifactId>
			<version>2.5.46</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx.geogebra</groupId>
			<artifactId>geogebra</artifactId>
			<version>2.5.46</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.18.0</version>
		</dependency>
		<dependency>
			<groupId>net.oauth.core</groupId>
			<artifactId>oauth-provider</artifactId>
			<version>20100601</version>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>dwojclient</artifactId>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>dwo-apps</artifactId>
			<version>2.5.48</version>
			<scope>runtime</scope>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>dwo-apps</artifactId>
			<version>2.5.48</version>
			<classifier>classes</classifier>
		</dependency>
		<dependency>
		     <groupId>nl.uu.fi.dwo.lms</groupId>
             <artifactId>chatgwt-server</artifactId>
             <version>2.5.48</version>
             <type>war</type>
			 <scope>runtime</scope>
		</dependency>
	<dependency>
		<groupId>nl.uu.fi.dwo.mobile</groupId>
		<artifactId>dwoplayer</artifactId>
		<type>war</type>
		<scope>runtime</scope>
	</dependency>
	<dependency>
		<groupId>nl.uu.fi.dwo.lms</groupId>
		<artifactId>dwogwtclient</artifactId>
		<version>2.5.49-SNAPSHOT</version>
		<type>war</type>
		<scope>runtime</scope>
	</dependency>
	<dependency>
		<groupId>nl.uu.fi.dwo.register</groupId>
		<artifactId>register</artifactId>
		<version>2.5.49-SNAPSHOT</version>
		<type>war</type>
		<scope>runtime</scope>
		<exclusions>
			<exclusion>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-annotations</artifactId>
			</exclusion>
			<exclusion>
				<groupId>javax.mail</groupId>
				<artifactId>mail</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
	<dependency>
		<groupId>nl.uu.fi.dwo.register</groupId>
		<artifactId>register</artifactId>
		<version>2.5.49-SNAPSHOT</version>
		<classifier>classes</classifier>
		<exclusions>
			<exclusion>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-annotations</artifactId>
			</exclusion>
			<exclusion>
				<groupId>javax.mail</groupId>
				<artifactId>mail</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
	<dependency>
		<groupId>fi.servlet</groupId>
		<artifactId>dwomaccess</artifactId>
		<version>2.5.48</version>
		<type>war</type>
		<scope>runtime</scope>
	</dependency>
	<dependency>
		<groupId>org.mitre.dsmiley.httpproxy</groupId>
		<artifactId>smiley-http-proxy-servlet</artifactId>
		<version>1.12</version>
		<scope>runtime</scope>
	</dependency>
	<dependency>
		<groupId>nl.numworx.oauth2</groupId>
		<artifactId>oauth2client</artifactId>
		<version>2.5.48</version>
		<classifier>classes</classifier>
		<exclusions>
			<exclusion>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-api</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
	<dependency>
		<groupId>nl.numworx.oauth2</groupId>
		<artifactId>oauth2client</artifactId>
		<version>2.5.48</version>
		<type>war</type>
		<scope>runtime</scope>
	</dependency>
		<dependency>
		    <groupId>com.google.zxing</groupId>
		    <artifactId>core</artifactId>
		    <version>3.4.1</version>
		</dependency>
		<dependency>
		    <groupId>com.google.zxing</groupId>
		    <artifactId>javase</artifactId>
		    <version>3.4.1</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx.swingbrowser</groupId>
			<artifactId>swingbrowser-api</artifactId>
		    <scope>test</scope>
		</dependency>
		<dependency>
			<groupId>nl.numworx.swingbrowser</groupId>
			<artifactId>swingbrowser-jxb</artifactId>
		    <scope>test</scope>
		</dependency>
		<dependency>
			<groupId>nl.numworx.notebook</groupId>
			<artifactId>notebook-service</artifactId>
			<version>2.5.48</version>
			<classifier>classes</classifier>
		</dependency>
		<dependency>
			<groupId>nl.numworx.xapi</groupId>
			<artifactId>xapiserver</artifactId>
  			<version>2.5.48</version>
			<scope>runtime</scope>
			<type>war</type>
		</dependency>
<!-- AWS SDK same version -->
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>s3</artifactId>
    <version>2.31.40</version>
    <scope>compile</scope>
</dependency>
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>rds</artifactId>
    <version>2.31.40</version>
</dependency>

	</dependencies>
	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<version>1.4</version>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<!-- doCheck and doUpdate actually talk to repository if it's true, 
						Check would check that there are no local changes. Update would update it -->
					<doCheck>false</doCheck>
					<doUpdate>false</doUpdate>
					<timestampFormat>{0,date,yyyyMMddHHmmss}</timestampFormat>
				</configuration>
			</plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>templating-maven-plugin</artifactId>
                <version>1.0.0</version>
                <executions>
                    <execution>
                        <id>filter-src</id>
                        <goals>
                            <goal>filter-sources</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<executions>
					<execution>
						<id>copy</id>
						<phase>process-resources</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>${project.groupId}</groupId>
									<artifactId>dwojclient</artifactId>
									<classifier>jar-with-dependencies</classifier>
									<overWrite>true</overWrite>
									<destFileName>dwo/DWOJApplet.jar</destFileName>
								</artifactItem>
								<artifactItem>
									<groupId>${project.groupId}</groupId>
									<artifactId>dwojclient</artifactId>
									<classifier>jar-with-dependencies</classifier>
									<type>jar.pack.gz</type>
									<overWrite>true</overWrite>
									<destFileName>dwo/DWOJApplet.jar.pack.gz</destFileName>
								</artifactItem>
								<artifactItem>
									<groupId>nl.numworx.swingbrowser</groupId>
									<artifactId>swingbrowser-api</artifactId>
									<destFileName>dwo/swingbrowser-api.jar</destFileName>
								</artifactItem>
								<artifactItem>
									<groupId>nl.numworx.swingbrowser</groupId>
									<artifactId>swingbrowser-jxb</artifactId>
									<destFileName>dwo/swingbrowser-jxb.jar</destFileName>
								</artifactItem>
							</artifactItems>
							<outputDirectory>${project.build.directory}/${project.build.finalName}/</outputDirectory>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>true</overWriteSnapshots>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- cargo plugin to run tomcat 8 for testing - configuration under construction -->
			<plugin>
				<groupId>org.codehaus.cargo</groupId>
				<artifactId>cargo-maven2-plugin</artifactId>
				<version>1.8.5</version>
				<configuration>
					<container>
						<containerId>tomcat9x</containerId>
						<artifactInstaller>
							<groupId>org.apache.tomcat</groupId>
							<artifactId>tomcat</artifactId>
							<version>9.0.107</version>
						</artifactInstaller>
						<systemProperties>
							<DWO_ENV>test</DWO_ENV>
						</systemProperties>
						<dependencies>
					        <dependency>
					            <groupId>com.mysql</groupId>
					            <artifactId>mysql-connector-j</artifactId>
					        </dependency>
						</dependencies>
					</container>
					<deployables>
						<deployable>
							<groupId>${project.groupId}</groupId>
							<artifactId>${project.artifactId}</artifactId>
							<type>war</type>
							<properties>
								<context>/</context>
							</properties>
						</deployable>
					</deployables>
					
					<configuration>
						<properties>
						        <cargo.servlet.port>${http.port}</cargo.servlet.port>
						</properties>
						<datasources>
							<datasource>
								<jndiName>jdbc/dwodb</jndiName>
								<driverClass>com.mysql.cj.jdbc.Driver</driverClass>
								<url>jdbc:mysql://localhost:3306/dwo_productie_v1_2</url>
								<username>${cargo.username}</username>
								<password>${cargo.password}</password>
							</datasource>
						</datasources>
					</configuration>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.tomcat.maven</groupId>
				<artifactId>tomcat7-maven-plugin</artifactId>
				<version>2.2</version>
				<configuration>
                        <systemProperties>
                        	<CDN_HOST>localhost:8082</CDN_HOST>
                        	<CDNURL>http://localhost:8082</CDNURL>
                            <DWO_ENV>testentree</DWO_ENV>
                            <SEB_TOETS_MAC>3dce4166740c27af1284d6f268bf601e58ea0668ae967947776c1246611a56f2,9153c48c6111d2733add6e1d596db4059c302cf736dcb18ca498288e21404507,c5d129e27f57b1970d2ffda2ed745a20f7d8e12ed9bfbfb168e83f75f9f870cf</SEB_TOETS_MAC>
  							<ALLOW_ORIGIN>http://localhost:${http.port}</ALLOW_ORIGIN>
 							<UU_INDEX />
 							<ENV_NOSEB>true</ENV_NOSEB>
 							<ENV_IPRANGE>127.0.0.1,::1</ENV_IPRANGE>
<!--                    		<XAPI_ENDPOINT>http://localhost:8089/xapi/</XAPI_ENDPOINT>-->
                    		<XAPI_AUTH>bXlfa2V5Om15X3NlY3JldA==</XAPI_AUTH>
                    		<DWO_REDIRECT>false</DWO_REDIRECT>               
                    		<AZ_ENDPOINT>http://azurite:10000/devstoreaccount1/</AZ_ENDPOINT>
                    		<AZ_SHAREDKEY>Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==</AZ_SHAREDKEY>
                    	<!-- alleen bij az	<S3_BUCKET>devstoreaccount1</S3_BUCKET> -->
							<SCW_ENDPOINT>http://localhost:9444/</SCW_ENDPOINT> <!-- s3-ninja -->
							<AWS_ACCESS_KEY_ID>AKIAIOSFODNN7EXAMPLE</AWS_ACCESS_KEY_ID>
							<AWS_SECRET_ACCESS_KEY>wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY</AWS_SECRET_ACCESS_KEY>
                        </systemProperties>
					<server>TomcatServer</server>
					<path>/</path>
					<warSourceDirectory>${project.build.directory}/${project.build.finalName}</warSourceDirectory>
					<contextFile>src/test/tomcat/${context.xml}</contextFile>
					<port>${http.port}</port>
					<webapps>
						<webapp>
							<groupId>nl.numworx.schoolyear</groupId>
  							<artifactId>sy</artifactId>
							<version>2.5.47</version>
							<type>war</type>
							<contextPath>/sy</contextPath>
                            <asWebapp>true</asWebapp>
						</webapp>
					</webapps>
				</configuration>
	<dependencies>
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-core</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-util</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-coyote</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-api</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-jdbc</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-dbcp</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-servlet-api</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-jsp-api</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-jasper</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-jasper-el</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-el-api</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-catalina</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-tribes</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-catalina-ha</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-annotations-api</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-juli</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-logging-juli</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-logging-log4j</artifactId>
			<version>${tomcat7.version}</version>
		</dependency>
		<dependency>
		    <groupId>de.javakaffee.msm</groupId>
		    <artifactId>memcached-session-manager-tc7</artifactId>
		    <version>2.3.2</version>
		</dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>8.4.0</version>
        </dependency>
	</dependencies>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
          			<filteringDeploymentDescriptors>true</filteringDeploymentDescriptors>
					<webXml>src/main/webxml/web.xml</webXml>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
						</manifest>
						<manifestEntries>
							<Implementation-Build>${buildNumber}</Implementation-Build>
							<Implementation-Timestamp>${timestamp}</Implementation-Timestamp>
							<Implementation-ScmBranch>${scmBranch}</Implementation-ScmBranch>
						</manifestEntries>
					</archive>
					<overlays>
						<overlay>
							<groupId>fi.dwo</groupId>
							<artifactId>dwo-apps</artifactId>
							<targetPath>/dwo/apps</targetPath>
							<excludes>
								<exclude>WEB-INF/**</exclude>
								<exclude>META-INF/**</exclude>
							</excludes>
						</overlay>
						<overlay>
							<groupId>nl.uu.fi.dwo.mobile</groupId>
							<artifactId>dwoplayer</artifactId>
							<targetPath>/dwo/tablet</targetPath>		
							<excludes>
								<exclude>WEB-INF/**</exclude>
								<exclude>META-INF/**</exclude>
							</excludes>
						</overlay>
						<overlay>
							<groupId>nl.uu.fi.dwo.lms</groupId>
							<artifactId>dwogwtclient</artifactId>
							<excludes>
								<exclude>WEB-INF/**</exclude>
								<exclude>META-INF/**</exclude>
								<exclude>**/*.scss</exclude>
								<exclude>css/*.rb</exclude>
								<exclude>css/*.map</exclude>
								<exclude>login.html</exclude>
								<exclude>gwtclient.html</exclude>
								<exclude>html5plain.html</exclude>
<!--								<exclude>library.html</exclude>-->
								<exclude>**/*.md</exclude>
								<exclude>ng-js/**</exclude>
								<exclude>js-plainui/**</exclude>
								<exclude>chatbox/**</exclude>
							</excludes>
							<targetPath>/gwtclient</targetPath>
						</overlay>
						<overlay>
							<groupId>nl.uu.fi.dwo.register</groupId>
							<artifactId>register</artifactId>
							<targetPath>/dwo/register</targetPath>
							<excludes>
								<exclude>WEB-INF/**</exclude>
								<exclude>META-INF/**</exclude>
							</excludes>
						</overlay>
						<overlay>
							<groupId>fi.servlet</groupId>
							<artifactId>dwomaccess</artifactId>
							<targetPath>/DWOmAccess</targetPath>
							<excludes>
								<exclude>WEB-INF/**</exclude>
								<exclude>META-INF/**</exclude>
							</excludes>
						</overlay>
						<overlay>
							<groupId>nl.numworx.oauth2</groupId>
							<artifactId>oauth2client</artifactId>
							<targetPath>/dwo/oauth2client</targetPath>
							<excludes>
								<exclude>WEB-INF/**</exclude>
								<exclude>META-INF/**</exclude>
							</excludes>						
						</overlay>
						<overlay>
						     <groupId>nl.uu.fi.dwo.lms</groupId>
             				 <artifactId>chatgwt-server</artifactId>
							<targetPath>/gwtclient/chatbox</targetPath>
							<excludes>
								<exclude>WEB-INF/**</exclude>
								<exclude>META-INF/**</exclude>
							</excludes>						
						</overlay>
					</overlays>
				</configuration>
			</plugin>
			<plugin> <!-- NIET ZOMAAR WEGGOOIEN! -->
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.5.0</version>
				<executions>
					<execution>
						<id>local-index</id>
						<goals>
							<goal>java</goal>
						</goals>
						<phase>process-resources</phase>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>fi.microserver</groupId>
						<artifactId>microindex</artifactId>
						<version>2.5.48</version>
					</dependency>
				</dependencies>
				<configuration>
					<mainClass>fi.microserver.microindex.Main</mainClass>
					<includeProjectDependencies>false</includeProjectDependencies>
					<includePluginDependencies>true</includePluginDependencies>
					<addOutputToClasspath>false</addOutputToClasspath>
					<addResourcesToClasspath>false</addResourcesToClasspath>
					<arguments>
						<argument>${project.build.directory}/${project.build.finalName}/dwo</argument>
					</arguments>
					<blockSystemExit>true</blockSystemExit>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.github.davidmoten</groupId>
				<artifactId>aws-maven-plugin</artifactId>
				<version>0.2.18</version>
				<configuration>
					<serverId>${aws.serverId}</serverId>
					<artifact>${project.build.directory}/${project.build.finalName}.war</artifact>
					<applicationName>${aws.applicationName}</applicationName>
					<environmentName>${aws.environmentName}</environmentName>
					<region>eu-west-1</region>
				</configuration>
				<dependencies>
					<dependency>
			    		<groupId>javax.xml.bind</groupId>
			    		<artifactId>jaxb-api</artifactId>
			    		<version>2.3.0</version>
					</dependency>				
				</dependencies>
			</plugin>
		</plugins>
	</build>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<DWOmAccessVersion>2.5.20</DWOmAccessVersion>
		<aws.serverId>prod</aws.serverId>
		<aws.applicationName>DWO-EBServer</aws.applicationName>
		<aws.environmentName>testip6server</aws.environmentName>
        <context.xml>context.xml</context.xml>
        <http.port>80</http.port>
        <upload.servlet />
        <upload.servlet.mapping />
        <OAuth2ClientVersion>2.5.47-SNAPSHOT</OAuth2ClientVersion>
    	<aws.java.sdk.version>2.31.40</aws.java.sdk.version>
    	<Register.html>Register.html</Register.html>
	</properties>
	<profiles>
		<profile>
			<id>local</id>
			<properties>
        		<http.port>8080</http.port>
			</properties>
		</profile>
		<profile>
			<id>sentree</id> <!-- voor staging-entree, werkt 8080 niet maar 8000 wel -->
			<properties>
        		<http.port>8000</http.port>
			</properties>
		</profile>
		<profile>
			<id>upload</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
        		<upload.servlet><![CDATA[ 
  <servlet>
  	<servlet-name>upload</servlet-name>
  	<servlet-class>nl.numworx.uploadwidgetgwt.server.Upload</servlet-class>
  	<init-param>
  		<param-name>corsDomainsRegex</param-name>
  		<param-value>.*</param-value>
  	</init-param>
  	<init-param>
  		<param-name>maxSize</param-name>
  		<param-value>52428800</param-value>
  	</init-param>
  	<init-param>
  		<param-name>maxFileSize</param-name>
  		<param-value>52428800</param-value>
  	</init-param>
  </servlet>
  <servlet>
  	<servlet-name>testblob</servlet-name>
  	<servlet-class>nl.numworx.uploadwidgetgwt.server.TestServlet</servlet-class>
  </servlet>
  <servlet>
  	<servlet-name>javaupload</servlet-name>
  	<servlet-class>nl.numworx.uploadwidgetgwt.server.JavaUpload</servlet-class>
  </servlet>
  <servlet>
  	<servlet-name>updownload</servlet-name>
  	<servlet-class>nl.numworx.uploadwidgetgwt.server.Download</servlet-class>
  </servlet>
    <servlet>
  	<servlet-name>proxy</servlet-name>
  	<servlet-class>nl.numworx.uploadwidgetgwt.server.Proxy</servlet-class>
  </servlet>

]]></upload.servlet>
	<upload.servlet.mapping><![CDATA[
  <servlet-mapping>
  	<servlet-name>upload</servlet-name>
    <url-pattern>/dwo/dav/upload/servlet.gupld</url-pattern>
  </servlet-mapping>
  <servlet-mapping>
  	<servlet-name>javaupload</servlet-name>
    <url-pattern>/dwo/dav/upload/dir/*</url-pattern> 
  </servlet-mapping>
  <servlet-mapping>
  	<servlet-name>updownload</servlet-name>
  	<url-pattern>/dwo/dav/upload/download/*</url-pattern>  
  </servlet-mapping>
  <servlet-mapping>
  	<servlet-name>testblob</servlet-name>
  	<url-pattern>/dwo/dav/testblob/*</url-pattern>
  </servlet-mapping>
    <servlet-mapping>
  	<servlet-name>proxy</servlet-name>
  	<url-pattern>/proxy/*</url-pattern>
  </servlet-mapping>
]]></upload.servlet.mapping>		
			</properties>
			<dependencies>
				<dependency>
					<groupId>nl.numworx.uploadwidget</groupId>
					<artifactId>uploadwidgetgwt</artifactId>
					<version>2.5.48</version>
					<classifier>classes</classifier>
					</dependency>			
				<dependency>
				    <groupId>org.slf4j</groupId>
				    <artifactId>slf4j-jdk14</artifactId>
				    <version>1.7.7</version>
				</dependency>
		        <dependency>
				  <groupId>software.amazon.jdbc</groupId>
		  		  <artifactId>aws-advanced-jdbc-wrapper</artifactId>
		  		  <version>2.6.5</version>
		  		  <scope>runtime</scope>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>memcached-jcache</id>
			<build><plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>process-resources</phase>
						<goals><goal>copy-dependencies</goal></goals>
						<configuration>
							<includeGroupIds>de.javakaffee.msm,net.spy</includeGroupIds>
							<outputDirectory>${project.build.directory}/${project.build.finalName}/.ebextensions</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			</plugins>
			</build>
			<dependencies>
				<dependency>
				    <groupId>org.memcached</groupId>
    				<artifactId>memcached-jcache</artifactId>
    				<version>1.0</version>
		    		<scope>runtime</scope>
				</dependency>
				<dependency>
				    <groupId>de.javakaffee.msm</groupId>
				    <artifactId>memcached-session-manager-tc9</artifactId>
				    <version>2.3.2</version>
				    <scope>test</scope>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>ri-jcache</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<dependencies>
					<dependency>
					    <groupId>org.jsr107.ri</groupId>
					    <artifactId>cache-ri-impl</artifactId>
					    <version>1.1.1</version>
					    <scope>runtime</scope>
					</dependency>			
			</dependencies>
		</profile>
		<profile>
			<id>redis-jcache</id>
			<dependencies>
				<dependency>
    				<groupId>nl.uu.fi.dwo.rest</groupId>
					<artifactId>redis-config</artifactId>
					<version>2.5.48</version>
				</dependency>
				<dependency>
					<groupId>org.redisson</groupId>
					<artifactId>redisson-tomcat-9</artifactId>
					<version>3.22.1</version>
					<scope>test</scope>
				</dependency>
				<dependency>
					<groupId>org.redisson</groupId>
					<artifactId>redisson-all</artifactId>
					<version>3.22.1</version>
					<scope>test</scope>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.tomcat.maven</groupId>
						<artifactId>tomcat7-maven-plugin</artifactId>
						<version>2.2</version>
						<dependencies>
								<dependency>
									<groupId>org.redisson</groupId>
									<artifactId>redisson-all</artifactId>
									<version>3.22.1</version>
								</dependency>							
							<dependency>
			    				<groupId>nl.uu.fi.dwo.rest</groupId>
								<artifactId>redis-config</artifactId>
								<version>2.5.48</version>
							</dependency>
						</dependencies>
					</plugin>
					<plugin>
						<artifactId>maven-war-plugin</artifactId>
						<configuration>
							<webResources>
								<resource>
									<directory>src/main/ebextensions/redis</directory>
									<targetPath>.ebextensions</targetPath>
								</resource>
							</webResources>
						</configuration>
					</plugin>
					
					<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<executions>
					<execution>
						<id>copy-redis</id>
						<phase>process-resources</phase>
						<goals><goal>copy-dependencies</goal></goals>
						<configuration>
							<includeGroupIds>org.redisson</includeGroupIds>
							<includeArtifactIds>redisson-all,redisson-tomcat-9</includeArtifactIds>
							<outputDirectory>${project.build.directory}/${project.build.finalName}/.ebextensions</outputDirectory>
						</configuration>
					</execution>
					<execution>
						<id>copy-config</id>
						<phase>process-resources</phase>
						<goals><goal>copy-dependencies</goal></goals>
						<configuration>
							<includeGroupIds>nl.uu.fi.dwo.rest</includeGroupIds>
							<includeArtifactIds>redis-config</includeArtifactIds>
							<outputDirectory>${project.build.directory}/${project.build.finalName}/.ebextensions</outputDirectory>
						</configuration>
					</execution>
				</executions>
					</plugin>
				</plugins>
			</build>		
		</profile>
		<profile>
			<id>repos</id>
			<dependencies>
		<dependency>
			<groupId>fi.tegels</groupId>
			<artifactId>tegels</artifactId>
			<version>0.0.1</version>
		</dependency>
		<dependency>
			<groupId>fi.mozarch</groupId>
			<artifactId>mozarch</artifactId>
			<version>0.0.1</version>
		</dependency>
		<dependency>
			<groupId>fi.verknippen</groupId>
			<artifactId>verknippen</artifactId>
			<version>0.0.1</version>
		</dependency>				
			</dependencies>
		</profile>
		<profile>
			<id>registerFree</id>
			<properties>
				<Register.html>RegisterFree.html</Register.html>
			</properties>
		</profile>
	</profiles>
</project>
